Contrib roles
sul-dlss/dor-services-app pull request #1206
Opened 2020-10-21 23:55 UTC by ndushay

## Why was this change made?

Fixes #1105 - implement from_ and to_ fedora mapping for contributor roles
Fixes #1161 - cocina mapping error for role when namePart is empty

Note that #1161 refers to the stage object https://argo-stage.stanford.edu/view/druid:pd967mn2579 which has funky empty name stuff:

```
  <name>
    <namePart/>
    <role>
      <roleTerm authority="marcrelator" type="text"/>
    </role>
```

Note that roleTerm has attributes but no value, so it is, effectively, no information.

Since contributor roles and all that were already defined fully in cocina-models, I believe I have no openapi changes and no type checking to add - please let me know if that's wrong.

## How was this change tested?

unit tests.  Made a point of using the same starting xml in "from_fedora" specs that I expected in "to_fedora specs.

## Which documentation and/or configurations were updated?

2020-10-22 02:06 UTC, jcoyne requested changes

2020-10-22 02:06 UTC, jcoyne commented on spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
> +              <roleTerm type="code" authority="marcrelator" authorityURI="http://id.loc.gov/vocabulary/relators/" valueURI="http://id.loc.gov/vocabulary/relators/aut">aut</roleTerm>
I'm not seeing this as a case that Arcadia has assigned to us.  Is this something we'd really see?  If so, this should first be an issue in https://github.com/sul-dlss-labs/cocina-descriptive-metadata

2020-10-22 02:06 UTC, jcoyne commented on spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
> +                    "code": 'marcreleator'
I believe we should ask Arcadia to clarify this entire case.  I'm not sure this should become a subject if namePart is nil (see https://github.com/sul-dlss/dor-services-app/issues/1161#issuecomment-709565285)

2020-10-22 16:31 UTC, ndushay commented on spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
> +              <roleTerm type="code" authority="marcrelator" authorityURI="http://id.loc.gov/vocabulary/relators/" valueURI="http://id.loc.gov/vocabulary/relators/aut">aut</roleTerm>
thi sis directly from Arcadia's examples.

2020-10-22 16:34 UTC, ndushay commented on spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
> +                    "code": 'marcreleator'
to be honest, the specific example that was giving a problem was:
- on stage (so perhaps not realistic)
- had non-info in the name part altogether -- the roleTerm indicated an authority and type, but no value -- so who cares?
- seems like an edge case that shouldn't have been coded before implementing roles
- probably doesn't really matter.

2020-10-22 16:36 UTC, ndushay commented on spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
> +  context 'with role' do
i thought it would be more helpful to keep all the "todo" ones together.   If we want to refer to the specification, we can do that with a comment or in the description, no?   Otherwise, we're ordering what will be a very long spec to match an external file we're not linking to, except in TODO comments.

2020-10-22 16:37 UTC, ndushay commented on app/services/cocina/from_fedora/descriptive/contributor.rb
> +          role_authority = name.xpath(ROLE_AUTHORITY_XPATH, mods: DESC_METADATA_NS).first
what was there before was very much skewed towards expecting roleTerm to be a code, only.

2020-10-22 16:37 UTC, ndushay commented on app/services/cocina/to_fedora/descriptive/contributor.rb
> +          attributes[:usage] = 'primary' if contributor&.status == 'primary'
perhaps I was overzealous on this point.

2020-10-22 16:38 UTC, ndushay commented
@jcoyne responded to your comments.  I did check with Mike at the end of the day (because I finished this after you were done with your work day).   Perhaps we should speak in real time to resolve.

2020-10-22 21:44 UTC, jcoyne approved these changes

2020-10-22 23:24 UTC, ndushay commented on spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
> +  context 'with role' do
reverted to original order

2020-10-22 23:24 UTC, ndushay commented on app/services/cocina/from_fedora/descriptive/contributor.rb
> +          role_authority = name.xpath(ROLE_AUTHORITY_XPATH, mods: DESC_METADATA_NS).first
switched this back to what was there.

2020-10-23 00:41 UTC, ndushay commented on spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
> +              <roleTerm type="code" authority="marcrelator" authorityURI="http://id.loc.gov/vocabulary/relators/" valueURI="http://id.loc.gov/vocabulary/relators/aut">aut</roleTerm>
I filed sul-dlss-labs/cocina-descriptive-metadata/issues/91 requesting additional examples to match what I added in this PR.

2020-10-23 00:55 UTC, ndushay commented on spec/services/cocina/from_fedora/descriptive/contributor_spec.rb
> +                    "code": 'marcreleator'
filed https://github.com/sul-dlss-labs/cocina-descriptive-metadata/issues/92

2020-10-23 02:09 UTC, ndushay commented on app/services/cocina/to_fedora/descriptive/contributor.rb
> +          attributes[:usage] = 'primary' if contributor&.status == 'primary'
oh - for empty elements, such as those in the existing test (checking that error is thrown when there is no authority) and the new test added for #1161.  :-P

2020-10-23 02:14 UTC, merged