implement language mappings to_ and from_fedora per Arcadia's examples
sul-dlss/dor-services-app pull request #1256
Opened 2020-10-27 21:56 UTC by ndushay

**NOTE:  we have a partial mapping for language;  this may actually reduce the number of errors ... not sure if this should be held as a "new mapping" or not.**

## Why was this change made?

Fixes #1216 -- what to do with the language element `objectPart` attribute
Fixes #1090 -- mapping the language element.   (@jcoyne had this ticket. I believe he did PR #1130, which was a beginning, and this PR does the rest)

This PR implements all of Arcadia's examples in https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/master/mods_cocina_mappings/mods_to_cocina_language.txt for both "from_fedora" and "to_fedora" .

Note that the known examples that were failing in prod are covered by the specs:

#1248 - from gf100ky7916 (quick fix with PR #1249), which has

```xml
<language>
    <languageTerm type="text">Latin</languageTerm>
    <languageTerm type="code" authority="iso639-2b">lat</languageTerm>
  </language>
```

specs have langTerm of type text analogous to above, and langTerm type code analogous to above, and "text" and "code" langTerms occurring together and apart.

#1240 - from md951vt4966 (quick fix with PR #1246), which has 

```xml
<language>
    <languageTerm type="code" authority="iso639-2b">eng</languageTerm>
  </language>
```
specs now cover this case.

bb012xz4244, from honeybadger which has 

```xml
  <language>
    <languageTerm authority="iso639-2b" authorityURI="http://id.loc.gov/vocabulary/iso639-2" valueURI="http://id.loc.gov/vocabulary/iso639-2/eng" type="code">eng</languageTerm>
    <languageTerm authority="iso639-2b" authorityURI="http://id.loc.gov/vocabulary/iso639-2" valueURI="http://id.loc.gov/vocabulary/iso639-2/eng" type="text">English</languageTerm>
  </language>
```
specs now cover this case.

## How was this change tested?

Wrote functional specs directly off Arcadia's examples in https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/master/mods_cocina_mappings/mods_to_cocina_language.txt

## Which documentation and/or configurations were updated?

2020-10-27 22:35 UTC, jcoyne requested changes

2020-10-27 22:35 UTC, jcoyne commented on app/services/cocina/from_fedora/descriptive/language.rb
> +            code ||= script_term_node.xpath('text()').to_s if script_term_node.xpath('@type').to_s == 'code'
I find that using the methods on the node is easier to understand. What do you think of this?
```suggestion
            code ||= script_term_node.content if script_term_node['type'] == 'code'
```

2020-10-27 22:35 UTC, jcoyne commented on app/services/cocina/from_fedora/descriptive/language.rb
> +            value ||= script_term_node.xpath('text()').to_s if script_term_node.xpath('@type').to_s == 'text'
```suggestion
            code ||= script_term_node.content if script_term_node['type'] == 'text'
```

2020-10-27 22:35 UTC, jcoyne commented on app/services/cocina/from_fedora/descriptive/language.rb
> +            authority ||= script_term_node.xpath('@authority').to_s
```suggestion
            authority ||= script_term_node['authority']
```

2020-10-27 22:35 UTC, jcoyne commented on app/services/cocina/from_fedora/descriptive/language.rb
> +          }.reject { |_k, v| v.blank? }
```suggestion
          }.compact
```

2020-10-27 22:35 UTC, jcoyne commented on app/services/cocina/from_fedora/descriptive/language.rb
> +          [value: lang.xpath(OBJECT_PART_XPATH, mods: DESC_METADATA_NS).to_s] if lang.xpath(OBJECT_PART_XPATH, mods: DESC_METADATA_NS).to_s.present?
```suggestion
          value = lang.xpath(OBJECT_PART_XPATH, mods: DESC_METADATA_NS).to_s
          [value: value] if value.present?
```

2020-10-27 22:35 UTC, jcoyne commented on app/services/cocina/from_fedora/descriptive/language.rb
> +        DISPLAY_LABEL_XPATH = './@displayLabel'
Can we move these strings that are only used one time into the method that uses them?  That makes it easier to read because you don't have to refer back here for the definitions.  I recognize there was an established pattern here, but I'm not a huge fan.  It would also be okay if we want to do that in another PR. I mostly want to hear your thoughts on this idea.

2020-10-27 22:35 UTC, jcoyne commented on app/services/cocina/from_fedora/descriptive/language.rb
> +          }.reject { |_k, v| v.blank? }
```suggestion
          }.compact
```

2020-10-27 22:35 UTC, jcoyne commented on app/services/cocina/from_fedora/descriptive/language.rb
>            }.reject { |_k, v| v.blank? }
I recognize this is not yours, but `.compact` here would be great too.

2020-10-27 22:35 UTC, jcoyne commented on app/services/cocina/to_fedora/descriptive/language.rb
> +          top_attributes[:objectPart] = applies_to_first_value(language.appliesTo) if applies_to_first_value(language.appliesTo)
```suggestion
          applies_to = applies_to_first_value(language.appliesTo)
          top_attributes[:objectPart] = applies_to if applies_to
```

2020-10-27 22:35 UTC, jcoyne commented on app/services/cocina/to_fedora/descriptive/language.rb
> +            if language.code
should this be an `else if`?

2020-10-28 02:07 UTC, justinlittman commented
@ndushay The problem that was causing the errors has been fixed, so I would suggest that this is a new mapping.

2020-10-28 03:30 UTC, ndushay commented on app/services/cocina/to_fedora/descriptive/language.rb
> +            if language.code
no - a language can have both a code and a value or it can have just one of them.

2020-10-28 03:32 UTC, ndushay commented on app/services/cocina/from_fedora/descriptive/language.rb
> +        DISPLAY_LABEL_XPATH = './@displayLabel'
I slightly prefer the constants to call out the hardcoded xpath expressions, but if they are only used once, i prefer them to be near the method using them.   I haven't liked this pattern of having them all together at the top.  I like the idea of addressing this as a separate PR.   Perhaps for ALL the from_fedora mapping classes at once, so we can abolish the yucky pattern and create one we like.

2020-10-28 03:47 UTC, ndushay commented on app/services/cocina/from_fedora/descriptive/language.rb
> +          }.reject { |_k, v| v.blank? }
nice.  I was following an established pattern for this as well!

2020-10-28 03:47 UTC, ndushay commented on app/services/cocina/from_fedora/descriptive/language.rb
>            }.reject { |_k, v| v.blank? }
I get errors using compact here, e.g.

```
 5) Cocina::FromFedora::Descriptive::Language with language code only builds the cocina data structure
     Failure/Error:
       expect(build).to eq [
         {
           "code": 'eng',
           "source": {
             "code": 'iso639-2b'
           }
         }
       ]
     
       expected: [{:code=>"eng", :source=>{:code=>"iso639-2b"}}]
            got: [{:code=>"eng", :source=>{:code=>"iso639-2b", :uri=>""}}]
     
       (compared using ==)
     
       Diff:
       @@ -1 +1 @@
       -[{:code=>"eng", :source=>{:code=>"iso639-2b"}}]
       +[{:code=>"eng", :source=>{:code=>"iso639-2b", :uri=>""}}]
       
     # ./spec/services/cocina/from_fedora/descriptive/language_spec.rb:71:in `block (3 levels) in <top (required)>'
```

2020-10-28 03:47 UTC, ndushay commented on app/services/cocina/from_fedora/descriptive/language.rb
> +            code ||= script_term_node.xpath('text()').to_s if script_term_node.xpath('@type').to_s == 'code'
thanks!  this is nicer!

2020-10-28 03:47 UTC, ndushay commented on app/services/cocina/from_fedora/descriptive/language.rb
> +          }.reject { |_k, v| v.blank? }
this one does NOT cause errors. yay!

2020-10-28 03:47 UTC, ndushay commented on app/services/cocina/from_fedora/descriptive/language.rb
> +          [value: lang.xpath(OBJECT_PART_XPATH, mods: DESC_METADATA_NS).to_s] if lang.xpath(OBJECT_PART_XPATH, mods: DESC_METADATA_NS).to_s.present?
yes, nicer!

2020-10-28 03:52 UTC, ndushay commented on app/services/cocina/to_fedora/descriptive/language.rb
> +          top_attributes[:objectPart] = applies_to_first_value(language.appliesTo) if applies_to_first_value(language.appliesTo)
👍

2020-10-28 03:54 UTC, jcoyne commented on app/services/cocina/from_fedora/descriptive/language.rb
> +          }.reject { |_k, v| v.blank? }
Ah, I forgot about the empty string case.  Compact is only for the nil values.

2020-10-28 03:54 UTC, jcoyne approved these changes

2020-10-28 03:56 UTC, ndushay commented
@jcoyne I took all of your suggestions that didn't cause test failures.

@justinlittman I think this is exactly the edge case that is confusing:  we have solved the language mapping bugs we have run across SO FAR, but the additional mappings in this PR are for anticipated issues with language mappings.

I would consider this "new mappings" if the language element hadn't been mapped at all yet ... but since it is partially mapped ... doesn't this solve problems rather than create them?   I thought there were no errors if we didn't map a MODS element at all, but if we map it partially, then what?

2020-10-29 16:27 UTC, justinlittman commented
I've tested this and it produces no new errors.

2020-10-29 16:41 UTC, merged