Adds scripts for creating cache and validating mapping to Cocina.
sul-dlss/dor-services-app pull request #1259
Opened 2020-10-28 12:48 UTC by justinlittman

## Why was this change made?
Provide tooling for testing Cocina mappings.

## How was this change tested?
Locally.

## Which documentation and/or configurations were updated?
README

2020-10-28 14:28 UTC, ndushay reviewed
Looks pretty awesome.  I'm thinking there should be tests for the rubydora patch.

I'm making this a comment rather than a "request changes" so I can be easily overruled on my suggestions.

2020-10-28 14:28 UTC, ndushay commented on README.md
> +
perhaps include "remove Solr Tunnel" as a step -- we lost the Argo production index due to a tunnel left open in the past ...

2020-10-28 14:28 UTC, ndushay commented on README.md
> +        scp -r dor_services@dor-services-prod.stanford.edu:/etc/pki/tls .
i suspect this is fine, but we've had some ops folks suggest it's better if we don't get this specific in a public repo

2020-10-28 14:28 UTC, ndushay commented on README.md
> +Error: undefined method `text' for nil:NilClass (32 errors)
this is a great start.  In the future, maybe we can dig a little deeper and determine which class is giving the nil error (e.g. adminMetadata?  contributor?  subject?)

2020-10-28 14:28 UTC, ndushay commented on lib/rubydora_patch.rb
> +# Patch Rubydora::RestApiClient to inject cache
maybe "... to allow local caching of DOR content (for validating cocina mappings)" ?

2020-10-28 14:40 UTC, justinlittman commented on README.md
> +
Yup. Added.

2020-10-28 15:19 UTC, justinlittman commented on README.md
> +        scp -r dor_services@dor-services-prod.stanford.edu:/etc/pki/tls .
Obscured.

2020-10-28 15:19 UTC, justinlittman commented on lib/rubydora_patch.rb
> +# Patch Rubydora::RestApiClient to inject cache
Done.

2020-10-28 15:39 UTC, ndushay commented on README.md
> +          url: 'https://sul-solr.stanford.edu/solr/argo3_prod'
it might just be argo_prod now??   I think cbeer renamed it and argo3_prod is somehow a link?   not sure.

2020-10-28 15:47 UTC, ndushay commented on bin/generate-druid-list
> +  results = ActiveFedora::SolrService.query('*:*', sort: 'random asc', fl: 'id', rows: REQUEST_SIZE)
add `fq: '-has_model_ssim:"info:fedora/afmodel:Part"'` as a query argument here (to avoid ETD part objects)

2020-10-28 16:03 UTC, ndushay commented on bin/generate-druid-list
> +  results = ActiveFedora::SolrService.query('*:*', sort: 'random asc', fl: 'id', rows: REQUEST_SIZE)
also, if you add wt=csv, then you'll get back something even easier to parse:

https://sul-solr-b.stanford.edu/solr/argo_prod/select?q=*:*&sort=random%20asc&fl=id&rows=10&fq=-has_model_ssim:%22info:fedora/afmodel:Part%22&wt=csv

```
id
druid:bk427kz4094
druid:yk877xp5181
druid:zz155sv2614
druid:qy805wh8168
druid:sw089sm8303
druid:ks499fs9755
druid:wx897vx0942
druid:xh465yn6146
druid:jv693gg2872
druid:nr368fk3363
```

2020-10-28 16:13 UTC, ndushay commented
Aside from my suggestions for the Solr query, I'd say let's get this merged and tweak it further in additional PRs.

2020-10-28 16:31 UTC, ndushay requested changes
Happy to merge with the Solr query changes

2020-10-28 16:33 UTC, justinlittman commented on README.md
> +          url: 'https://sul-solr.stanford.edu/solr/argo3_prod'
Not sure. This is what was in prod config.

2020-10-29 11:20 UTC, justinlittman commented
@ndushay This is ready for re-review at your convenience.

2020-10-29 15:53 UTC, ndushay approved these changes

2020-10-29 15:55 UTC, merged