fix subject name mapping from fedora when name has no type
sul-dlss/dor-services-app pull request #1282
Opened 2020-10-28 19:14 UTC by ndushay

## Why was this change made?

Fixes #1265 

Also updates references to mapping specification for xit statements.

## How was this change tested?

Was able to reproduce the error locally with new unit test, and the fix addressed it.

## Which documentation and/or configurations were updated?

2020-10-28 21:28 UTC, jcoyne commented on spec/services/cocina/from_fedora/descriptive/subject_spec.rb
> +    context 'without name type' do
Did you run this by @arcadiafalcone?  Did she agree that this is not a data error? Does an example need to be added into https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/master/mods_cocina_mappings/mods_to_cocina_subject.txt?

2020-10-28 22:04 UTC, jcoyne requested changes
After talking with Arcadia this sounds like a data error, so maybe we shouldn't apply this change.

2020-10-29 00:20 UTC, ndushay commented
I am closing this PR, as you were on top of spotting this as a data error rather than a mapping error!   Thank you.

2020-10-29 00:23 UTC, ndushay commented
Hrmm - I need to look at more examples -- it may be the one I chose to use as a spec was a data error but I don't think they all are.

2020-10-29 00:49 UTC, ndushay commented
@jcoyne fixed the example in the spec to be data that has the problem, but isn't a subject masquerading as a name.

2020-10-29 03:06 UTC, jcoyne requested changes

2020-10-29 03:06 UTC, jcoyne commented on spec/services/cocina/from_fedora/descriptive/subject_spec.rb
> +            <name>
Have we asked @arcadiafalcone if this shouldn't have `type="organization"` for this to be valid?

2020-10-29 06:03 UTC, ndushay commented on spec/services/cocina/from_fedora/descriptive/subject_spec.rb
> +            <name>
nope, I haven't talked to @arcadiafalcone .  We clearly have data like this, tho.  JLitt trapped 55 errors in his random sample ...

This fix avoids errors ... but whether it also needs to notify honeybadger for bad data ... I couldn't say.

2020-10-29 17:00 UTC, ndushay commented
@jcoyne ready for re-review

2020-10-29 17:58 UTC, justinlittman commented on spec/services/cocina/from_fedora/descriptive/subject_spec.rb
> +            <name>
From @arcadiafalcone:
> ideally type="personal" would be present, but it's not required. i would like to remediate these, but it's valid mods to not have it.

So perhaps we should HB alert when no type?

2020-10-29 18:21 UTC, arcadiafalcone commented on spec/services/cocina/from_fedora/descriptive/subject_spec.rb
> +            <name>
Yes, alert for it but let it pass. 64 out of 373 nil_key errors I analyzed were bad data for reasons other than the missing type, and the rest were just missing the attribute. Missing the type doesn't make the records invalid MODS, but it will cause problems generating data in other schemas down the line and can be a symptom of something else wrong with the data.

2020-10-29 18:25 UTC, jcoyne approved these changes

2020-10-29 19:19 UTC, ndushay reviewed
Just pushed commit that alerts honeybadger when subject name has no type attribute.

2020-10-29 19:19 UTC, ndushay commented on spec/services/cocina/from_fedora/descriptive/subject_spec.rb
> +            <name>
Just pushed commit that alerts honeybadger when subject name has no type attribute.

2020-10-29 19:20 UTC, ndushay commented
@jcoyne @justinlittman this now alerts Honeybadger when there is no type attribute on a name subject.

2020-10-29 19:39 UTC, jcoyne approved these changes

2020-10-29 19:39 UTC, merged

2020-10-29 19:53 UTC, justinlittman commented
Verified that this reduces errors.