Fixes handling of role code.
sul-dlss/dor-services-app pull request #1301
Opened 2020-10-30 17:49 UTC by justinlittman

addresses problem in #1290

## Why was this change made?
To satisfy the requirement:
```
If there's a valueURI without an authority attribute, that's valid and doesn't need to be reported. If the value is three letters, let it pass without the authority attribute and report it as an error. If the value is not three letters, something unpredictable is wrong with the data and it should fail.
```

## How was this change tested?
Unit

## Which documentation and/or configurations were updated?
NA

2020-10-30 19:30 UTC, jcoyne commented on app/services/cocina/from_fedora/descriptive/contributor.rb
> -        # rubocop:disable Metrics/PerceivedComplexity
👏

2020-10-30 19:32 UTC, jcoyne requested changes

2020-10-30 19:32 UTC, jcoyne commented on app/services/cocina/from_fedora/descriptive/contributor.rb
> +          if role_code&.content.present? && role_code.content.size == 3
I don't think you need `&.` here because you've already checked that it's not nil.

2020-10-30 19:32 UTC, jcoyne requested changes

2020-10-30 19:32 UTC, jcoyne commented on app/services/cocina/from_fedora/descriptive/contributor.rb
> +          raise Cocina::Mapper::InvalidDescMetadata, "Contributor role code is missing and has unexpected value: #{role_code&.content}"
Nil check isn't needed here either.

2020-11-02 23:26 UTC, ndushay commented
Please assign #1290 to Arcadia after this is merged.

2020-11-06 14:01 UTC, justinlittman commented on app/services/cocina/from_fedora/descriptive/contributor.rb
> +          if role_code&.content.present? && role_code.content.size == 3
Fixed.

2020-11-06 14:01 UTC, justinlittman commented on app/services/cocina/from_fedora/descriptive/contributor.rb
> +          raise Cocina::Mapper::InvalidDescMetadata, "Contributor role code is missing and has unexpected value: #{role_code&.content}"
Fixed.

2020-11-09 14:04 UTC, jcoyne requested changes

2020-11-09 14:04 UTC, jcoyne commented on .rubocop_todo.yml
> +  Max: 118
👏

2020-11-09 14:04 UTC, jcoyne commented on .rubocop_todo.yml
> +  Max: 15
😢  Can you add an exception on one method rather than increasing the threshold for all methods?

2020-11-09 14:27 UTC, jcoyne approved these changes

2020-11-09 14:27 UTC, merged