Empty key not found
sul-dlss/dor-services-app pull request #1305
Opened 2020-11-02 19:54 UTC by ndushay

## Why was this change made?

To add mappings indicated for #1276  (nils for `name/role/roleTerm` values)

bonus content:
- addressed nil `name/namePart` values 
- added fleshed out some TODO specs where code was already implemented.

Before merging:
- [ ] Run this change through from-fedora-to-cocina validator on sdr-deploy to ensure it doesn't add mapping errors

## How was this change tested?

- wrote unit tests per Arcadia's specs.
-  from-fedora-to-cocina validator 

## Which documentation and/or configurations were updated?

2020-11-02 19:57 UTC, ndushay commented on spec/services/cocina/to_fedora/descriptive/contributor_spec.rb
> -    xit 'TODO: https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/master/mods_cocina_mappings/mods_to_cocina_name.txt#L365'
this was implemented, but the xit was still here.

2020-11-02 20:45 UTC, ndushay commented
tests ran green - not sure what's up with reporting -   https://app.circleci.com/pipelines/github/sul-dlss/dor-services-app?branch=empty-key-not-found

2020-11-02 22:44 UTC, ndushay commented
Diff between validation results  of master branch and this branch:

```
< 758 of 350000 (0.21657142857142858%)
---
> 723 of 350000 (0.20657142857142857%)
677,713d676
< Error: key not found: "" (36 errors)
< druid:bv906dj0910
< druid:ft228gt4019
< druid:fq254hh2957
< druid:ff265xb5816
< druid:dh545kq3183
< druid:ct356kk5797
< druid:zx867rz8188
< druid:dx835nd1155
< druid:pk902jf7671
< druid:hk474mp2227
< druid:tm789ny6770
< druid:jm814nd6955
< druid:fb924nn9794
< druid:gm077tf4677
< druid:qw752qv9051
< druid:kd537gt3922
< druid:rn180rz6204
< druid:tx708fh9017
< druid:hp834gf5386
< druid:qn096dd3767
< druid:zx668nd2259
< druid:ph333tb3281
< druid:jz887db3108
< druid:sx420wp6433
< druid:hz399yx0876
< druid:wc593yj6369
< druid:cw099tk2420
< druid:hv256ds4205
< druid:hn018yf1183
< druid:yc736tf5625
< druid:fw661pz6503
< druid:bf650pm8076
< druid:nc548jv8806
< druid:nz272nr8945
< druid:mj772yw8319
< druid:mj734dt0131
```

2020-11-03 04:10 UTC, jcoyne requested changes

2020-11-03 04:10 UTC, jcoyne commented on app/services/cocina/from_fedora/descriptive/contributor.rb
> +              # rubocop:enable Style/MultilineBlockChain
This method is getting very confusing to read, and this is an indicator that it coupld possibly be a bit clearer.  Can you extract a `build_contributor(name)` method from this method?

2020-11-03 04:10 UTC, jcoyne commented on app/services/cocina/from_fedora/descriptive/contributor.rb
> +            unless role[:code] || role[:value]
I find that `if !role[:code] && !role[:value]` is a little easier to read. What do you think?

2020-11-03 16:20 UTC, ndushay commented on app/services/cocina/from_fedora/descriptive/contributor.rb
> +            unless role[:code] || role[:value]
I agree.  :-)

2020-11-03 16:20 UTC, ndushay commented on app/services/cocina/from_fedora/descriptive/contributor.rb
> +              # rubocop:enable Style/MultilineBlockChain
great idea.

2020-11-03 16:21 UTC, ndushay commented
@jcoyne took both of your suggestions.

2020-11-03 16:22 UTC, jcoyne approved these changes
Thank you!

2020-11-03 16:23 UTC, merged