subject mapping fixes for topic - two separate causes
sul-dlss/dor-services-app pull request #1308
Opened 2020-11-03 19:20 UTC by ndushay

## Why was this change made?

To add mapping grease for #1291 (`<Topic>` element uppercase)  and #1306 (`<subject><name>` has invalid type attribute of "topic")

## How was this change tested?

- wrote unit tests for these cases
- with from-fedora-to-cocina validator

```
$ diff results-master-branch.txt results-topic-branch.txt 
698,721d641
< Error: key not found: "Topic" (11 errors)
< druid:xv661kx4223
< druid:qr684zq1130
< druid:xy743kk5793
< druid:yw448qd5583
< druid:ky082np9069
< druid:gf424bq2099
< druid:rd235fv8920
< druid:fz099qm8777
< druid:bq782pp3515
< druid:jx066kr2212
< druid:qt282gh9166
729,730d648
< Error: key not found: "topic" (1 errors)
< druid:kd333yz5798
```

## Which documentation and/or configurations were updated?

2020-11-03 19:23 UTC, ndushay commented
mapping grease applied in #1308

2020-11-04 15:45 UTC, justinlittman requested changes

2020-11-04 15:45 UTC, justinlittman commented on app/services/cocina/from_fedora/descriptive/subject.rb
> +            Honeybadger.notify('Data error: <subject> has <Topic>; normalized to "topic"', tags: 'data_error')
`[DATA ERROR]` please.

2020-11-04 16:12 UTC, ndushay commented on app/services/cocina/from_fedora/descriptive/subject.rb
> +            Honeybadger.notify('Data error: <subject> has <Topic>; normalized to "topic"', tags: 'data_error')
normalized all to [DATA ERROR] (throughout app)

2020-11-04 16:16 UTC, justinlittman approved these changes

2020-11-04 16:16 UTC, merged