name mapping fix for unrecognized type attribute value
sul-dlss/dor-services-app pull request #1309
Opened 2020-11-03 19:57 UTC by ndushay

## Why was this change made?

To add mapping grease for #1292 (`<name>` has invalid type attribute of 'primary') and #1293 (`<name>` has invalid type attribute of 'naf')

## How was this change tested?

- wrote unit tests for these cases
- with from-fedora-to-cocina validator

    ```
    will insert results here
    ```

## Which documentation and/or configurations were updated?

2020-11-03 20:22 UTC, jcoyne requested changes

2020-11-03 20:22 UTC, jcoyne commented on .rubocop_todo.yml
> +  Max: 122
Please don't increase this for every class in the project. Just add an exception for the class you are working on if you don't want to refactor.

2020-11-03 21:39 UTC, ndushay commented on .rubocop_todo.yml
> +  Max: 122
i figured in this one case, because it was only going up by 3, it made sense.  If it had been a bigger increase, I would have done as you suggested.  I can put the exception in the class.

I suspect the _todo file hadn't been regenned in some time, as a bunch of other occurrence counts went up.  :-(

2020-11-03 23:50 UTC, ndushay commented
@jcoyne redid the rubocop commit.

2020-11-04 02:01 UTC, jcoyne approved these changes
Thank you!

2020-11-04 02:01 UTC, merged