Add directions on generating a full list of druids.
sul-dlss/dor-services-app pull request #1331
Opened 2020-11-06 14:05 UTC by justinlittman

## Why was this change made?
To document how to generate a full list of druids.

## How was this change tested?
NA

## Which documentation and/or configurations were updated?
README.

2020-11-06 15:36 UTC, ndushay requested changes

2020-11-06 15:36 UTC, ndushay commented on README.md
> +mysql --user=fedora --password fedora -e "select doPID from doRegistry where doPID like 'druid:%';" -N | cut -c 1-17 > druids.txt
is the "cut" part getting rid of noise lines in the output?  Also wondering if this is more of a wiki thing since it's not really part of this app, but a part of Fedora.

2020-11-06 16:10 UTC, justinlittman commented on README.md
> +mysql --user=fedora --password fedora -e "select doPID from doRegistry where doPID like 'druid:%';" -N | cut -c 1-17 > druids.txt
It is getting rid of table formatting noise.

Which wiki would you recommend?

2020-11-06 22:27 UTC, ndushay commented on README.md
> +mysql --user=fedora --password fedora -e "select doPID from doRegistry where doPID like 'druid:%';" -N | cut -c 1-17 > druids.txt
wiki for this app would be fine with me, or ???   @jmartin-sul @jcoyne @mjgiarlo have any feelings about where this documentation should live?

2020-11-06 22:31 UTC, mjgiarlo commented on README.md
> +mysql --user=fedora --password fedora -e "select doPID from doRegistry where doPID like 'druid:%';" -N | cut -c 1-17 > druids.txt
I think it's OK for the README given it's related to the prior section, but I don't have strong feelings on this.

2020-11-09 13:35 UTC, jcoyne commented on README.md
> +mysql --user=fedora --password fedora -e "select doPID from doRegistry where doPID like 'druid:%';" -N | cut -c 1-17 > druids.txt
👎 to wikis. Put it in the repo (not necessarily the readme)

2020-11-11 18:58 UTC, mjgiarlo commented
@ndushay are you cool with this going forward until we have a better place to stash this info?

2020-11-12 00:56 UTC, ndushay approved these changes
whatever.  I dunno where to stash it.  devopsdocs?  readme on sul-dor-xxx ?

2020-11-12 00:56 UTC, merged