H2 contrib publisher mappings
sul-dlss/dor-services-app pull request #1456
Opened 2020-11-20 19:04 UTC by ndushay

## Why was this change made?

Part of #1375 - changes to DSA needed for h2 publisher contributors (but of benefit to all our MODS data - cough cough)

## How was this change tested?

- unit tests
    - any tweaks to existing tests were confirmed as correct by Arcadia
    - got H2 contributor publication mapping tests to pass

- need to test mappings on prod data

## Which documentation and/or configurations were updated?

2020-11-20 19:49 UTC, ndushay commented on app/services/cocina/to_fedora/descriptive/event.rb
> -            attributes[:eventType] = EVENT_TYPE.fetch(event.type) if events.size > 1 && event.type
I spoke with Arcadia about this and it is fine to add eventType if we have it;  it was not avail until MODS 3.5 or something, but anything running through this code is ok.

However, it may affect roundtrip comparisons???

2020-11-20 19:49 UTC, ndushay commented on app/services/cocina/to_fedora/descriptive/event.rb
> +          return unless contributor_role_publisher?(contributor)
also confirmed this with Arcadia.  Other contributor types don't have a valid MODS element.  We should only get to EVENT from contributor for publisher in any case.

2020-11-20 19:49 UTC, ndushay commented on app/services/cocina/to_fedora/descriptive/event.rb
>            name = contributor.name.first
assuming one contributor lalalalalala

2020-11-20 20:35 UTC, ndushay commented
## Validation Results

### Roudntrip Before

```
Status (n=250000):
  Success:   92806 (37.1224%)
  Different: 155621 (62.2484%)
  To Cocina error:     98 (0.0392%)
  To Fedora error:     6 (0.0024%)
  Missing:     1469 (0.5876%)
```

### Roundtrip After

```
```

NOTE:  eventType attribute added to events will cause roundtrip to fail, but this change has been approved by Arcadia

2020-11-21 18:20 UTC, ndushay commented on app/services/cocina/to_fedora/descriptive/event.rb
> -            attributes[:eventType] = EVENT_TYPE.fetch(event.type) if events.size > 1 && event.type
I have added a normalization to roundtrip validations that accounts for this.

2020-11-21 18:52 UTC, jcoyne requested changes

2020-11-21 18:52 UTC, jcoyne commented on app/services/cocina/to_fedora/descriptive/contributor.rb
> +        # write marcrelator roles only if any are present, otherwise write other roles
Why did you choose to change this description?  It does look like it's returning those, isn't it?

2020-11-21 18:52 UTC, jcoyne commented on app/services/cocina/to_fedora/descriptive/event.rb
> +          xml.send('publisher', name.value, attributes)
why do send if we know the name of the method?
```suggestion
          xml.publisher(name.value, attributes)
```

2020-11-21 18:52 UTC, jcoyne commented on app/services/cocina/to_fedora/descriptive/event.rb
> +          contributor.role.any? { |role| role.value&.content&.match?(/publisher/i) }
It looks like this line needs a test.

2020-11-21 18:52 UTC, jcoyne commented on app/services/cocina/to_fedora/descriptive/event.rb
> +        def contributor_role_publisher?(contributor)
Could this take the role itself, rather than the whole publisher?

2020-11-21 19:29 UTC, ndushay commented on app/services/cocina/to_fedora/descriptive/contributor.rb
> +        # write marcrelator roles only if any are present, otherwise write other roles
stupidity?   fixing.

2020-11-21 19:31 UTC, ndushay commented on app/services/cocina/to_fedora/descriptive/event.rb
> +          xml.send('publisher', name.value, attributes)
good point.  fixing.

2020-11-21 19:37 UTC, ndushay commented on app/services/cocina/to_fedora/descriptive/event.rb
> +        def contributor_role_publisher?(contributor)
no, because we have to check all roles, potentially.  This code happened because the first role had value H2 'Publisher' rather than marcrelator 'publisher.'   :-P

2020-11-21 19:45 UTC, ndushay commented on app/services/cocina/to_fedora/descriptive/event.rb
> +          contributor.role.any? { |role| role.value&.content&.match?(/publisher/i) }
good catch.  line had a bug.  test added.

2020-11-23 16:02 UTC, jcoyne commented on app/services/cocina/to_fedora/descriptive/event.rb
> +        def contributor_role_publisher?(contributor)
I guess what I meant was the roles array.

2020-11-23 17:15 UTC, ndushay commented on app/services/cocina/to_fedora/descriptive/event.rb
> +        def contributor_role_publisher?(contributor)
what does that actually gain us?  passed by reference anyway ...

2020-11-23 18:13 UTC, mjgiarlo commented
@jcoyne mind having another look at this?

2020-11-24 00:59 UTC, jcoyne commented on app/services/cocina/to_fedora/descriptive/event.rb
> +        def contributor_role_publisher?(contributor)
It makes the method more testable and the code easier to understand because you know that this method only depends on this one property rather than a whole object.

2020-11-24 01:01 UTC, jcoyne approved these changes
Approved, with a suggestion.

2020-11-24 15:30 UTC, merged