validate-to-cocina, validate-to-fedora: provide option to automatically give result files unique descriptive names
sul-dlss/dor-services-app pull request #1467
Opened 2020-11-23 10:34 UTC by jmartin-sul

## Why was this change made?

When running tests or reports that produce output files, I find it nice when output is easy to associate with the input that produced it, so I added an option to do that for the cocina validation results, since I was running against a number of branches in a row Friday evening.  Figured others might find it useful, and it was quick to write so I thought it'd save me time in the long run.  Old behavior is still the default.

## How was this change tested?

used the new `-u` flag on friday while running validations.

<img width="894" alt="Screen Shot 2020-11-20 at 7 28 42 PM" src="https://user-images.githubusercontent.com/7741604/99951987-ce244e80-2d33-11eb-8529-8914557fdfc5.png">

## Which documentation and/or configurations were updated?

`validate-to-cocina` and `validate-to-fedora` help messages

2020-11-23 12:18 UTC, justinlittman requested changes
Also, please add new flag to options listed in README.

2020-11-23 12:18 UTC, justinlittman commented on bin/validate-to-cocina
> +  option_parser.on('-u', '--unique-filename', 'Result file named for branch and runtime') { options[:unique_filename] = true }
Is `{ options[:unique_filename] = true }` necessary?

2020-11-23 12:18 UTC, justinlittman commented on bin/validate-to-cocina
> +File.open(results_file_name(options), 'w') do |file|
Why pass it all of options and not just `options[:unique_filename]`?

2020-11-23 12:18 UTC, justinlittman commented on bin/validate-to-fedora
> +  option_parser.on('-u', '--unique-filename', 'Result file named for branch and runtime') { options[:unique_filename] = true }
Same comment as above.

2020-11-23 12:18 UTC, justinlittman commented on bin/validate-to-fedora
> +File.open(results_file_name(options), 'w') do |file|
Same comment as above.

2020-12-03 09:50 UTC, jmartin-sul commented on bin/validate-to-cocina
> +  option_parser.on('-u', '--unique-filename', 'Result file named for branch and runtime') { options[:unique_filename] = true }
My recollection is that in the bit of testing I did, I couldn't get `parser.parse!(into: options)` to set a value for `unique-filename` based solely on the presence of the flag, and taking a param value seemed unnecessary, hence the manual setting of `options[:unique_filename]`.  That did bug me a bit, but I also only spent 10 or 15 minutes trying to avoid what I did here (using [`FalseClass` for type coercion with a default](https://ruby-doc.org/stdlib-2.7.2/libdoc/optparse/rdoc/OptionParser.html#class-OptionParser-label-Type+Coercion), iirc).

2020-12-03 09:50 UTC, jmartin-sul commented on bin/validate-to-cocina
> +File.open(results_file_name(options), 'w') do |file|
good point, fixed

2020-12-03 09:52 UTC, jmartin-sul commented on bin/validate-to-fedora
> +  option_parser.on('-u', '--unique-filename', 'Result file named for branch and runtime') { options[:unique_filename] = true }
same reply as that one

2020-12-03 09:52 UTC, jmartin-sul commented on bin/validate-to-fedora
> +File.open(results_file_name(options), 'w') do |file|
also fixed

2020-12-03 09:54 UTC, jmartin-sul commented
made readme and arg passing touchups, replied to the question about manually setting the options value, and re-tested using same invocations as in the issue description.  ready for another look, i think...

2020-12-03 12:03 UTC, justinlittman approved these changes

2020-12-03 12:03 UTC, merged