[DRAFT] Add individual location blocks for each URL
sul-dlss/dor-services-app pull request #1563
Opened 2020-12-01 00:06 UTC by aaron-collier

## Why was this change made?

Fixes #1483 

DRAFT while refactoring.

## How was this change tested?

Additional spec.

## Which documentation and/or configurations were updated?

N/A

2020-12-01 17:44 UTC, justinlittman requested changes
@aaron-collier Can you test this on sdr-deploy?

2020-12-01 18:00 UTC, mjgiarlo approved these changes

2020-12-01 21:30 UTC, aaron-collier commented
@justinlittman I ran the validate-to-fedora and my branch matches master:

Master:

```
Testing |Time: 00:00:12 | =============================================================================================================================================================================================================================== | Time: 00:00:12
To Fedora error: 4 of 10000 (0.04%)
To Cocina error: 1 of 10000 (0.01%)
Data error: 3 of 10000 (0.03%)
Missing: 68 of 10000 (0.68%)

To Fedora error: key not found: "distribution" (2 errors)
Examples: druid:xv158sd4671, druid:rm699mr9758
To Fedora error: key not found: "acquisition" (1 errors)
Examples: druid:xk850mn9988
To Fedora error: key not found: "manufacture" (1 errors)
Examples: druid:qx562pf7510
```


Branch:
```
Testing |Time: 00:00:12 | =============================================================================================================================================================================================================================== | Time: 00:00:12
To Fedora error: 4 of 10000 (0.04%)
To Cocina error: 1 of 10000 (0.01%)
Data error: 3 of 10000 (0.03%)
Missing: 68 of 10000 (0.68%)

To Fedora error: key not found: "distribution" (2 errors)
Examples: druid:xv158sd4671, druid:rm699mr9758
To Fedora error: key not found: "acquisition" (1 errors)
Examples: druid:xk850mn9988
To Fedora error: key not found: "manufacture" (1 errors)
Examples: druid:qx562pf7510
```

2020-12-02 02:30 UTC, justinlittman commented
Actually, best practice now is to  `validate-cocina-roundtrip` to make sure it improves.

Before:
```
Status (n=100000):
  Success:   79659 (79.659%)
  Different: 19669 (19.669%)
  To Cocina error:     33 (0.033%)
  To Fedora error:     29 (0.029%)
  Missing:     610 (0.61%)
```

After:
```
Status (n=100000):
  Success:   51310 (51.31%)
  Different: 48018 (48.018%)
  To Cocina error:     33 (0.033%)
  To Fedora error:     29 (0.029%)
  Missing:     610 (0.61%)
```

So it appears that something isn't right.

2020-12-07 21:54 UTC, aaron-collier commented
@justinlittman I have better results now:

```
MASTER:

Testing |Time: 00:00:38 | ====================================================================================================================================================== | Time: 00:00:38
Status (n=10000):
  Success:   8336 (83.36%)
  Different: 1589 (15.89%)
  To Cocina error:     4 (0.04%)
  To Fedora error:     3 (0.03%)
  Missing:     68 (0.68%)

This Branch:

Testing |Time: 00:00:50 | ====================================================================================================================================================== | Time: 00:00:50
Status (n=10000):
  Success:   7650 (76.5%)
  Different: 2275 (22.75%)
  To Cocina error:     4 (0.04%)
  To Fedora error:     3 (0.03%)
  Missing:     68 (0.68%)
```

I'm not sure yet what if anything can be done about this small drop, the checking I've done with 10000 items locally doesn't show anything specific to location work in the errors... It's mostly originInfo and something else.

2020-12-08 12:32 UTC, justinlittman requested changes

2020-12-08 12:32 UTC, justinlittman commented on app/services/cocina/mods_normalizer.rb
> +        physical_location_nodes(location_node).each do |physical_location|
Since all of these are doing the same, I'd recommend consolidating into something like:
```
location_node.xpath('mods:physicalLocation|mods:url|mods:shelfLocator', mods: Cocina::FromFedora::Descriptive::DESC_METADATA_NS).each do |node|
          new_location = Nokogiri::XML::Node.new('location', Nokogiri::XML(nil))
          new_location << physical_location
          location_node.parent << new_location
end
```

2020-12-08 12:32 UTC, justinlittman commented on app/services/cocina/to_fedora/descriptive/location.rb
>            write_access_conditions if access
Isn't the `if access` here redundant?

2020-12-08 12:32 UTC, justinlittman commented on spec/services/cocina/mods_normalizer_spec.rb
> +  context 'when normalizing physical location purl' do
This test isn't right.

2020-12-08 12:32 UTC, justinlittman commented on spec/services/cocina/to_fedora/descriptive/location_spec.rb
> +  context 'when it has multiple URLs' do
Where are the multiple URLs?

2020-12-08 14:33 UTC, justinlittman commented
Master:
```
Status (n=100000):
  Success:   84480 (84.48%)
  Different: 14853 (14.853%)
  To Cocina error:     33 (0.033%)
  To Fedora error:     24 (0.024%)
  Missing:     610 (0.61%)
```

After the normalization tweak:
```
Status (n=100000):
  Success:   86096 (86.096%)
  Different: 13237 (13.237%)
  To Cocina error:     33 (0.033%)
  To Fedora error:     24 (0.024%)
  Missing:     610 (0.61%)
```

2020-12-08 15:43 UTC, aaron-collier commented on app/services/cocina/to_fedora/descriptive/location.rb
>            write_access_conditions if access
Yeah, good catch. That was an earlier incantation and crufty...

2020-12-08 15:45 UTC, aaron-collier commented on app/services/cocina/to_fedora/descriptive/location.rb
>            write_access_conditions if access
Weird, that's actually already gone locally but doesn't seem to have been pushed up.... strange...

2020-12-08 18:30 UTC, justinlittman requested changes
Two minor changes and then good to go.

2020-12-08 18:30 UTC, justinlittman commented on app/services/cocina/mods_normalizer.rb
> +    def physical_location_nodes(location_node)
No longer necessary, right?

2020-12-08 18:30 UTC, justinlittman commented on spec/services/cocina/mods_normalizer_spec.rb
> +            <physicalLocation>Stanford University Libraries</physicalLocation>
Can you add a shelfLocator into this example?

2020-12-08 18:53 UTC, justinlittman approved these changes

2020-12-08 18:53 UTC, merged