Select event for issuance, etc. based on precedence rule.
sul-dlss/dor-services-app pull request #1580
Opened 2020-12-01 21:54 UTC by justinlittman

closes #1548

## Why was this change made?
Issuance, etc. should be placed on events based on precedence rule (described in ticket).

## How was this change tested?
Unit, sdr-deploy

## Which documentation and/or configurations were updated?
NA

2020-12-01 22:07 UTC, justinlittman commented
Before:
```
Status (n=100000):
  Success:   79662 (79.662%)
  Different: 19666 (19.666%)
  To Cocina error:     33 (0.033%)
  To Fedora error:     29 (0.029%)
  Missing:     610 (0.61%)
```

After:
```
Status (n=100000):
  Success:   79779 (79.779%)
  Different: 19549 (19.549%)
  To Cocina error:     33 (0.033%)
  To Fedora error:     29 (0.029%)
  Missing:     610 (0.61%)
```

2020-12-01 22:11 UTC, jcoyne commented on app/services/cocina/from_fedora/descriptive/event.rb
> +              # byebug
Cruft?

2020-12-01 22:11 UTC, jcoyne requested changes

2020-12-01 22:11 UTC, jcoyne commented on app/services/cocina/from_fedora/descriptive/event.rb
> +        def find_event(events, event_type)
Does anything ever call this method?

2020-12-02 00:10 UTC, mjgiarlo commented on app/services/cocina/from_fedora/descriptive/event.rb
> +        def find_event(events, event_type)
I don't see any callers.

2020-12-02 02:15 UTC, justinlittman commented on app/services/cocina/from_fedora/descriptive/event.rb
> +        def find_event(events, event_type)
Nope. Removed.

2020-12-02 02:15 UTC, justinlittman commented on app/services/cocina/from_fedora/descriptive/event.rb
> +              # byebug
Yes. Removed.

2020-12-02 04:42 UTC, jcoyne approved these changes

2020-12-02 04:42 UTC, merged