Ignore names with missing nameParts in FromFedora mapping
sul-dlss/dor-services-app pull request #1724
Opened 2020-12-16 19:37 UTC by mjgiarlo

Fixes #1721

# Before

```
TBD
```

# After

```
TBD
```

2020-12-16 22:02 UTC, jcoyne requested changes

2020-12-16 22:02 UTC, jcoyne commented on app/services/cocina/from_fedora/descriptive/name_builder.rb
> +          name_parts = Array(build_name_parts(name_node))
If we removed the `.presence` from the end of `build_name_parts`, we wouldn't need to re-wrap with an array.

2020-12-16 22:02 UTC, jcoyne commented on app/services/cocina/from_fedora/descriptive/name_builder.rb
> +          Honeybadger.notify('[DATA ERROR] missing name/namePart element', { tags: 'data_error' }) if name_parts.reject(&:empty?).empty?
Could this be `... if name_parts.all?(&:empty?)` ?  this seems more readable to me.

2020-12-16 22:23 UTC, mjgiarlo commented on app/services/cocina/from_fedora/descriptive/name_builder.rb
> +          name_parts = Array(build_name_parts(name_node))
I think we would still need it because the recently added `next` short-circuit (when no name parts) causes the `#tap` to return `[]` which gets compacted to `nil`.

2020-12-16 22:24 UTC, mjgiarlo commented on app/services/cocina/from_fedora/descriptive/name_builder.rb
> +          Honeybadger.notify('[DATA ERROR] missing name/namePart element', { tags: 'data_error' }) if name_parts.reject(&:empty?).empty?
Yep, that's better. Done.

2020-12-16 22:34 UTC, jcoyne commented on app/services/cocina/from_fedora/descriptive/name_builder.rb
> +          name_parts = Array(build_name_parts(name_node))
I don't think compact works that way:
```
 [].compact
=> []
```

2020-12-16 22:43 UTC, mjgiarlo commented on app/services/cocina/from_fedora/descriptive/name_builder.rb
> +          name_parts = Array(build_name_parts(name_node))
@jcoyne True. I misdiagnosed when I removed `.presence` a bunch of tests started failing. I now changed the nil-check I added to an emptiness check, so pushing that momentarily.

2020-12-16 22:44 UTC, mjgiarlo commented
@jcoyne ready for another look

2020-12-17 05:05 UTC, jcoyne approved these changes

2020-12-17 05:05 UTC, merged