to_fedora mapping specs get shared_example
sul-dlss/dor-services-app pull request #1825
Opened 2021-01-13 19:05 UTC by ndushay

## Why was this change made?

To make it easier to read and maintain to_fedora mapping specs by getting rid of noise in them.  Note that the rest of the specs will be converted to use the shared_example as part of the cocina-descriptive-md alignment work.

## How was this change tested?

unit tests

## Which documentation and/or configurations were updated?

2021-01-13 19:12 UTC, mjgiarlo commented on spec/support/mapping_spec_helper.rb
> +        end
We can dump the new rubocop exclusion and lot of duplication here by doing using `case`/`when` more idiomatically like so:

```ruby
case described_class
when Cocina::ToFedora::Descriptive::Access
when Cocina::ToFedora::Descriptive::AdminMetadata
# ...
```

Would that work here or is there a reason you went with a bare `case`?

2021-01-13 19:12 UTC, jcoyne commented on spec/support/mapping_spec_helper.rb
> +        case
To me, this case statement obscures a lot of variability that would better be expressed in the individual tests themselves.  Instead of doing this can you make a method like:

```ruby
def build_mods
  "#{MODS_HEADER}#{yield}#{MODS_FOOTER}"
 end
 ```
 
 Then you can do:
 ```
 xml = build_mods do
  <<~XML
      <classification authority="ddc" edition="11">683</classification>
      <classification authority="ddc" edition="12">684</classification>
    XML
    end
  ```

2021-01-13 19:14 UTC, mjgiarlo commented on spec/support/mapping_spec_helper.rb
> +        end
Btw, really like the overall reduction in duplication that shared_specs brings!

2021-01-13 19:15 UTC, ndushay commented on spec/support/mapping_spec_helper.rb
> +        end
Because when i tried doing what you suggest, it didn't work.   '===' gave false, but '==' gives true.   Happy if there's a  solution that works!

2021-01-13 19:16 UTC, ndushay commented on spec/support/mapping_spec_helper.rb
> +        case
i don't think there WAS variability for this in the tests themselves.  Except I saw one that called out MODS 3.3 which I will of course leave alone.

2021-01-13 19:20 UTC, mjgiarlo commented on spec/support/mapping_spec_helper.rb
> +        end
@ndushay Ah, OK, because the class of a class is `Class` not the class. Gotcha! That makes sense.

2021-01-13 19:24 UTC, ndushay commented on spec/support/mapping_spec_helper.rb
> +        case
if you mean the params passed in to `described_class.write`, maybe I can add an argument to the shared_examples for that -- would that work for you?

2021-01-13 19:31 UTC, jcoyne commented on spec/support/mapping_spec_helper.rb
> +        case
The variability I'm complaining about is the "case" statement.  I think it's very hard to understand why that all needs to be in this shared example.  Putting that in the individual tests for each of those classes is the idiomatic way of instantiating the class under test.

2021-01-14 18:01 UTC, ndushay commented on spec/support/mapping_spec_helper.rb
> +        case
@jcoyne and I spoke and the new approach I have since pushed up works for him.

2021-01-14 18:03 UTC, jcoyne requested changes

2021-01-14 18:03 UTC, jcoyne commented on .rubocop.yml
> +    - 'spec/support/mapping_spec_helper.rb'
Is this still necessary? I don't see any case condition i that file.

2021-01-14 18:05 UTC, ndushay commented on .rubocop.yml
> +    - 'spec/support/mapping_spec_helper.rb'
whoops!  will remove.

2021-01-14 18:09 UTC, jcoyne approved these changes

2021-01-14 18:09 UTC, merged