Rearange to_fedora identifier spec for clarity an anlysis
sul-dlss/dor-services-app pull request #1829
Opened 2021-01-13 23:31 UTC by aaron-collier

## Why was this change made?

https://docs.google.com/spreadsheets/d/1yDJZPVMUOq0lD-t-3tlubVdjlq3YFLAeWcKwQzPOY88/edit#gid=0

This is the `to_fedora` side of the identifier analysis

## How was this change tested?

## Which documentation and/or configurations were updated?

2021-01-13 23:41 UTC, ndushay requested changes
dropped some comments about your comments.  Heh.

2021-01-13 23:41 UTC, ndushay commented on spec/services/cocina/to_fedora/descriptive/identifier_spec.rb
> +  # 0: Identifier is nil
unless  Arcadia's mapping has a 0 in it, I just leave out the comment for the ones missing from her examples.

2021-01-13 23:41 UTC, ndushay commented on spec/services/cocina/to_fedora/descriptive/identifier_spec.rb
> +  # FIXME:  https://github.com/sul-dlss-labs/cocina-descriptive-metadata/issues/320
so this is "hey, this example isn't on Arcadia's mappings, and it probably should be"?

I did 

``` 
# FIXME: this example should be added to cdm (?) - see https://github.com/sul-dlss-labs/cocina-descriptive-metadata/issues/298
```

to be as clear as possible.

2021-01-14 01:02 UTC, justinlittman approved these changes

2021-01-14 18:10 UTC, ndushay commented
also, PR #1825 is merged so pls convert to shared_examples approach for xml tests.

2021-01-23 00:22 UTC, ndushay commented
closing this as the approach has changed 5 times since this PR, and is settled in a different direction.

2021-01-23 00:22 UTC, closed without merging