new approach to mods <--> cocina mapping specs (leaner, maintainable)
sul-dlss/dor-services-app pull request #1892
Opened 2021-01-23 02:33 UTC by ndushay

Needs sign off by @arcadiafalcone and @justinlittman, and at least one other developer.

## Why was this change made?

To make it easier:
- for Arcadia to add/update cocina mappings and get them coded (by having them live in dor-services-app)
- for Arcadia to know exactly which of her mappings are and are not implemented
- to maintain our code against Arcadia's mappings by removing duplication - we use shared examples to execute directly off Arcadia's mappings
- no more tickets back and forth between sul-dlss-labs/cocina-descriptive-metadata and this github repo

## How was this change tested?

All the changes were to rspec code, except some yard style documentation added to a few cocina mapping methods.  Code coverage should not go down.

## Which documentation and/or configurations were updated?

2021-01-23 02:38 UTC, ndushay commented on spec/services/cocina/from_fedora/descriptive/notes_spec.rb
> -        <abstract>This is an abstract.</abstract>
removed specs correspond to new mappings in `spec/services/cocina/mapping/descriptive/mods/`

2021-01-23 02:38 UTC, ndushay commented on spec/services/cocina/from_fedora/descriptive/notes_spec.rb
> +  # abstract extra test
tagging @arcadiafalcone

2021-01-23 02:38 UTC, ndushay commented on spec/services/cocina/to_fedora/descriptive/subject_classification_spec.rb
tagging @justinlittman @arcadiafalcone this is the only spec remaining in this file:  when cocina has no subjects.  Do we want to keep a test like this, and if so, perhaps not in a file specific to subject classification?

2021-01-23 02:38 UTC, ndushay commented on spec/support/mods_mapping_spec_helper.rb
>  end
the previous shared example code was for an older approach to this problem and will be going away as we use this new approach.

2021-01-24 02:10 UTC, justinlittman approved these changes

2021-01-25 16:14 UTC, arcadiafalcone commented on spec/services/cocina/mapping/descriptive/mods/abstract_spec.rb
> +  describe 'display label' do
Should this be "abstract with display label" instead of just "display label," to fit the pattern of the other tests?

2021-01-25 16:26 UTC, arcadiafalcone commented on spec/services/cocina/to_fedora/descriptive/subject_classification_spec.rb
If you want to keep it, I think it makes sense to have a file with all of the nil tests together.

2021-01-25 16:29 UTC, arcadiafalcone commented on spec/support/mods_mapping_spec_helper.rb
> +def ng_mods_for(snippet)
Could we make this MODS 3.7 instead of 3.6? There is one originInfo mapping where it makes a difference, but otherwise I'd prefer to use the most recent version as the default.

2021-01-25 16:30 UTC, justinlittman commented on spec/services/cocina/mapping/descriptive/mods/abstract_spec.rb
> +  describe 'display label' do
For what it is worth, I have been copying the titles exactly from the original examples (including capitalization).

2021-01-25 16:32 UTC, arcadiafalcone commented on spec/services/cocina/mapping/descriptive/mods/subject_classification_spec.rb
> +  describe 'with authority' do
Ditto above, making the label "classification with authority" for readability, with the same applying to the other examples.

2021-01-25 17:04 UTC, ndushay commented on spec/support/mods_mapping_spec_helper.rb
> +def ng_mods_for(snippet)
Let's bump the MODS version to 3.7 as a separate PR as it involves touching code as well as specs.

2021-01-25 17:09 UTC, ndushay commented on spec/services/cocina/mapping/descriptive/mods/abstract_spec.rb
> +  describe 'display label' do
With or without the number?

2021-01-25 17:13 UTC, ndushay commented on spec/services/cocina/to_fedora/descriptive/subject_classification_spec.rb
removed.

2021-01-25 17:15 UTC, justinlittman commented on spec/services/cocina/mapping/descriptive/mods/abstract_spec.rb
> +  describe 'display label' do
Without.

2021-01-25 17:17 UTC, ndushay commented on spec/services/cocina/mapping/descriptive/mods/subject_classification_spec.rb
> +  describe 'with authority' do
used your descriptions, except added context where you didn't have it (e.g. when it was just "Display label")

2021-01-25 17:23 UTC, ndushay commented on spec/support/mods_mapping_spec_helper.rb
> +def ng_mods_for(snippet)
@justinlittman should mods_normalizer also be changed to 3.7?

2021-01-25 17:50 UTC, ndushay commented on spec/services/cocina/mapping/descriptive/mods/abstract_spec.rb
> +  describe 'display label' do
example descriptions redone.

2021-01-25 17:50 UTC, ndushay commented on spec/support/mods_mapping_spec_helper.rb
> +def ng_mods_for(snippet)
working on this in separate PR.

2021-01-25 17:58 UTC, jcoyne requested changes

2021-01-25 17:58 UTC, jcoyne commented on spec/services/cocina/from_fedora/descriptive/notes_spec.rb
> +  # abstract extra test
What does this mean?

2021-01-25 18:08 UTC, ndushay commented on spec/services/cocina/from_fedora/descriptive/notes_spec.rb
> +  # abstract extra test
It means we have a test that Arcadia's examples doesn't have, so we will keep it in our code but let Arcadia know.   We will likely have some of these as we go along, and wanted to separate conversion of our specs to the new way from addressing all of these.

2021-01-25 18:09 UTC, arcadiafalcone approved these changes

2021-01-25 18:09 UTC, jcoyne commented on spec/services/cocina/from_fedora/descriptive/notes_spec.rb
> +  # abstract extra test
Would you mind updating the comment to say just that.

2021-01-25 19:27 UTC, ndushay commented on spec/services/cocina/from_fedora/descriptive/notes_spec.rb
> +  # abstract extra test
done.

2021-01-25 19:28 UTC, jcoyne approved these changes

2021-01-25 19:29 UTC, merged