Mapping tests for subject for H2
sul-dlss/dor-services-app pull request #1916
Opened 2021-01-26 21:57 UTC by justinlittman

…to MODS to COCINA (for H2)

## Why was this change made?
* Add tests for H2 subjects.
* Add testing for cocina-first mapping.

## How was this change tested?
Unit

## Which documentation and/or configurations were updated?
NA

2021-01-26 22:35 UTC, ndushay approved these changes
LGTM;

@arcadiafalcone do you want these h2 specs:
- to keep h2 in the spec file name and description
- to be in the same directory as the other MODS specs?

2021-01-26 22:35 UTC, ndushay commented on spec/services/cocina/mapping/descriptive/mods/subject_h2_spec.rb
> +RSpec.describe 'MODS subject <--> cocina mappings for H2' do
should this read `Cocina <--> MODS mappings for H2 subjects' or even `Cocina <--> MODS mappings for FAST subjects`?

2021-01-26 22:35 UTC, ndushay requested changes
oops - meant to request changes so Arcadia can answer

2021-01-27 15:48 UTC, arcadiafalcone commented on spec/services/cocina/mapping/descriptive/mods/subject_h2_spec.rb
> +RSpec.describe 'MODS subject <--> cocina mappings for H2' do
They're really Cocina --> MODS mappings at this point - they're not roundtripped back to Cocina. `Cocina --> MODS mappings for FAST subjects` is probably the most accurate.

2021-01-27 15:50 UTC, arcadiafalcone commented on spec/services/cocina/mapping/descriptive/mods/subject_h2_spec.rb
> +RSpec.describe 'MODS subject <--> cocina mappings for H2' do
Let's keep H2 in the file names and descriptions -- these mappings are really dependent on the structure of the H2 metadata entry form. Having them in a different directory would be preferable.

2021-01-27 18:51 UTC, justinlittman commented on spec/services/cocina/mapping/descriptive/mods/subject_h2_spec.rb
> +RSpec.describe 'MODS subject <--> cocina mappings for H2' do
OK. Moved them to an `h2` directory and used the description that you provided.

2021-01-27 18:53 UTC, ndushay commented on spec/services/cocina/mapping/descriptive/mods/subject_h2_spec.rb
> +RSpec.describe 'MODS subject <--> cocina mappings for H2' do
ugh - should it be a subdirectory of MODS?  since it's still MODS?

2021-01-27 18:55 UTC, ndushay approved these changes
one last question for @arcadiafalcone about whether h2 should be a subdirectory for MODS and one for @justinlittman double checking these aren't already in our old style subject specs.

Approving with those caveats.

2021-01-27 18:57 UTC, arcadiafalcone commented on spec/services/cocina/mapping/descriptive/mods/subject_h2_spec.rb
> +RSpec.describe 'MODS subject <--> cocina mappings for H2' do
It's primarily an H2>Cocina mapping though - the MODS is secondary. I don't think it should be a subdirectory of MODS.

2021-01-27 19:26 UTC, justinlittman commented on spec/services/cocina/mapping/descriptive/mods/subject_h2_spec.rb
> +RSpec.describe 'MODS subject <--> cocina mappings for H2' do
We can always change later if `H2` is no longer appropriate.

2021-01-27 19:30 UTC, justinlittman commented
I think contributor and form are the only area with old style tests for H2.

2021-01-27 19:30 UTC, merged