mods name <--> cocina mapping specs refactored
sul-dlss/dor-services-app pull request #1930
Opened 2021-01-27 20:06 UTC by ndushay

## Why was this change made?

To reduce ongoing costs of mods/cocina mappings

## How was this change tested?

it was all test code changes; there should be no coverage decrease (and there's less overall test code!)

## Which documentation and/or configurations were updated?

2021-01-27 20:24 UTC, ndushay commented on spec/support/mods_mapping_spec_helper.rb
> +        end
calling this out for @justinlittman to review.  the change you made seemed to require me to put nil in the spec itself, but needed this fix here as well.   It's not elegant, but it works.  Perhaps you have a better solution.

2021-01-27 20:36 UTC, ndushay commented
I am not finding which code is no longer covered by tests ...

2021-01-27 20:43 UTC, mjgiarlo commented on spec/support/mods_mapping_spec_helper.rb
> +          expect(actual_cocina_props[key] == [{}]).to eq true
I'm curious if `expect(actual_cocina_props[key]).to eq [{}]` would work just as well here (and below).

2021-01-27 20:51 UTC, justinlittman requested changes

2021-01-27 20:51 UTC, justinlittman commented on spec/services/cocina/mapping/descriptive/mods/name_spec.rb
> +    let(:druid) { 'cp049zn0898' } # adapted from ...
This should just a comment `# adapted from druid:cp049zn0898`.

The `let(:druid)` is for when the druid is needed for the mapping.

2021-01-27 20:51 UTC, justinlittman commented on spec/services/cocina/mapping/descriptive/mods/name_spec.rb
> +    # Should this warn?
These seems crufty. Ticket or ask Arcadia?

2021-01-27 20:51 UTC, justinlittman commented on spec/support/mods_mapping_spec_helper.rb
> +        end
I don't understand what problem this is solving. Can you say more?

2021-01-27 20:54 UTC, jmartin-sul commented
> I am not finding which code is no longer covered by tests ...

according to the code climate link in the PR, it looks like the issue is in `contributor_writer.rb`, and comparing `main` against this branch using the code climate browser plugin, it looks like this is what lost coverage:
https://github.com/sul-dlss/dor-services-app/blob/mods-name-specs/app/services/cocina/to_fedora/descriptive/contributor_writer.rb#L136-L164

vs

https://github.com/sul-dlss/dor-services-app/blob/main/app/services/cocina/to_fedora/descriptive/contributor_writer.rb#L136-L164

(in this branch's version, it appears that much of the `write_note`, `write_identifier`, and `write_display_form` coverage was lost)

2021-01-27 21:05 UTC, ndushay commented on spec/support/mods_mapping_spec_helper.rb
> +        end
pull the branch and try running `rspec spec/services/cocina/mapping/descriptive/mods/name_spec.rb:537` - it will explain it better than I can.

Something about the deep_equal implementation cannot equate `nil` with `[{}]`, IIRC.

2021-01-28 18:09 UTC, ndushay commented on spec/services/cocina/mapping/descriptive/mods/name_spec.rb
> +    let(:druid) { 'cp049zn0898' } # adapted from ...
oooOOOOOooooo

2021-01-28 19:05 UTC, justinlittman approved these changes

2021-01-28 19:07 UTC, merged

2021-01-28 20:50 UTC, ndushay commented
John - thanks for the research. @justinlittman - I'm inclined to ignore the coverage difference - what do you think?