add access_h2_spec for cocina mappings
sul-dlss/dor-services-app pull request #1933
Opened 2021-01-27 21:06 UTC by ndushay

## Why was this change made?

adding Arcadia's mappings for h2 access specs.

## How was this change tested?

it adds two "xit" specs ...

## Which documentation and/or configurations were updated?

2021-01-27 21:20 UTC, justinlittman requested changes

2021-01-27 21:20 UTC, justinlittman commented on spec/services/cocina/mapping/descriptive/h2/access_h2_spec.rb
> +    xit 'FIXME: cocina -> MODS ok, but no way to get back'
I don't understand. Is the example incomplete? In which case I would omit `let(:mods)` and have xit be something like "incomplete mapping".

2021-01-27 21:20 UTC, justinlittman commented on spec/services/cocina/mapping/descriptive/h2/access_h2_spec.rb
> +    xit 'FIXME: get MODS mapping for email (is it part of name ?)'
I don't understand. Is this not implemented, in which case I would recommend "not implemented" as xit? Or is something else wrong?

2021-01-27 21:27 UTC, ndushay commented on spec/services/cocina/mapping/descriptive/h2/access_h2_spec.rb
> +    xit 'FIXME: cocina -> MODS ok, but no way to get back'
it's more that h2 provides the "in the stanford repository" bit, which is good, but we don't put that in the MODS, so this particular h2 mapping is NEVER going to roundtrip properly.

2021-01-27 21:28 UTC, ndushay commented on spec/services/cocina/mapping/descriptive/h2/access_h2_spec.rb
> +    xit 'FIXME: get MODS mapping for email (is it part of name ?)'
Arcadia's spec itself doesn't have the MODS, but this will clearly map to MODS somewhere, so this seemed like a useful message.

You are going for very brief and standardized xits, and I am going for more specific ones as I write these examples and learn stuff.  :-P

2021-01-27 21:50 UTC, justinlittman commented on spec/services/cocina/mapping/descriptive/h2/access_h2_spec.rb
> +    xit 'FIXME: get MODS mapping for email (is it part of name ?)'
I'm my mind, we have 3 types of incomplete tests:
1. Not implemented: the example is complete, but we haven't written the mapping code.
2. Broken: the example is complete and we wrote mapping code, but the mapping code doesn't work.
3. Incomplete mapping: the example is incomplete.

The challenge is that your xit comments make sense to you, but when I read them I can't make sense of them, or at least without digging into the test. Perhaps we want to some standardized prefixes and then additional details be optional, like `incomplete mapping: get MODS mapping for email (is it part of name ?)`.

2021-01-27 21:50 UTC, justinlittman commented on spec/services/cocina/mapping/descriptive/h2/access_h2_spec.rb
> +    xit 'FIXME: get MODS mapping for email (is it part of name ?)'
Happy to discuss more.

2021-01-28 18:12 UTC, ndushay commented on spec/services/cocina/mapping/descriptive/h2/access_h2_spec.rb
> +    xit 'FIXME: get MODS mapping for email (is it part of name ?)'
I propose to do a pass of all the cocina mapping xit comments as a separate PR when mine are merged.  I'll be sure to standardize on your prefixes.   Also, for h2 specs, I remembered we can have diff roundtrip_cocina but only after a bunch of PRs were already merged.

If you want me to address the xits and so on in this PR before merging, rather than bundling it in, I can do ...

2021-01-28 18:13 UTC, justinlittman approved these changes

2021-01-28 18:13 UTC, merged