H2 mappings - xit update
sul-dlss/dor-services-app pull request #1954
Opened 2021-01-28 19:57 UTC by ndushay

## Why was this change made?

Standardizing xit practices on mapping specs.  Also, I forgot about roundtrip_cocina so was able to add some specs to admin_metadata.

## How was this change tested?

it's all spec code

## Which documentation and/or configurations were updated?

2021-01-28 21:57 UTC, justinlittman requested changes

2021-01-28 21:57 UTC, justinlittman commented on spec/services/cocina/mapping/descriptive/h2/access_h2_spec.rb
> +    let(:mods) do
Why the empty `let(:mods)`? And why is it different than the empty mods let below?

2021-01-28 21:57 UTC, justinlittman commented on spec/services/cocina/mapping/descriptive/h2/admin_metadata_h2_spec.rb
> +      let(:druid) { 'jv545yc8727' }
This should be a comment, right? `# Adapted from druid:jv545yc8727`.

2021-01-28 22:53 UTC, ndushay commented on spec/services/cocina/mapping/descriptive/h2/access_h2_spec.rb
> +    let(:mods) do
I was trying to run these to see what happened.  I will remove both.

2021-01-28 22:53 UTC, ndushay commented on spec/services/cocina/mapping/descriptive/h2/admin_metadata_h2_spec.rb
> +      let(:druid) { 'jv545yc8727' }
will fix.  when is druid "needed" ?

2021-01-29 02:34 UTC, justinlittman approved these changes

2021-01-29 02:34 UTC, merged