Add external link mapping to table of contents spec
sul-dlss/dor-services-app pull request #1964
Opened 2021-01-29 17:50 UTC by arcadiafalcone

## Why was this change made?
Partially addresses #1936 

## How was this change tested?
n/a

## Which documentation and/or configurations were updated?
n/a

2021-02-01 12:29 UTC, justinlittman requested changes
Does this work or should it be an `xit`?

2021-02-01 12:29 UTC, justinlittman commented on spec/services/cocina/mapping/descriptive/mods/table_of_contents_spec.rb
> +
Missing an `end` here.

2021-02-01 17:13 UTC, arcadiafalcone commented on spec/services/cocina/mapping/descriptive/mods/table_of_contents_spec.rb
> +
Fixed.

2021-02-02 16:55 UTC, justinlittman approved these changes

2021-02-02 16:55 UTC, merged

2021-02-02 16:56 UTC, justinlittman commented
#2027 is for implementation.