implement typeOfResource mapping when attribute without value
sul-dlss/dor-services-app pull request #1980
Opened 2021-01-29 21:11 UTC by ndushay

## Why was this change made?

Fixes #1969 

## How was this change tested?

### This branch

rut roh

```
Status (n=50000):
  Success:   49071 (98.142%)
  Different: 602 (1.204%)
  To Cocina error:     16 (0.032%)
  To Fedora error:     0 (0.0%)
  Missing:     311 (0.622%)
```

### main branch

```
Status (n=50000):
  Success:   49078 (98.156%)
  Different: 595 (1.19%)
  To Cocina error:     16 (0.032%)
  To Fedora error:     0 (0.0%)
  Missing:     311 (0.622%)

```

## Which documentation and/or configurations were updated?

2021-01-29 22:03 UTC, mjgiarlo commented on app/services/cocina/to_fedora/descriptive/form.rb
> +          return write_attributes_only(is_manuscript, is_collection) if form.nil?
Was this line added to accommodate what's now on line 47 or are there other cases where `form` can be `nil`? If there are other cases, this seems right. If there aren't, line 47 could change to `write_attributes_only(is_manuscript, is_collection)` since we already known the form is `nil` there. Do not feel strongly about this at all.

2021-01-29 22:03 UTC, mjgiarlo approved these changes

2021-01-30 19:13 UTC, jcoyne requested changes

2021-01-30 19:13 UTC, jcoyne commented on app/services/cocina/from_fedora/descriptive/form.rb
> +            if type.text.present?
Why did you choose to use present? here? Is this to check for an empty string? Do we have a test for that case?

2021-02-01 17:58 UTC, ndushay commented on app/services/cocina/to_fedora/descriptive/form.rb
> +          return write_attributes_only(is_manuscript, is_collection) if form.nil?
See line 43, which is like line 47, but only one has form=nil.

2021-02-01 18:03 UTC, ndushay commented on app/services/cocina/from_fedora/descriptive/form.rb
> +            if type.text.present?
While developing, I wrote some extra tests for attribute `collection="yes"` and for <typeOfResource> without attributes or a value.  This code worked.   It's possible just `type.text` would also have worked.

I removed my extra tests since the mapping files are now really Arcadia's and I didn't want to clutter them up.

Does `.present?` offend because it might be unnecessary?  It seems like a small thing to quibble over.

2021-02-01 18:31 UTC, ndushay commented on app/services/cocina/from_fedora/descriptive/form.rb
> +            if type.text.present?
I also wonder if we do get an empty string from `<element></element>` - we've had to add `.present?` to a lot of mapping code over the last few months.

2021-02-01 18:41 UTC, jcoyne commented on app/services/cocina/from_fedora/descriptive/form.rb
> +            if type.text.present?
I'm concerned about this, because it's not clear to me as a reader of the code what cases you are actually looking for.  There are several cases handled by this method, but it's not clear that we need to handle all of these cases.  If we do, we should have tests for them.  That is, if I change the code to `if type.text` then one of the tests ought to break.   I feel like the code should be as simple as possible to handle the cases we need to.  And `type.text` is simpler than `type.text.present?`

2021-02-01 18:52 UTC, ndushay commented on app/services/cocina/from_fedora/descriptive/form.rb
> +            if type.text.present?
ah.  and I feel like our MODS is made in so many different ways, that it makes sense for our code to cope broadly with possible empty attributes and elements and am not sure if we want all of those tests in Arcadia's mapping specs or not, or if we want them all in to_fedora and from_fedora ... or not.   Since our practice has been inconsistent in terms of having specs for this in the past ... it seems weird that this is now a sticking point in my 2 PRs.

2021-02-01 21:08 UTC, ndushay commented on app/services/cocina/from_fedora/descriptive/form.rb
> +            if type.text.present?
added test.

2021-02-01 21:12 UTC, jcoyne approved these changes

2021-02-01 21:13 UTC, merged