Event approx date
sul-dlss/dor-services-app pull request #1984
Opened 2021-01-30 00:58 UTC by ndushay

## Why was this change made?

fixes event mapping for `encoding` and `qualifier` attributes -- Arcadia says 

> "the pattern is for properties to be at the highest [outermost] level to which they apply"

Also required fixing existing originInfo mapping specs to be consistent the this rule.

Fixes #1971 
Fixes #1972

## How was this change tested?

specs updated plus roundtrip validation:

### this branch

```
Status (n=50000):
  Success:   49078 (98.156%)
  Different: 595 (1.19%)
  To Cocina error:     16 (0.032%)
  To Fedora error:     0 (0.0%)
  Missing:     311 (0.622%)
```

### main branch

```
Status (n=50000):
  Success:   49078 (98.156%)
  Different: 595 (1.19%)
  To Cocina error:     16 (0.032%)
  To Fedora error:     0 (0.0%)
  Missing:     311 (0.622%)
```

## Which documentation and/or configurations were updated?

2021-01-30 19:06 UTC, jcoyne requested changes

2021-01-30 19:06 UTC, jcoyne commented on app/services/cocina/from_fedora/descriptive/event.rb
> +            new_node.remove_attribute('encoding') if common_attribs[:encoding].present?
Why do we need `present?` here? Can't we just check that the value is there or not?  Present is for checking things that could be arrays or scalars, but this could never be an array.

2021-01-30 19:08 UTC, jcoyne requested changes

2021-01-30 19:08 UTC, jcoyne commented on app/services/cocina/from_fedora/descriptive/event.rb
> +          encoding_is_common = node_set.all? { |node| node['encoding'] == first_encoding } if first_encoding.present?
Same with present here. These are never arrays, right?

2021-02-01 17:47 UTC, arcadiafalcone approved these changes

2021-02-01 18:04 UTC, ndushay commented on app/services/cocina/from_fedora/descriptive/event.rb
> +            new_node.remove_attribute('encoding') if common_attribs[:encoding].present?
an attribute can be present but empty.

2021-02-01 18:04 UTC, ndushay commented on app/services/cocina/from_fedora/descriptive/event.rb
> +          encoding_is_common = node_set.all? { |node| node['encoding'] == first_encoding } if first_encoding.present?
an attribute can be present but empty.  And sometimes is.

2021-02-01 18:37 UTC, jcoyne commented on app/services/cocina/from_fedora/descriptive/event.rb
> +          encoding_is_common = node_set.all? { |node| node['encoding'] == first_encoding } if first_encoding.present?
Do we have a test for this case?

2021-02-01 18:37 UTC, jcoyne commented on app/services/cocina/from_fedora/descriptive/event.rb
> +            new_node.remove_attribute('encoding') if common_attribs[:encoding].present?
Can you add a test for this?

2021-02-01 18:49 UTC, ndushay commented on app/services/cocina/from_fedora/descriptive/event.rb
> +            new_node.remove_attribute('encoding') if common_attribs[:encoding].present?
can you explain better what problem you are trying to have me solve here?   In implementing lots of mappings, we had to put "compact" and "present?" all over the place to deal with empty values.  I doubt we have tests for all of those spots.    Are you suggesting we should?  If so, maybe make a ticket for systematically doing that everywhere, and discuss w Arcadia if she wants those specs in the official "mapping" specs or in the "unit" test specs of to_fedora and from_fedora.

If you're not suggesting that we become consistent on this point ... then I wonder why we would want to add rspec tests for this in this particular case.

2021-02-01 20:33 UTC, jcoyne commented on app/services/cocina/from_fedora/descriptive/event.rb
> +            new_node.remove_attribute('encoding') if common_attribs[:encoding].present?
@ndushay in all of the places, if we remove the `present?` or `compact` the tests fail. I'm not sure any test fails if you remove this code here. Therefore, this is extra complexity.  Our code should be no more complex than we need it to be.  We should either make it simple or demonstrate through a test as to why we need this complexity.

2021-02-01 21:52 UTC, ndushay commented on app/services/cocina/from_fedora/descriptive/event.rb
> +            new_node.remove_attribute('encoding') if common_attribs[:encoding].present?
Ho ho - wrote tests;  they failed.  Fixed code and added the tests I wrote.

2021-02-01 21:56 UTC, ndushay commented on app/services/cocina/from_fedora/descriptive/event.rb
> +          encoding_is_common = node_set.all? { |node| node['encoding'] == first_encoding } if first_encoding.present?
yes, we do now.

2021-02-01 22:37 UTC, jcoyne approved these changes

2021-02-01 22:37 UTC, merged