Splits up mods normalizer.
sul-dlss/dor-services-app pull request #2060
Opened 2021-02-03 23:12 UTC by justinlittman

closes #2050

## Why was this change made?
Code maintainability.

## How was this change tested?
Unit, sdr-deploy

## Which documentation and/or configurations were updated?
NA

2021-02-03 23:19 UTC, justinlittman commented
Before:
```
Status (n=100000):
  Success:   98179 (98.179%)
  Different: 1272 (1.272%)
  To Cocina error:     18 (0.018%)
  To Fedora error:     0 (0.0%)
  Missing:     531 (0.531%)
```

After:
```
Status (n=100000):
  Success:   98179 (98.179%)
  Different: 1272 (1.272%)
  To Cocina error:     18 (0.018%)
  To Fedora error:     0 (0.0%)
  Missing:     531 (0.531%)
```

2021-02-03 23:20 UTC, justinlittman commented
This is a straight refactoring -- no significant changes.

2021-02-03 23:23 UTC, mjgiarlo commented on app/services/cocina/mods_normalizers/geo_extension_normalizer.rb
> +        GeoExtensionNormalizer.new(mods_ng_xml: mods_ng_xml, druid: druid).normalize
How would you feel about shortening this to `new(mods_ng_xml: mods_ng_xml, druid: druid).normalize`?

2021-02-03 23:25 UTC, mjgiarlo commented on app/services/cocina/mods_normalizers/geo_extension_normalizer.rb
> +        GeoExtensionNormalizer.new(mods_ng_xml: mods_ng_xml, druid: druid).normalize
This applies to all the new classes.

2021-02-03 23:29 UTC, mjgiarlo commented on spec/services/cocina/mods_normalizers/geo_extension_normalizer_spec.rb
> +  let(:normalized_ng_xml) { Cocina::ModsNormalizer.normalize(mods_ng_xml: mods_ng_xml, druid: 'druid:pf694bk4862') }
I was a bit surprised that each of the new tests appear to be testing via the top-level normalizer rather than the class named on the `RSpec.describe` line. I don't think that's problematic, but I thought I'd register my surprise to get your reaction. Do you see a time when we tweak the tests to test their classes in a more targeted way or not really?

2021-02-04 01:51 UTC, ndushay requested changes
Given that @arcadiafalcone has asked in a separate ticket for all elements without attribute values or content to be removed as part of normalization ... wouldn't that go in a generic mods_normalization class?

The above question and one inline to be considered.  Thanks.

2021-02-04 01:51 UTC, ndushay commented on spec/support/mods_mapping_spec_helper.rb
> +
These should live in a real class somewhere and be accessed from that class for app code and for spec code.

2021-02-04 02:19 UTC, justinlittman commented on spec/services/cocina/mods_normalizers/geo_extension_normalizer_spec.rb
> +  let(:normalized_ng_xml) { Cocina::ModsNormalizer.normalize(mods_ng_xml: mods_ng_xml, druid: 'druid:pf694bk4862') }
The different normalization steps can interact with each other, so in the big picture you want to test the overall workings of the normalizer.

2021-02-04 02:21 UTC, justinlittman commented on app/services/cocina/mods_normalizers/geo_extension_normalizer.rb
> +        GeoExtensionNormalizer.new(mods_ng_xml: mods_ng_xml, druid: druid).normalize
I'd feel really good.

2021-02-04 02:26 UTC, justinlittman commented on spec/support/mods_mapping_spec_helper.rb
> +
It's not quite the same for the app code: https://github.com/sul-dlss/dor-services-app/blob/main/app/services/cocina/to_fedora/descriptive.rb#L44-L53

2021-02-04 02:29 UTC, justinlittman commented
I'm not sure I understand your question/suggestion about removing empty elements @ndushay .

2021-02-04 05:30 UTC, jcoyne approved these changes
Just normalize the MODS they said. It'll be easy, they said.

2021-02-04 16:19 UTC, mjgiarlo commented on app/services/cocina/mods_normalizers/geo_extension_normalizer.rb
> +        GeoExtensionNormalizer.new(mods_ng_xml: mods_ng_xml, druid: druid).normalize
:laughing: OK.

2021-02-04 16:21 UTC, mjgiarlo commented on spec/services/cocina/mods_normalizers/geo_extension_normalizer_spec.rb
> +  let(:normalized_ng_xml) { Cocina::ModsNormalizer.normalize(mods_ng_xml: mods_ng_xml, druid: 'druid:pf694bk4862') }
Not a problem.

2021-02-04 17:12 UTC, ndushay commented on spec/support/mods_mapping_spec_helper.rb
> +
oh right - I remember this.  as a string for specs only, this is a good location.

2021-02-04 17:20 UTC, ndushay commented
@justinlittman See issue #2034

2021-02-04 17:28 UTC, mjgiarlo commented
@ndushay Do you think this PR will make #2034 harder to implement? If not, :shipit: :question:

2021-02-04 17:34 UTC, ndushay approved these changes

2021-02-04 17:34 UTC, merged