migrate from_fedora contrib spec to mapping name spec, with additional normalizations
sul-dlss/dor-services-app pull request #2124
Opened 2021-02-09 19:04 UTC by ndushay

## Why was this change made?

We want to migrate the from_fedora and to_fedora mapping specs to a land where all the mapping specs are above average

## How was this change tested?

mods normalization changed - we got one more success in 10,000 records!   w00t!

### this branch

```
Status (n=10000):
  Success:   9818 (98.18%)
  Different: 114 (1.14%)
  To Cocina error:     0 (0.0%)
  To Fedora error:     0 (0.0%)
  Missing:     68 (0.68%)
```

### main branch

```
Status (n=10000):
  Success:   9817 (98.17%)
  Different: 115 (1.15%)
  To Cocina error:     0 (0.0%)
  To Fedora error:     0 (0.0%)
  Missing:     68 (0.68%)
```

## Which documentation and/or configurations were updated?

2021-02-09 23:59 UTC, justinlittman requested changes
Mostly suggestions.

2021-02-09 23:59 UTC, justinlittman commented on app/services/cocina/mods_normalizers/name_normalizer.rb
> +            name_node_w_type.remove_attribute('type')
Not a big deal, but elsewhere we've been using `.delete()`.

2021-02-09 23:59 UTC, justinlittman commented on app/services/cocina/mods_normalizers/name_normalizer.rb
> +require_relative '../from_fedora/descriptive/contributor'
I'm surprised that this is required.

2021-02-09 23:59 UTC, justinlittman commented on app/services/cocina/mods_normalizers/name_normalizer.rb
> +        ng_xml.root.xpath('//mods:name[(@type)]', mods: ModsNormalizer::MODS_NS).each do |name_node_w_type|
I don't think the () are needed in "(@type)".

2021-02-09 23:59 UTC, justinlittman commented on spec/services/cocina/mapping/descriptive/mods/name_spec.rb
> +    context 'when unrecognized' do
When what is unrecognized?

2021-02-09 23:59 UTC, justinlittman commented on spec/services/cocina/mapping/descriptive/mods/name_spec.rb
> +    context 'with a role that has no URI and has xlink uris from MODS 3.3' do
Why not use the shared example? Might require some changes to allow setting the mods header.

2021-02-10 13:14 UTC, ndushay commented on app/services/cocina/mods_normalizers/name_normalizer.rb
> +        ng_xml.root.xpath('//mods:name[(@type)]', mods: ModsNormalizer::MODS_NS).each do |name_node_w_type|
right you are.

2021-02-10 13:16 UTC, ndushay commented on spec/services/cocina/mapping/descriptive/mods/name_spec.rb
> +    context 'with a role that has no URI and has xlink uris from MODS 3.3' do
i felt the path of least resistance was to just port the MODS 3.3 example as it was.  If we want to make it possible to use different MODS versions, we should maybe write a ticket for that;  I don't think we have more than a handful of these tests.

2021-02-10 13:22 UTC, ndushay commented on app/services/cocina/mods_normalizers/name_normalizer.rb
> +require_relative '../from_fedora/descriptive/contributor'
well, I'll be.  it isn't required now.  It was when I was developing the code;  must've had something weird going on for a spell.

2021-02-10 13:22 UTC, ndushay commented on app/services/cocina/mods_normalizers/name_normalizer.rb
> +            name_node_w_type.remove_attribute('type')
ja - docs imply they are aliases for one another.  Leaving this unless it really bugs you.

2021-02-10 13:22 UTC, ndushay commented on spec/services/cocina/mapping/descriptive/mods/name_spec.rb
> +    context 'when unrecognized' do
amended.

2021-02-10 13:22 UTC, ndushay commented on spec/services/cocina/mapping/descriptive/mods/name_spec.rb
> +    context 'with a role that has no URI and has xlink uris from MODS 3.3' do
Also wasn't sure if we had to have a specific xlink namespace declaration on the outer MODS element.

2021-02-10 16:14 UTC, ndushay commented
nice - elegant.  It just wasn't clicking for me.

2021-02-10 17:24 UTC, justinlittman approved these changes

2021-02-10 17:24 UTC, merged