Support partial object update.
sul-dlss/dor-services-app pull request #2427
Opened 2021-03-05 22:16 UTC by justinlittman

closes #2410

## Why was this change made?
Reduce the risk of unrelated mapping errors when performing an object update.

## How was this change tested?
Not yet.

## Which documentation and/or configurations were updated?
NA

2021-03-05 22:35 UTC, mjgiarlo commented on app/services/cocina/to_fedora/access.rb
> +        item.rightsMetadata.content = item.rightsMetadata.ng_xml.to_s
This change may conflict with #2402 but it shouldn't be difficult to work it back in.

2021-03-05 22:51 UTC, justinlittman commented on app/services/cocina/to_fedora/access.rb
> +        item.rightsMetadata.content = item.rightsMetadata.ng_xml.to_s
Yeah, looking at #2402, I think there will be several but no problem.

2021-03-11 13:57 UTC, jcoyne commented
> Reduce the risk of unrelated mapping errors when performing an object update.

how?

2021-03-11 14:36 UTC, jcoyne commented on spec/services/cocina/object_updater_spec.rb
> +          update
is there some expectation here?

2021-03-11 14:36 UTC, jcoyne commented on spec/services/cocina/object_updater_spec.rb
> +          update
Is there an expectation here?

2021-03-11 14:37 UTC, jcoyne commented on spec/services/cocina/object_updater_spec.rb
> +          update
Is there an expectation here?

2021-03-11 14:42 UTC, jcoyne commented on app/services/cocina/object_updater.rb
> +        item.contentMetadata.content = Cocina::ToFedora::ContentMetadataGenerator.generate(druid: item.pid, object: cocina_object)
what about `hasMemberOrders`?

2021-03-11 14:47 UTC, jcoyne commented on app/services/cocina/to_fedora/identity.rb
> +      def self.apply(item, label:, object_type:, agreement_id: nil)
I'm curious as to why youl've extracted `label` since this already has a dependency on the object where the label comes from.

2021-03-11 14:50 UTC, jcoyne commented on app/services/cocina/object_updater.rb
> +    def update?(key)
can we call this `has_changed?(key)`

2021-03-11 14:51 UTC, jcoyne commented on app/services/cocina/object_updater.rb
> +      cocina_object.public_send(key) != orig_cocina_object.public_send(key)
Is this basically doing the same as we're doing at the rubydora level? https://github.com/samvera/rubydora/blob/2cfedc707daa7203bce8c34a1a86ed72b6507e06/lib/rubydora/datastream.rb#L180

2021-03-11 14:54 UTC, jcoyne commented on app/services/cocina/object_updater.rb
> +      cocina_object.public_send(key) != orig_cocina_object.public_send(key)
And https://github.com/samvera/rubydora/blob/2cfedc707daa7203bce8c34a1a86ed72b6507e06/lib/rubydora/datastream.rb#L22 for the label (i.e. `dsLabel`)

2021-03-11 15:07 UTC, justinlittman commented on app/services/cocina/object_updater.rb
> +    def update?(key)
Yup.

2021-03-11 15:08 UTC, justinlittman commented on app/services/cocina/object_updater.rb
> +        item.contentMetadata.content = Cocina::ToFedora::ContentMetadataGenerator.generate(druid: item.pid, object: cocina_object)
No idea. I'm not changing this code.

2021-03-11 15:12 UTC, justinlittman commented on app/services/cocina/to_fedora/identity.rb
> +      def self.apply(item, label:, object_type:, agreement_id: nil)
It avoids passing the cocina object. Passing the cocina object might allow a future developer to accidentally bypass the has_changed? checking.

2021-03-11 15:13 UTC, justinlittman commented on app/services/cocina/object_updater.rb
> +      cocina_object.public_send(key) != orig_cocina_object.public_send(key)
Kinda looks like it.

2021-03-11 15:17 UTC, justinlittman commented on spec/services/cocina/object_updater_spec.rb
> +          update
It's implicit. If an attempt was made to update descriptive, then an error would have been thrown, something like:

```
 Failure/Error: item.descMetadata.content = Cocina::ToFedora::Descriptive.transform(obj.description, item.pid).to_xml
       #<Double (anonymous)> received unexpected message :content= with ("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<mods xmlns=\"http://www.loc.gov/mods/v3\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" version=\"3.7\" xsi:schemaLocation=\"http://www.loc.gov/mods/v3 http://www.loc.gov/standards/mods/v3/mods-3-7.xsd\">\n  <titleInfo>\n    <title>new title</title>\n  </titleInfo>\n</mods>\n")
```

2021-03-11 16:00 UTC, jcoyne commented on app/services/cocina/object_updater.rb
> +        item.contentMetadata.content = Cocina::ToFedora::ContentMetadataGenerator.generate(druid: item.pid, object: cocina_object)
what if the user provides `cocina_object.structural.hasMemberOrders` and not cocina_object.structural.contains`? Then their change would never be saved.

2021-03-11 16:07 UTC, jcoyne requested changes

2021-03-11 16:07 UTC, jcoyne commented on app/services/cocina/object_updater.rb
> +      if has_changed?(:label) || has_changed?(:structural)
Does this handle if the agreement_id is changed?

2021-03-11 17:05 UTC, justinlittman commented on app/services/cocina/object_updater.rb
> +      if has_changed?(:label) || has_changed?(:structural)
I believe so. Agreement is `obj.structural.hasAgreement`, so it would pass this if statement.

2021-03-11 17:54 UTC, justinlittman commented on app/services/cocina/object_updater.rb
> +        item.contentMetadata.content = Cocina::ToFedora::ContentMetadataGenerator.generate(druid: item.pid, object: cocina_object)
I'm not following.

2021-03-11 18:16 UTC, jcoyne commented on spec/services/cocina/object_updater_spec.rb
> +          update
It might be more clear to say `expect(foo).not_to have_received(:bar)`

2021-03-11 18:17 UTC, jcoyne commented on app/services/cocina/object_updater.rb
> +        item.contentMetadata.content = Cocina::ToFedora::ContentMetadataGenerator.generate(druid: item.pid, object: cocina_object)
It is possilbe for a cocina object to have nothing in the `contains` property, but to have `hasMemberOrders`.  If you are checking only for the presence of `contains`, then my changes to `hasMemberOrders` will not be preserved.

2021-03-11 18:20 UTC, jcoyne commented
I'm sorry to be really critical of this PR, but this adds a whole bunch of complexity and I'm not exactly sure what problem it solves.  I feel like these conditionals may end up introducing several hard to diagnose bugs.  I'd like some other team members to look at this very carefully and see what they think.

2021-03-11 19:57 UTC, justinlittman commented on app/services/cocina/object_updater.rb
> +        item.contentMetadata.content = Cocina::ToFedora::ContentMetadataGenerator.generate(druid: item.pid, object: cocina_object)
The comment in the line above says ` # We don't want to overwrite contentMetadata unless they provided structural.contains`, which would suggest that this behavior is deliberate. Maybe?

However, this PR isn't changing this code so if you think it is incorrect, I'd suggest another ticket.

2021-03-11 21:05 UTC, justinlittman commented on spec/services/cocina/object_updater_spec.rb
> +          update
Added `not_to`s

2021-03-11 21:16 UTC, justinlittman commented
I agree that the complexity is undesirable. However, until our mappings are rock solid, it reduces the risk of changes to one part of an item causing changes in an unrelated part of the item. For example, if a change is made to the access only the rightsMetadata datastream should change, the descMetadata datastream should not change. At worst, such changes might include errors; at best, they would be disconcerting to a user.

2021-03-12 02:12 UTC, jcoyne commented
I'm not sure this PR does that though. The cocina schemas don't map 1-1 with datastreams.   Many schemas are an amalgamation of several datastreams. For example changing the "type" property affects the "contentMetadata" datastream.  Changing the collection something belongs to is in the structural metadata, but it's written into the RELS-EXT datastream. The adminPolicy is in the administrative schema, but that also is in the RELS-EXT datastream.

2021-03-12 12:21 UTC, justinlittman commented
It doesn't matter if it is a 1-1 mapping. All that it matters is that a cocina change does not result in an _unrelated_ fedora change.

But let's step back. The motivation for this line of work was to enable H2 to use the updates endpoint, including for description changes. The risk that was identified was that for non-H2 uses of the updates endpoint, non-description updates would result in changes in the descMetadata datastream.

The changes might be of two sorts:
1. Roundtripping differences: Because there is not a 1-1 mapping of MODS to Cocina, if MODS is converted to Cocina, even if the Cocina is not changed, and then converted back to MODS, the MODS will have changed. While the MODS should be logically the same, it would be disconcerting for users to have the MODS unexpectedly changed.
2. Roundtripping errors: Because we continue to identify bugs in our mapping, forcing an unnecessary roundtripping and saving the resulting MODS will codify those errors. As we discover the errors, we will probably need to remediate, all for changes that weren't necessary.

While this was primarily motivated by and is clearest for descriptive metadata, it seems like it would apply in other areas, e.g., access rights, where we continue to discover wrinkles in our mappings / logic.

The goal here is not a perfect solution, but just to reduce the risk of unintended changes from the cocina update endpoint.

And to be clear, there are multiple ways of accomplishing this; I'm not wedded to this approach.

2021-03-12 13:00 UTC, jcoyne commented
I'm all for the descMetadata part of this. I understand how it's helpful there. I'd like an example case for an error in accessRights for instance.

2021-03-12 13:46 UTC, justinlittman commented
See https://github.com/sul-dlss/argo/issues/2382

2021-03-12 14:02 UTC, jcoyne commented
@justinlittman that is exactly what i'm thinking of.  While this could prevent the source_id from messing up the rights, it still will mess up the rights when the structural metadata gets changed.  And that sort of complexity makes it really hard to know we have a bug that only occurs in field Y when you change field X since it doesn't occur when you change field Z.  I think it is easier to find and fix a bug that occurs consistently whenever a change is made.

2021-03-12 14:22 UTC, justinlittman commented
I'm going to disagree -- it is more difficult to track down bugs that occur in totally unrelated places. For example, making the connection between a change in descriptive metadata breaking something in rights.

I'd suggest that we bring @andrewjbtw into the discussion, because it comes down what strategy and priority (if any) he wants to pursue for reducing risk of unintended changes.

2021-03-12 14:59 UTC, jcoyne commented
Sure absolutely. Discussion during standup?

2021-03-12 23:02 UTC, jcoyne approved these changes

2021-03-13 00:30 UTC, merged