add metadata/mods endpoint to retrieve source mods
sul-dlss/dor-services-app pull request #2487
Opened 2021-03-11 18:49 UTC by ndushay

## Why was this change made?

Fixes #1885

Adds an endpoint to retrieve source MODS for a DOR object.

## How was this change tested?

test suite

## Which documentation and/or configurations were updated?

2021-03-11 19:49 UTC, jcoyne requested changes

2021-03-11 19:49 UTC, jcoyne commented on app/services/publish/mods_service.rb
> +      @doc ||= dor_object.descMetadata.ng_xml.dup(NOKOGIRI_DEEP_COPY)
can this just be `dor_object.descMetadata.content`?

2021-03-11 19:49 UTC, jcoyne commented on app/services/publish/mods_service.rb
> +module Publish
This namespace seems confusing to me.  This might be misleading as this is not related to the `publish` endpoint.

2021-03-11 20:01 UTC, ndushay commented on app/services/publish/mods_service.rb
> +module Publish
happy to move it -- what do you suggest?

2021-03-11 20:02 UTC, ndushay commented on app/services/publish/mods_service.rb
> +      @doc ||= dor_object.descMetadata.ng_xml.dup(NOKOGIRI_DEEP_COPY)
ah - good point - in this context, yes.

2021-03-12 01:07 UTC, jcoyne commented on app/services/publish/mods_service.rb
> +module Publish
Do we need this service at all? Can we just return `item.descMetadata.content`?

2021-03-12 01:33 UTC, ndushay commented on app/services/publish/mods_service.rb
> +module Publish
another excellent point.  Done.

2021-03-12 02:13 UTC, jcoyne approved these changes

2021-03-12 02:13 UTC, merged