Check round trip before doing cocina update or create
sul-dlss/dor-services-app pull request #2494
Opened 2021-03-11 21:35 UTC by justinlittman

## Why was this change made?
To make sure that only changes that can be roundtripped are accepted for create or update. This ensures the integrity of data that is submitted via cocina update or create endpoints.

## How was this change tested?
Unit

## Which documentation and/or configurations were updated?
NA

2021-03-16 21:05 UTC, jcoyne requested changes

2021-03-16 21:05 UTC, jcoyne commented on app/services/cocina/object_creator.rb
> +        raise ValidationError.new(validator.error, status: :internal_server_error) unless validator.valid?
I'm not sure that 500 is the right code here. Would you consider 409?

2021-03-16 21:05 UTC, jcoyne commented on app/controllers/objects_controller.rb
> +    Honeybadger.notify(e) if e.status == :internal_server_error
Can this be a subclass of `Cocina::ValidationError` so we don't have to test on properties?

2021-03-16 21:05 UTC, jcoyne commented on app/services/cocina/object_updater.rb
> +      if has_changed?(:description) && update_descriptive? && Settings.enabled_features.validate_descriptive_roundtrip.update
why not do a `return unless ...` here?

2021-03-16 21:05 UTC, jcoyne commented on app/validators/cocina/description_roundtrip_validator.rb
> +      # Requests do not have druids.
👍

2021-03-17 13:52 UTC, justinlittman commented on app/services/cocina/object_creator.rb
> +        raise ValidationError.new(validator.error, status: :internal_server_error) unless validator.valid?
Done.

2021-03-17 13:52 UTC, justinlittman commented on app/controllers/objects_controller.rb
> +    Honeybadger.notify(e) if e.status == :internal_server_error
Done.

2021-03-17 13:57 UTC, justinlittman commented on app/services/cocina/object_updater.rb
> +      if has_changed?(:description) && update_descriptive? && Settings.enabled_features.validate_descriptive_roundtrip.update
While I generally support guard statements, I find this sort of a use of a guard statement confusing and requires additional effort to understand the code. In particular, I think guard statements should be used to filter the unhappy/atypical path, leaving the normal code path as the happy/typical path. In this case, if filters the happy/typical path and leaves the normal code path the unhappy/atypical path.

2021-03-17 13:57 UTC, justinlittman commented on app/services/cocina/object_updater.rb
> +      if has_changed?(:description) && update_descriptive? && Settings.enabled_features.validate_descriptive_roundtrip.update
But this is a pet peeve of mine.

2021-03-17 16:18 UTC, jcoyne approved these changes

2021-03-17 16:18 UTC, merged