Store the resource type in cocina
sul-dlss/dor-services-app pull request #2497
Opened 2021-03-11 23:22 UTC by jcoyne

## Why was this change made?

## How was this change tested?

## Which documentation and/or configurations were updated?

2021-03-12 22:36 UTC, aaron-collier commented
Should HOLD be removed from the title? 

Coverage! ugh!

2021-03-12 22:47 UTC, jcoyne commented
@aaron-collier no, this is a HOLD until monday when we update everything with a new api.  Still need approval though. The coverage drop is because we got to delete a bunch of code.

2021-03-15 11:36 UTC, justinlittman requested changes

2021-03-15 11:36 UTC, justinlittman commented on Gemfile
> +gem 'cocina-models', github: 'sul-dlss/cocina-models', branch: 'main' # '~> 0.54.0'
Cruft

2021-03-15 14:33 UTC, justinlittman approved these changes

2021-03-15 16:16 UTC, merged