Implement top level part mapping.
sul-dlss/dor-services-app pull request #2552
Opened 2021-03-19 12:46 UTC by justinlittman

refs #2499

## Why was this change made?
Infinite MODS.

## How was this change tested?
Unit, sdr-deploy

## Which documentation and/or configurations were updated?
NA

2021-03-19 12:57 UTC, justinlittman commented
Before:
```
Status (n=100000; not using Missing for success/different/error stats):
  Success:   99499 (99.499%)
  Different: 49 (0.049%)
  To Cocina error:     452 (0.452%)
  To Fedora error:     0 (0.0%)
  MODS normalizer error:     0 (0.0%)
  Missing (no descMetadata):     0 (0.0%)
```

After:
```
Status (n=100000; not using Missing for success/different/error stats):
  Success:   99500 (99.5%)
  Different: 48 (0.048%)
  To Cocina error:     452 (0.452%)
  To Fedora error:     0 (0.0%)
  MODS normalizer error:     0 (0.0%)
  Missing (no descMetadata):     0 (0.0%)
```

2021-03-22 15:20 UTC, jcoyne requested changes

2021-03-22 15:20 UTC, jcoyne commented on .rubocop.yml
> +  Enabled: false
Is there a reason we are turning this cop off and not adding a TODO?

2021-03-22 20:02 UTC, justinlittman commented on .rubocop.yml
> +  Enabled: false
The changes required make the code less readable and that sort of performance optimization isn't a consideration.

2021-03-22 20:51 UTC, jcoyne commented on .rubocop.yml
> +  Enabled: false
That sounds like a local consideration for the method you were working on rather than something we want to change globally.  Can you wrap your method with an exception?

2021-03-22 21:36 UTC, justinlittman commented on .rubocop.yml
> +  Enabled: false
Adding:
```
Performance/CollectionLiteralInLoop: # (new in 1.8)
  Enabled: true
  Exclude:
    - 'app/services/cocina/to_fedora/descriptive/part_writer.rb'
```

resulted in:
```
app/models/dor/update_marc_record_service.rb:164:9: C: Performance/CollectionLiteralInLoop: Avoid immutable Array literals in loops. It is better to extract it into a local variable or a constant.
        %w(partName partNumber).include?(child.name)
        ^^^^^^^^^^^^^^^^^^^^^^^
app/models/symphony_reader.rb:34:42: C: Performance/CollectionLiteralInLoop: Avoid immutable Array literals in loops. It is better to extract it into a local variable or a constant.
      record << marc_field(field) unless %w[001 003].include? field['tag'] # explicitly remove all 001 and 003 fields from the record
                                         ^^^^^^^^^^^
app/services/cocina/from_fedora/descriptive/access.rb:148:18: C: Performance/CollectionLiteralInLoop: Avoid immutable Array literals in loops. It is better to extract it into a local variable or a constant.
              if %w[marcorg oclcorg].include?(node[:authority])
                 ^^^^^^^^^^^^^^^^^^^
app/services/cocina/from_fedora/descriptive/form.rb:96:47: C: Performance/CollectionLiteralInLoop: Avoid immutable Hash literals in loops. It is better to extract it into a local variable or a constant.
          other_genre.each { |genre| forms << { type: 'genre' }.merge(build_genre(genre)) }
                                              ^^^^^^^^^^^^^^^^^
app/services/cocina/from_fedora/descriptive/title_builder.rb:97:19: C: Performance/CollectionLiteralInLoop: Avoid immutable Array literals in loops. It is better to extract it into a local variable or a constant.
            add = ['-', "'", ' '].include?(last_character) ? 0 : 1
                  ^^^^^^^^^^^^^^^
app/services/cocina/to_fedora/descriptive/access.rb:65:83: C: Performance/CollectionLiteralInLoop: Avoid immutable Hash literals in loops. It is better to extract it into a local variable or a constant.
                xml.physicalLocation access_contact.value || access_contact.code, { type: 'repository' }.merge(descriptive_attrs(access_contact))
```

which had nothing to do with my changes (or had performance considerations). And so I turned it off.

2021-03-22 21:41 UTC, jcoyne commented on .rubocop.yml
> +  Enabled: false
It's because the settings in `.rubocop.yml` are overwriting what you already have in https://github.com/sul-dlss/dor-services-app/blob/8461592524975be180ccd0d688033715c4fa2090/.rubocop_todo.yml#L94

2021-03-22 21:53 UTC, justinlittman commented on .rubocop.yml
> +  Enabled: false
Ah ... since we're ignoring it in all cases, then we should just turn it off in `.rubocop.yml`. It's confusing to split our ignores across the two rubo files, especially when we never intend to fix the TODOs.

However, at the end of the day, I don't care that much.

2021-03-23 01:40 UTC, jcoyne commented on .rubocop.yml
> +  Enabled: false
I don't think we are ignoring it in all cases.  I've hit it before and said "Ah-ha! I should fix this."  We are ignoring it in 7 specific places and five of them are in the descriptive metadata mapping.

2021-03-23 12:01 UTC, justinlittman commented on .rubocop.yml
> +  Enabled: false
OK, then I moved them from `.rubocop_todo.yml` to `.rubocop.yml` since they're not TODOs.

2021-03-23 13:45 UTC, jcoyne commented on .rubocop.yml
> +  Enabled: false
I rather think the ones in app/models were TODOs, as they were detected and never fixed, but I don't want to spend more time on this as it's really not worth it.

2021-03-23 13:45 UTC, jcoyne approved these changes

2021-03-23 14:52 UTC, justinlittman commented on .rubocop.yml
> +  Enabled: false
Agree. I conceptually understand the reason for TODOs, but I think in practice they do more harm then good.

2021-03-23 14:53 UTC, justinlittman commented on .rubocop.yml
> +  Enabled: false
Hah, and to add insult to injury, now there is a conflict on rubocop.yml.

2021-03-23 15:16 UTC, merged