allow objects that are currently opened to be accessioned properly
sul-dlss/dor-services-app pull request #2634
Opened 2021-03-31 23:09 UTC by peetucket

## Why was this change made?

~~HOLD:~~ Currently causing an integration tests to fail in QA (UPDATE: These tests all fail even with main branch of DSA deployed to QA, so likely unrelated to the work in this PR)

```
SDR_ENV=qa rspec ./spec/features/create_apo_spec.rb:19 # Use Argo to create an APO and verify new objects inherit it's rights is expected to have text "The following defaults will apply to all newly registered objects."
```
~~The pre-assembly spec is causing this exception with the legacy_metadata service: https://app.honeybadger.io/projects/50568/faults/78762991   .... assume because it is closing a version now via the new codepath?  But not sure why this is a problem.~~

-------
Came out of discussions on some work being done by John here: https://github.com/sul-dlss/sdr-api/pull/285 

The method we call to start accessioning (currently in pre-assembly and goobi, but soon to be sdr-api as well) handles the following two scenarios:

* A newly registered object that has not been accessioned
* An object that has been accessioned and is not yet opened

This change handles a potential third scenario:

* An object that has been accessioned and is in an open state

If not handled as in this PR, I believe objects in the last state will currently result in a version mismatch error, as we will start the accessionWF without closing them, which will end up trying to send an object to Preservation core with the same version as the last one sent.

NEWLY ADDED:

* if an object is currently being accessioned, return a 406 and do nothing

## How was this change tested?

Added a new test

## Which documentation and/or configurations were updated?

2021-03-31 23:19 UTC, ndushay commented
seems like functionality / concepts Andrew should weigh in on ...

2021-03-31 23:20 UTC, ndushay approved these changes
Aside from my concern that Andrew think through whether there are undesired side effects, the code looks fine.

2021-03-31 23:37 UTC, jmartin-sul approved these changes
LGTM also, agree andrew's sign-off would be good to have

2021-04-01 00:44 UTC, jmartin-sul reviewed
ok, actually, a question about whether there's another opportunity for preventing version mismatch errors from pres cat, which is possibly just my lack of understanding of SDR object states and versioning.

2021-04-01 00:44 UTC, jmartin-sul commented on app/controllers/objects_controller.rb
>      end
actually, question:  should there be a check that throws an error if it's not open, not openable, and not registered/v1?  that is, should it be possible to kick off accessioning on something that's not the initial v1 registration, and which is also already closed by some other process?  or am i misunderstanding the object state transitions?  how would the accessioned-to-an-existing-version content get preserved?

2021-04-01 00:47 UTC, jmartin-sul commented on app/controllers/objects_controller.rb
>      end
i wouldn't hold up this PR over my question, since i think the check that was added makes sense, and stays the same regardless of the answer to my question (which i think results in no change if i'm off-base, and a check that throws an error if i did notice an opportunity for a preservation version mismatch problem).

2021-04-01 17:34 UTC, peetucket commented on app/controllers/objects_controller.rb
>      end
So let's think through the possibly object states when we reach this method:

- a newly registered object, never accessioned: `VersionService.can_open?` is false and `VersionService.open_for_versioning?` is also false so we just kick off accessioning.  This seems fine and should not generate any errors
- an object that is currently closed and ready to be opened: ``VersionService.can_open?` is true, so we will open/close the version and kick off accessioning
- an object that is currently opened (and therefore by definition has already been accessioned once): `VersionService.can_open?` is false and ` VersionService.open_for_versioning?` is true, so we close and then start accessioning (this is the work in this PR)

I don't know if its possible for something to be in a state of `not open, not openable, and not registered/v1` ... I think it may be possible for something to be openable but for the version number to not be correct for whatever reason.

2021-04-06 18:30 UTC, andrewjbtw commented
I'm pretty sure that Preassembly currently skips objects that aren't open and writes a message to the log that says something like "object skipped when object is open and version is greater than 1". Would this mean that Preassembly will start accessioning objects in this state? I believe preassembly is avoiding running on open objects because they may be open for another reason and running preassembly would then close them.

2021-04-06 18:33 UTC, andrewjbtw commented on app/controllers/objects_controller.rb
>      end
`not open, not openable, and not registered/v1`

I believe this describes "in accessioning".

2021-04-06 20:18 UTC, peetucket commented on app/controllers/objects_controller.rb
>      end
Ahh, that's a good point and we aren't checking for that.  I'm going to propose we add another check and return a 406 unacceptable if an item is currently in accessioning.  This would prevent us from adding a new workflow if there is one that is in process (or stuck in an error state).  Thoughts?

2021-04-06 20:24 UTC, peetucket commented
Ahh yes, that is happening here: https://github.com/sul-dlss/pre-assembly/blob/main/app/lib/pre_assembly/digital_object.rb#L70

Basically, it won't bother calling this start accession method if we can't open it and its not an initial version (basically "in accessioning").  The same check I'd propose adding here, though the caller would have to handle the 406 method.  

There is no harm in leaving pre-assembly the way it is, it would just an extra check to try and prevent creating bad data by kicking off accessioning when it shouldn't be.



> I'm pretty sure that Preassembly currently skips objects that aren't open and writes a message to the log that says something like "object skipped when object is open and version is greater than 1". Would this mean that Preassembly will start accessioning objects in this state? I believe preassembly is avoiding running on open objects because they may be open for another reason and running preassembly would then close them.

2021-04-06 20:43 UTC, peetucket commented
Note that the current consumers of start accession API endpoint modified here are:

* pre-assembly (does it's own check to try and prevent starting accessioning on something that is in process)
* goobi 
* sdr-api (this is the recent work done by John)

I think it is acceptable for any of these apps to get a 406 if they try to start accessioning on an object that is already currently in accessioning.  But open to whether the extra check I just added is a good idea or not.

2021-04-06 22:00 UTC, jmartin-sul commented on app/controllers/objects_controller.rb
>      end
@peetucket 👍 from me to that `406` idea.

i think i was vaguely imagining the version mismatch scenario ("it may be possible for something to be openable but for the version number to not be correct for whatever reason").  but @andrewjbtw's point about "in accessioning" is a good one, and makes for a more concrete/testable scenario.  that does seem like a possible race condition that could introduce versioning issues?

2021-04-06 22:02 UTC, peetucket commented on app/controllers/objects_controller.rb
>      end
It certainly seems plausible that a race condition could exist if you start accessioning on something already in progress, though the more likely situation is just an extra accessionWF on something that stopped mid-way due to an error (and will then error out again).  So I think this new check for "in accessioning" is not likely to prevent version mismatch errors, but seems reasonable to guard against anyway.

2021-04-06 22:04 UTC, peetucket commented on app/controllers/objects_controller.rb
>      end
new check for in accessioning added, along with a new test

2021-04-06 22:06 UTC, jmartin-sul commented
fwiw, it appears that the openability check does check to see whether something is in accessioning:

https://github.com/sul-dlss/dor-services-app/blob/5500c31d1c5ba4821559d7e4c2a7712c4a229b8a/app/services/version_service.rb#L107-L124

that said, i do like the specific error code for that situation, so no objection to @peetucket's latest proposed modification.

2021-04-06 22:08 UTC, peetucket commented
> fwiw, it appears that the openability check does check to see whether something is in accessioning:
> 
> https://github.com/sul-dlss/dor-services-app/blob/5500c31d1c5ba4821559d7e4c2a7712c4a229b8a/app/services/version_service.rb#L107-L124
> 
> that said, i do like the specific error code for that situation, so no objection to @peetucket's latest proposed modification.

Yes, I realized that too.  The problem is that if something is in accessioning and thus fail the openability check, that just means it won't be versioned... it will still have accessioning started.  So the new check is the only one that stops accessioning from being started at all.

2021-04-06 22:10 UTC, jmartin-sul commented
> > fwiw, it appears that the openability check does check to see whether something is in accessioning:
> > that said, i do like the specific error code for that situation, so no objection to @peetucket's latest proposed modification.
> 
> Yes, I realized that too. The problem is that if something is in accessioning and thus fails the openability check, that just means it won't be versioned... it will still have accessioning started. So the new check is the only one that stops accessioning from being started at all.

ah, yeah, good point.  so then i'm definitely in favor of the additional check.

2021-04-07 00:13 UTC, jmartin-sul requested changes
one small testing quibble, otherwise looks good to me!

2021-04-07 00:13 UTC, jmartin-sul commented on spec/requests/start_accession_spec.rb
> +      expect(VersionService).not_to have_received(:open).with(object, base_params, event_factory)
i've seen rubocop warn about this before, but if you don't expect `open` to be called at all in this scenario, you might want to remove the `with(...)` qualifier from this expectation

2021-04-07 02:24 UTC, peetucket commented on spec/requests/start_accession_spec.rb
> +      expect(VersionService).not_to have_received(:open).with(object, base_params, event_factory)
good call...fixed

2021-04-07 17:22 UTC, jmartin-sul commented on spec/requests/start_accession_spec.rb
> +      expect(VersionService).not_to have_received(:open).with(object, base_params, event_factory)
thanks!

2021-04-07 17:23 UTC, jmartin-sul approved these changes

2021-04-07 17:29 UTC, jmartin-sul commented
@peetucket i wasn't sure if you wanted to deploy the branch to -qa or -stage to run integration tests (or have @andrewjbtw test) before merge to `main`, so i held off on merging myself.

2021-04-07 18:18 UTC, peetucket commented
> @peetucket i wasn't sure if you wanted to deploy the branch to -qa or -stage to run integration tests (or have @andrewjbtw test) before merge to `main`, so i held off on merging myself.

Yup, good idea.  I'll deploy this branch to qa and then run the integration tests there

2021-04-07 18:18 UTC, andrewjbtw commented
I'm not sure how to tell if there are going to be any side effects without actually deploying this, so the QA, test, merge route makes sense to me.

2021-04-07 19:57 UTC, mjgiarlo commented on app/controllers/objects_controller.rb
> +    elsif VersionService.open_for_versioning?(@item, params)
I believe this line causes an exception: https://app.honeybadger.io/projects/50568/faults/78761944 

Should be `open?` instead of `open_for_versioning?`. Would be great for this `NoMethodError` to be raised in a test.

2021-04-07 19:57 UTC, mjgiarlo commented on spec/requests/start_accession_spec.rb
> +      allow(VersionService).to receive(:open_for_versioning?).and_return(false)
This line is why we're not seeing the `NoMethodError` get raised.

2021-04-07 20:07 UTC, peetucket commented on app/controllers/objects_controller.rb
> +    elsif VersionService.open_for_versioning?(@item, params)
i think in order to actually hit the `VersionService` in this test instead of just mocking the calls, we'd need to mock all of the actual underlying calls to the workflow service...but this was an unfortunate case of the actual bug slipping through the test

2021-04-07 23:36 UTC, peetucket commented
Releasing hold and I think it's ok to go.  It works fine with integration tests in QA (after a couple legit bug fixes pointed out by Mike).  Only one integration test is failing in QA, but it fails on stage and without my changes here as well in the same way.

2021-04-08 02:53 UTC, merged