apo adminMetadata mapping: only create disseminationWF if there is one
sul-dlss/dor-services-app pull request #2677
Opened 2021-04-13 04:06 UTC by ndushay

## Why was this change made?

- Adds roundtripping apo adminstrativeMetadata spec before working on ticket #2659
- doesn't create empty dissemination elements in APO administrativeMetaadata (part of #2644)

## How was this change tested?

- it's a spec, and a fix added because the spec illustrated it.

## Which documentation and/or configurations were updated?

2021-04-13 04:10 UTC, ndushay commented on app/services/cocina/to_fedora/apo_rights.rb
> +        admin_node.add_child "<dissemination><workflow id=\"#{administrative.disseminationWorkflow}\" /></dissemination>" if administrative.disseminationWorkflow
this is a partial fix for #2644, and was discovered with the new specs.   whee!

2021-04-13 04:10 UTC, ndushay commented on spec/services/cocina/mapping/administrative/apo_administrative_spec.rb
> +          # referencesAgreement: 'druid:yr951qr4199',
this is issue #2659, which I will work on as soon as this PR is merged.

2021-04-13 04:12 UTC, ndushay commented on spec/services/cocina/mapping/administrative/apo_administrative_spec.rb
> +    # TODO: test without roles ?
@aaron-collier, @justinlittman some tests/normalization to work on for clean APO roundtripping.

2021-04-13 04:12 UTC, ndushay commented on spec/services/cocina/mapping/administrative/apo_administrative_spec.rb
> +    xit 'problems with empty name elements in role/person, with sunetid members, with license (roundtrips as license url)' do
@aaron-collier, @justinlittman a test to work on for clean APO roundtripping.

2021-04-13 12:34 UTC, jcoyne commented on app/services/cocina/to_fedora/apo_rights.rb
> +        admin_node.add_child "<dissemination><workflow id=\"#{administrative.disseminationWorkflow}\" /></dissemination>" if administrative.disseminationWorkflow
If we do the full fix for for #2644, will this check be necessary?  I rather like the explicitness of having a `<dissemination>` node for every APO.  This shows that this is a configuration option that belongs to an APO and that in this case it has zero workflows in it.

2021-04-13 12:39 UTC, jcoyne requested changes

2021-04-13 12:39 UTC, jcoyne commented on spec/services/cocina/mapping/administrative/apo_administrative_spec.rb
> +RSpec.shared_examples 'APO from Fedora to Cocina mapping' do
Isn't this spec duplicating what we already have in `spec/requests/create_object_spec.rb` and `spec/requests/update_object_spec.rb` for full integration tests as well as `spec/services/cocina/to_fedora/*_spec.rb` for unit tests?   I don't think having specs in yet another location makes it easy to find the tests we are looking for. I'd rather we address any deficiencies in these previous locations rather than add yet another set of specs.

2021-04-13 16:32 UTC, ndushay commented on app/services/cocina/to_fedora/apo_rights.rb
> +        admin_node.add_child "<dissemination><workflow id=\"#{administrative.disseminationWorkflow}\" /></dissemination>" if administrative.disseminationWorkflow
noted;  will note in #2644 and I have taken that ticket to work on shortly.

2021-04-13 16:35 UTC, ndushay commented on spec/services/cocina/mapping/administrative/apo_administrative_spec.rb
> +RSpec.shared_examples 'APO from Fedora to Cocina mapping' do
The roundtripping is crucial to get right before we cutover and the way the unit tests are written, it is not addressed.   We can certainly move some of the tests in those other place to this location, especially the  to_fedora  tests that are relevant.   Testing this way has already surfaced a bunch of stuff that won't roundtrip cleanly.

2021-04-13 16:39 UTC, ndushay commented on spec/services/cocina/mapping/administrative/apo_administrative_spec.rb
> +RSpec.shared_examples 'APO from Fedora to Cocina mapping' do
Also - we discussed this approach in mid-sprint planning yesterday and many folks chimed in that doing roundtrip testing of mappings beyond MODS (e.g. access, identity, structural) will likely be very useful for the same reasons -- we need to be sure we can do clean roundtrips and the current tests don't cover that.

2021-04-13 16:40 UTC, jcoyne commented on spec/services/cocina/mapping/administrative/apo_administrative_spec.rb
> +RSpec.shared_examples 'APO from Fedora to Cocina mapping' do
The round tripping is fine, is there a reason that can't be done in the request specs or the unit specs I've pointed out?  I don't want to introduce yet another place that one should look for tests.  Also, I'm skeptical that "round-tripping" is the goal. I know that we don't want to loose important data, but sometimes we are writing things in a way that was better (more explicit) than it would otherwise be.

2021-04-13 16:43 UTC, ndushay commented on spec/services/cocina/mapping/administrative/apo_administrative_spec.rb
> +RSpec.shared_examples 'APO from Fedora to Cocina mapping' do
this is following the pattern used for MODS.  unit specs ... are only for the direction of the code -- one way -- so they are not a good choice.   We found this approach worked really really well for MODS roundtripping.   It does not replace the need for unit tests or for request specs ... it augments.   I think maybe you'll need to let this go through and we can discuss it further when you and I are both available, and possibly as a team discussion.  I think you might be missing some context.

2021-04-13 16:49 UTC, ndushay commented on spec/services/cocina/mapping/administrative/apo_administrative_spec.rb
> +RSpec.shared_examples 'APO from Fedora to Cocina mapping' do
"Request specs provide a thin wrapper around Rails' integration tests, and are
designed to drive behavior through the full stack, including routing
(provided by Rails) and without stubbing (that's up to you)." -- this is useful, but it's not about roundtripping metadata in an API app that would only ever get one direction from a single API call.

2021-04-13 16:56 UTC, ndushay commented on spec/services/cocina/mapping/administrative/apo_administrative_spec.rb
> +RSpec.shared_examples 'APO from Fedora to Cocina mapping' do
- where should roundtrip specs live?  In the code base where the mappings are done.
- the app where the mappings are done is an API app
- each direction of mapping is used for separate API calls;  testing the individual API calls works well as a request spec

I am more than happy to discuss consolidating tests or moving test code to a different location when you and I are both working and can talk in realtime.;  I think this is a useful PR as it stands, and the "cleanup" or "consolidation" can happen separately

2021-04-13 17:04 UTC, jcoyne commented on spec/services/cocina/mapping/administrative/apo_administrative_spec.rb
> +RSpec.shared_examples 'APO from Fedora to Cocina mapping' do
Round tripping is not important for this data. It is very important for MODS as this is something we plan to do for a long time.  So because we have different requirements for those, let's not try to use the same approach.  Any update request is already doing a round trip because it writes to fedora and then builds the cocina model anew from Fedora: https://github.com/sul-dlss/dor-services-app/blob/main/app/services/cocina/object_updater.rb#L51-L54  So any test in tthttps://github.com/sul-dlss/dor-services-app/blob/main/app/services/cocina/object_updater.rb#L51-L54 is already doing this.

2021-04-13 17:17 UTC, justinlittman commented on spec/services/cocina/mapping/administrative/apo_administrative_spec.rb
> +RSpec.shared_examples 'APO from Fedora to Cocina mapping' do
One of the lessons of our MODS work is that one-direction testing inevitably produced gaps in the testing. An approach that made roundtrip testing the default definitely reduced mapping errors.

That being said, if tests are moved here, we want to make sure redundant tests are removed from other areas.

2021-04-13 17:31 UTC, jcoyne commented on spec/services/cocina/mapping/administrative/apo_administrative_spec.rb
> +RSpec.shared_examples 'APO from Fedora to Cocina mapping' do
@ndushay the conference, aside from keynotes is completely asynchronous and I have availability to have real time discussion.

2021-04-13 17:32 UTC, ndushay commented on spec/services/cocina/mapping/administrative/apo_administrative_spec.rb
> +RSpec.shared_examples 'APO from Fedora to Cocina mapping' do
FYI:

There are no unit tests for the mapping classes:  Cocina::FromFedora::APO and Cocina::ToFedora::AdministativeMetadata (was apo_rights).    

The unit tests for Cocina::ObjectUpdater, relevant to an APO, are checking that when a particular part of the cocina model is updated, the relevant fedora datastream is updated -- an excellent unit test, but not on point for the roundtrip testing.  There is no unit test for an APO in Cocina::ObjectCreator.

The request specs of relevance appear to be in 
- create_object_spec.rb -- there *may* be some duplicative testing there, but I would argue that it is testing that "given this api call, the right thing happens", and that   I would be happy to make a ticket to indicate this needs revisiting.

2021-04-13 17:32 UTC, ndushay commented on app/services/cocina/to_fedora/apo_rights.rb
> +        admin_node.add_child "<dissemination><workflow id=\"#{administrative.disseminationWorkflow}\" /></dissemination>" if administrative.disseminationWorkflow
noted in ticket #2644

2021-04-13 17:46 UTC, jcoyne commented on spec/services/cocina/mapping/administrative/apo_administrative_spec.rb
> +RSpec.shared_examples 'APO from Fedora to Cocina mapping' do
> There are no unit tests for the mapping classes: Cocina::FromFedora::APO and Cocina::ToFedora::AdministativeMetadata (was apo_rights).

The relevant steps are likely covered in the integration tests and higher level unit tests.  If you see a gap, is it possible to improve it there rather than creating a new paradigm?

> The unit tests for Cocina::ObjectUpdater, relevant to an APO, are checking that when a particular part of the cocina model is updated, the relevant fedora datastream is updated -- an excellent unit test, but not on point for the roundtrip testing. There is no unit test for an APO in Cocina::ObjectCreator.

Why is it "not on point"?  What is preventing you from  you making it so? I'm absolutely certain we are missing test cases here (as evidenced by the tickets being open), but why can't we add them here.

I don't think that I'm being clear about why I think that round tripping for administrativeMetadata is not important.
AdministrativeMetadata is the serialization format exclusively for DSA it should be completely opaque from the outside. There are no other systems that need to know how to parse this XML.  We could convert it to binary data and nobody would be the wiser because our API encapsulates that implementation detail.  We intend to do this in the near future when we move to database for persistence.  This is why using request tests for this scenario is the best way to ensure the data we send in (via cocina) is the data we get out (also via cocina). 

On the other hand, MODS is produced externally and consumed externally.  Thus we need to go bi-directionally from MODS to Cocina.  This is not the use case for administrativeMetadata.   I'm concerned that tests written they way you have now in this PR will likely be deleted when we go to a new persistence layer.

2021-04-13 17:54 UTC, jcoyne commented on spec/services/cocina/mapping/administrative/apo_administrative_spec.rb
> +RSpec.shared_examples 'APO from Fedora to Cocina mapping' do
Here's how I would expand the existing test that does round tripping: #2681

2021-04-13 17:57 UTC, justinlittman commented on spec/services/cocina/mapping/administrative/apo_administrative_spec.rb
> +RSpec.shared_examples 'APO from Fedora to Cocina mapping' do
I'm not understanding why roundtripping is important for descriptive/MODS, but not other types of data. Since we will be creating/updating objects in the immediate future and mapping all objects permanently from Fedora to Cocina in the near future, it seems important regardless.

Having worked on the request specs, they are a cumbersome way to test mappings. More direct unit tests such as these are cleaner and easier to work on.

2021-04-13 18:03 UTC, jcoyne commented on spec/services/cocina/mapping/administrative/apo_administrative_spec.rb
> +RSpec.shared_examples 'APO from Fedora to Cocina mapping' do
@justinlittman  I think the 2 line change is #2681 is a much simpler change than the ~530 line change proposed here. 

MODS roundtrip tests were important because Arcadia was writing them, because MODS is complex, because the timeframe to keep this is longer, because the app needs to accept both MODS and Cocina and because there was no underlying modeling approach (ActiveFedora/OM models).  All of these circumstances are different here.

2021-04-13 18:27 UTC, justinlittman commented on spec/services/cocina/mapping/administrative/apo_administrative_spec.rb
> +RSpec.shared_examples 'APO from Fedora to Cocina mapping' do
I agree with your logic -- we don't want to test the implementation detail of persisting as Fedora. However, that doesn't seem to correspond with request specs. If you look at the request specs, e.g., for object_updater, most of what is being tested is mapping / the implementation detail of persisting as Fedora. When we take Fedora out of the equation, we'll probably discard/simplify most of the request specs.

2021-04-13 18:36 UTC, ndushay commented on spec/services/cocina/mapping/administrative/apo_administrative_spec.rb
> +RSpec.shared_examples 'APO from Fedora to Cocina mapping' do
@jcoyne the issue here isn't whether or not I can address #2659 for the referencesAgreement with an easy change.  **The issue is that roundtrip testing is desired by Andrew and this is a way to do it.**  Is it perfect?  Of course not.  But it is a way.   Will we need this roundtripping test code forever?  Nope -- it's all about cocina to fedora and back and vice versa.  

Given that we at least temporarily have been asked to provide this roundtrip testing, it makes sense to alter relevant mappings AFTER we have this testing in place and have this way to ensure that the new mappings roundtrip cleanly.

2021-04-13 19:20 UTC, jcoyne commented on spec/services/cocina/mapping/administrative/apo_administrative_spec.rb
> +RSpec.shared_examples 'APO from Fedora to Cocina mapping' do
I think I've been missing context.

> The issue is that roundtrip testing is desired by Andrew and this is a way to do it

> Given that we at least temporarily have been asked to provide this roundtrip testing

That was not clear in the description of this ticket an I didn't see any issues like that on the board.

> it's all about cocina to fedora and back and vice versa.

We already have the "cocina to fedora and back part" covered by existing tests.    We do not yet have "vice-versa" covered an as I've already explained, I'm not sure why this latter part is necessary.  What user case are we addressing there?

2021-04-15 11:07 UTC, justinlittman approved these changes
Approve pending consideration of comments.

Are the various xit's/TODO's ticketed?

2021-04-15 11:07 UTC, justinlittman commented on spec/services/cocina/mapping/administrative/apo_administrative_spec.rb
> +                                 # source_id: cocina_admin_policy.identification.sourceId,
Cruft?

2021-04-15 11:07 UTC, justinlittman commented on spec/services/cocina/mapping/administrative/apo_administrative_spec.rb
> +        Cocina::ToFedora::Roles.write(fedora_apo, Array(actual_cocina_apo_admin.roles))
Does the Array() belong here or does this indicate a condition that should be handled by `Cocina::ToFedora::Roles.write()`?

2021-04-15 11:21 UTC, jmartin-sul approved these changes
a couple small questions, but this looks good to me.

restating some things to make sure i understand them:
* we have a lot of data with a very complex data serialization format in principle.  in practice we've collected millions of objects in a non-transactional data store, with little pre-save validation for conformance to the expected structure, and much hand editing.  there's a lot of unknown and irregularity we have to tolerate.
* we essentially don't want to lose any (?) of it in translation/transfer to the successor serialization format/data store, except where we explicitly decide it's ok.
* fedora -> cocina -> fedora roundtrip testing seems to have caught mapping bugs we'd otherwise have missed (in PRs like this / #2701 / #2703 / #2704, and for real data as with `bin/validate-desc-cocina-roundtrip`)

and if those things are true, my $0.02 to the larger discussion in this PR and the associated meeting:
* i'm in favor of using and expanding (e.g #2700) on the existing roundtrip validation of real fedora datastream xml to look for regressions from any mapping changes, and to make sure changes improve things when expected
  *  and when the time comes to actually migrate, to maybe do a last check to make sure that the final fedora representation roundtrips cleanly before being serialized in cocina for storage using the successor data store as the source of truth, and alerting for manual remediation if the check fails
* but i also find that roundtrip unit tests on basic/represenatative/tricky examples, as with this PR, provide good quick guard rails for development.  e.g. breaking a bunch of existing roundtrip unit tests in the style of this PR prevented me from inadvertently going down the wrong path on #2456 / #2661.
* personally, instead of framing this sort of test code as specs for dor-services app that we know we have to throw away soon, i'd look at it as safeguard and analysis code to give us peace of mind while ironing out a very tricky format mapping and a difficult data store migration.  i don't think that code has a super clear ideal home, but pragmatically the choices for the fedora roundtrip validation code seem good to me so far.
* i can't currently think of an easier or less throwaway way to get the same peace of mind that thorough roundtrip testing has given us, and i'd be hesitant to have less thorough testing than that on any datastream we know we want to keep, given what that sort of testing has turned up for us so far.

2021-04-15 17:59 UTC, ndushay commented on spec/services/cocina/mapping/administrative/apo_administrative_spec.rb
> +          # referencesAgreement: 'druid:yr951qr4199',
yes, precisely - RELS_EXT wil be needed for referencesAgreement and I was ... prepping.   Not perfectly agile, nor obvious from the PR.

2021-04-15 18:00 UTC, ndushay commented on spec/services/cocina/mapping/administrative/apo_administrative_spec.rb
> +  end
agree with you, and yes, this will only be used in this file as administrativeMetadata.xml is only used for APOs.

2021-04-15 19:18 UTC, ndushay commented on spec/services/cocina/mapping/administrative/apo_administrative_spec.rb
> +                                 # source_id: cocina_admin_policy.identification.sourceId,
actually, I don't know if it is needed or not at this point.  I copied this comment from https://github.com/sul-dlss/dor-services-app/blob/main/app/services/cocina/object_creator.rb#L64. (hahahaha!).   I'll remove it.

2021-04-15 19:22 UTC, ndushay commented on spec/services/cocina/mapping/administrative/apo_administrative_spec.rb
> +        Cocina::ToFedora::Roles.write(fedora_apo, Array(actual_cocina_apo_admin.roles))
Turns out it isn't needed.  Once again, I copied it from https://github.com/sul-dlss/dor-services-app/blob/main/app/services/cocina/object_creator.rb#L70 / https://github.com/sul-dlss/dor-services-app/blob/main/app/services/cocina/object_updater.rb#L84 (hahahaha)

2021-04-15 20:03 UTC, justinlittman approved these changes

2021-04-15 20:03 UTC, merged

2021-04-15 20:04 UTC, ndushay commented
@jmartin-sul FYI, I added your comment to the testing doc from the meeting:  https://docs.google.com/document/d/19NSubyerKKh5pjwkFrzBsUtHFZAlIla91C7h8jwiTnI

2021-04-15 20:05 UTC, ndushay commented
normalizations needed ticketed as https://github.com/sul-dlss/dor-services-app/issues/2707