Fix bug with rights determinations when metadata has multiple access nodes
sul-dlss/dor-services-app pull request #2716
Opened 2021-04-16 21:09 UTC by mjgiarlo

Connects to sul-dlss/argo#2382

## Why was this change made?

Rights metadata containing e.g. file-specific nodes reveal a bug in the prior `FromFedora/Access` implementation, namely the assumption that the presence of a single access=read node is meaningful. Instead of hand-crafted, buggy XPaths, re-use the logic that is already in place in the dor-rights-auth gem.

This PR adds full object-level rights mappings on both the to- and from-fedora sides (32 cases a piece).

## How was this change tested?

CI. This is on HOLD until @andrewjbtw can run some tests in QA.

## Which documentation and/or configurations were updated?

None

2021-04-16 21:11 UTC, mjgiarlo commented on app/services/cocina/from_fedora/access.rb
> +          download: download,
This was too simplistic and did not cover all 32 object-level rights mapping cases we have.

2021-04-16 21:11 UTC, mjgiarlo commented on app/services/cocina/from_fedora/access.rb
> +          h[:controlledDigitalLending] = true if controlled_digital_lending?
Instead of implementing a bunch of bespoke and buggy XPaths, use the dor-rights-auth gem for heavy lifting.

2021-04-16 21:14 UTC, mjgiarlo commented on app/services/cocina/from_fedora/access.rb
> +        'foobar'
Cruft. Will remove.

2021-04-16 21:18 UTC, aaron-collier commented on app/services/cocina/from_fedora/access.rb
> +        return 'world' if obj_lvl.group.fetch(:stanford).rule
Can you clarify why the return of `stanford` above on `obj_lvl.world.rule` and `world` here?

2021-04-16 21:18 UTC, aaron-collier commented on app/services/cocina/from_fedora/access.rb
> +        'foobar'
I like it, but assume we don't want to return `foobar` :-)

2021-04-16 21:23 UTC, mjgiarlo commented on app/services/cocina/from_fedora/access.rb
> +        'foobar'
Yep! Removing now. :beers:

2021-04-16 21:23 UTC, mjgiarlo commented on app/services/cocina/from_fedora/access.rb
> +        return 'world' if obj_lvl.group.fetch(:stanford).rule
I just tossed another commit at this to simplify it.

2021-04-16 21:31 UTC, mjgiarlo commented on app/services/cocina/from_fedora/access.rb
> +        return 'stanford' if stanford_world_no_download?
Here's an algorithm for determining download access based on both the object-level rights and the object-level download, using helper methods that lean on dor-rights-auth. It errs on the side of explicitness by commenting every line.

2021-04-16 21:32 UTC, mjgiarlo commented on app/services/cocina/from_fedora/access.rb
> +        citation_only? || dark? || controlled_digital_lending?
We do not allow downloads for any of these items.

2021-04-19 12:36 UTC, justinlittman approved these changes
Approve pending consideration of question.

2021-04-19 12:36 UTC, justinlittman commented on app/services/cocina/to_fedora/access.rb
> -        rightsMetadata.content = rightsMetadata.ng_xml.to_s
Is it problematic that this was dropped?

2021-04-19 15:12 UTC, mjgiarlo commented on app/services/cocina/to_fedora/access.rb
> -        rightsMetadata.content = rightsMetadata.ng_xml.to_s
@justinlittman I don't think so. It was essentially replaced by [`Cocina::ToFedora::RightsMetadataGenerator#generate`](https://github.com/sul-dlss/dor-services-app/pull/2716/files#diff-fc3f0a6382213c47496252a88f5591b894a61d327791de94125c55d8f44d1f63R19-R35). Thanks for the review!

2021-04-19 17:54 UTC, ndushay requested changes
in from_fedora/access line 7 - I am not fully clear on why it is explicitly called `collection_props` ... is it because the basic rights ALWAYS come from collections?   Maybe the comment could be improved?  (esp. since we're doing rights on ITEMs, no?)

2021-04-19 17:54 UTC, ndushay commented on spec/services/cocina/from_fedora/dro_access_spec.rb
> +      it 'builds the hash' do
same request regarding these descriptions

2021-04-19 18:04 UTC, andrewjbtw commented
When setting rights from the blue button, I got the following errors on stage (the switch was from "World" to "World no-download"):

dor-services-app: https://app.honeybadger.io/projects/50568/faults/78908761
```
NameError: undefined local variable or method `cocina_object' for #<ObjectsController:0x00007f2230acd1a0>
```

Argo: https://app.honeybadger.io/projects/49894/faults/78940241
```
NoMethodError: undefined method `first' for nil:NilClass
```

2021-04-19 18:21 UTC, mjgiarlo commented on spec/requests/update_metadata_spec.rb
> +    allow(Cocina::ToFedora::RightsMetadataGenerator).to receive(:generate)
Agree. This was recommended by @jcoyne because, basically, it's either mock out the Fedora bits or add Fedora as a CI runtime dependency, which I was hoping to avoid for this PR.

2021-04-19 18:23 UTC, mjgiarlo commented on app/services/cocina/from_fedora/access.rb
> +          h[:controlledDigitalLending] = true if controlled_digital_lending?
@ndushay When we dump Fedora, I don't think it'll be useful any longer, but apparently we're stuck with Fedora for another year at least.

2021-04-19 18:28 UTC, mjgiarlo commented
@ndushay :speech_balloon: 
> in from_fedora/access line 7 - I am not fully clear on why it is explicitly called `collection_props` ... is it because the basic rights ALWAYS come from collections? Maybe the comment could be improved? (esp. since we're doing rights on ITEMs, no?)

I don't know why. I ***suspect*** it was to add some clarity about the relationship between Access and DROAccess, which could use improvement. The relationship is that DROAccess inherits from Access, but Access is the class used for collections (even though it's not in the class name). Stuffing `collection` in the class method communicates that that method is collection-specific even if the class itself is not. It's admittedly messy. I'd like not to change that in this PR if I could avoid it.

2021-04-19 18:42 UTC, mjgiarlo commented on spec/services/cocina/from_fedora/access_spec.rb
> +      it 'builds the hash' do
done.

2021-04-19 18:42 UTC, mjgiarlo commented on spec/services/cocina/from_fedora/dro_access_spec.rb
> +      it 'builds the hash' do
done

2021-04-19 18:43 UTC, mjgiarlo commented
@ndushay replied to all your comments. Thanks for the review! Mind having another look?

2021-04-19 20:13 UTC, andrewjbtw commented
This looks good for object-level rights. I checked all of the menu choices, the special case of "world access, stanford can download", plus at least one location for:

- location-based, no download
- world access, location-download
- stanford access, location-download

From the Fedora perspective, this includes both rights settings with one "read" block and rights settings with two "read" blocks.

2021-04-19 20:22 UTC, ndushay approved these changes

2021-04-19 20:22 UTC, ndushay commented on app/services/cocina/from_fedora/access.rb
> +          h[:controlledDigitalLending] = true if controlled_digital_lending?
i think a sideways thumb might have been the best emoticon.  dor-rights-auth is not my fav gem, but it does serve a purpose decently, i suppose.

2021-04-19 20:22 UTC, ndushay commented on app/services/cocina/from_fedora/access.rb
> +        return 'stanford' if stanford_world_no_download?
"Here's an algorithm for determining download access based on both the object-level rights and the object-level download, using helper methods that lean on dor-rights-auth."

2021-04-19 20:22 UTC, ndushay commented on spec/requests/update_metadata_spec.rb
> +    allow(Cocina::ToFedora::RightsMetadataGenerator).to receive(:generate)
understood.  Wishing for the moon.

2021-04-19 20:23 UTC, ndushay commented
> @ndushay 💬
> 
> > in from_fedora/access line 7 - I am not fully clear on why it is explicitly called `collection_props` ... is it because the basic rights ALWAYS come from collections? Maybe the comment could be improved? (esp. since we're doing rights on ITEMs, no?)
> 
> I don't know why. I _**suspect**_ it was to add some clarity about the relationship between Access and DROAccess, which could use improvement. The relationship is that DROAccess inherits from Access, but Access is the class used for collections (even though it's not in the class name). Stuffing `collection` in the class method communicates that that method is collection-specific even if the class itself is not. It's admittedly messy. I'd like not to change that in this PR if I could avoid it.

agree.  Just trying to puzzle it out as a side effect of this review.   Maybe we should consider renaming it in cocina-models ... maybe ...

2021-04-19 20:26 UTC, mjgiarlo commented on app/services/cocina/from_fedora/access.rb
> +        return 'stanford' if stanford_world_no_download?
Added! Thanks, @ndushay

2021-04-19 20:39 UTC, ndushay commented
I think my LEAST favorite lines are not yours, but I find them very confusing - maybe you've figured it out and can improve on them:

https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/from_fedora/access_spec.rb#L8-L10

```
let(:item) do
    Dor::Collection.new
end
```

2021-04-19 21:05 UTC, mjgiarlo commented
@ndushay :speech_balloon: 
> I think my LEAST favorite lines are not yours, but I find them very confusing - maybe you've figured it out and can improve on them:
> 
> [`main`/spec/services/cocina/from_fedora/access_spec.rb#L8-L10](https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/from_fedora/access_spec.rb?rgh-link-date=2021-04-19T20%3A39%3A56Z#L8-L10)
> 
> ```
> let(:item) do
>     Dor::Collection.new
> end
> ```

Yeah, we should prolly change those!

2021-04-19 21:06 UTC, merged