[HOLD] Updates cocina for access rights.
sul-dlss/dor-services-app pull request #2744
Opened 2021-04-20 13:01 UTC by justinlittman

## Why was this change made?
* Support the updated cocina model for embargoes by providing a full mapping.
* Refactor access/rights mapping so that mapping code could be shared between embargo and access when appropriate.

## How was this change tested?
Unit

## Which documentation and/or configurations were updated?
openapi

2021-04-21 17:24 UTC, ndushay requested changes
i'm officially confused:   if cocina-models is now DROAccess and CollectionAccess (which I like), 

are we keeping DROAccess for mapping code and renaming  what was xxxFedora::Access to xxxFedora::CollectionAccess to match?   Or are we being clever and having a single xxxFedora::Access mapping class which creates the correct model flavor?

it's confusing, but current DSA has TWO mapping classes for each flavor:

one for collections
one for dro ... which inherits from the collections one

your changes here aren't in keeping with the current code -- should the dro_access classes be removed from the from_fedora and to_fedora areas?

It's possible I'm completely confused.  It's also possible that some of my comments are useful anyway.

2021-04-21 17:24 UTC, ndushay commented on app/services/cocina/from_fedora/access.rb
> +      end
currently addressed in Cocina::FromFedora::DROAccess  ??   Not that I'm in love with that approach ... but heretofore the cocina-models had both flavors.   Delighted if they go away ... but wonder if this should be dro_props just to be clearer in cocina language?

2021-04-21 17:24 UTC, ndushay commented on app/services/cocina/from_fedora/embargo.rb
> +      def dra_object
typo - dro not dra. ?   or don't use DRA abbreviation if it means something other than DRO

2021-04-21 17:24 UTC, ndushay commented on app/services/cocina/from_fedora/access_helper.rb
> +    class AccessHelper
I like this refactoring!

2021-04-21 17:24 UTC, ndushay commented on app/services/cocina/to_fedora/dro_access.rb
>      class DROAccess < Access
yay! - you caught it for ToFedora, but what about FromFedora?

2021-04-21 17:24 UTC, ndushay commented on app/services/embargo_service.rb
> -class EmbargoService
whoa!  I think we _might_ want to keep an EmbargoService?   I'm thinking of someone, in Argo, wanting to change an embargo date.   Are you envisioning that working a different way?   Because we don't always consider changing embargos requiring mapping to and from fedora, do we?

I see that THIS implementation is fedora-centric.   But I think we'll want a way to do this native cocina.

2021-04-21 17:24 UTC, ndushay commented on spec/services/cocina/to_fedora/access_spec.rb
> +  subject(:apply) { described_class.apply(item, access) }
shouldn't we check both item and collection?

2021-04-21 21:24 UTC, justinlittman commented
Wow, I missed the forest for the weeds (and entirely skipped the trees). Thanks for catching @ndushay. I'm refactoring some of the classes and tests to consolidate.

2021-04-21 21:25 UTC, justinlittman commented on app/services/cocina/from_fedora/embargo.rb
> +      def dra_object
I don't know what it means: https://github.com/sul-dlss/dor-services/blob/main/lib/dor/datastreams/rights_metadata_ds.rb#L89

2021-04-21 21:28 UTC, ndushay commented on app/services/cocina/from_fedora/embargo.rb
> +      def dra_object
how about `dor_rights_auth_object` ?

2021-04-21 21:29 UTC, justinlittman commented on app/services/embargo_service.rb
> -class EmbargoService
`EmbargoService` became `Cocina::ToFedora::EmbargoGenerator`. I didn't make sense to have it as a service, when it is really to fedora mapping code.

2021-04-21 21:30 UTC, justinlittman commented on app/services/embargo_service.rb
> -class EmbargoService
Oh, and to be clear there is no longer an embargo endpoint in dor-services-app. It was subsumed by the update endpoint.

2021-04-21 21:31 UTC, justinlittman commented on spec/services/cocina/to_fedora/access_spec.rb
> +  subject(:apply) { described_class.apply(item, access) }
Now moved to separate tests.

2021-04-21 21:31 UTC, ndushay commented on app/services/embargo_service.rb
> -class EmbargoService
I didn't look at it closely enough to understand which code addresses the embargo date change stuff ... but we have integration tests for that now (deposit_via_hydrus_spec) so if we break it, we should be able to find out before deploying to prod!

2021-04-21 21:32 UTC, ndushay commented on app/services/embargo_service.rb
> -class EmbargoService
oh yeah - the famous update endpoint will be used for embargo kerfuffle.  w00t.  good on you for remembering.

2021-04-21 21:48 UTC, mjgiarlo commented on app/services/cocina/from_fedora/access.rb
> +        }.compact.merge(AccessHelper.props(dra_object: rights_metadata_ds.dra_object))
Similar to what I was working on in #2748, it looks like?

2021-04-21 22:45 UTC, ndushay reviewed
dropped a couple more line comments.  Would love to be at meeting between you and Mike, but since I have a doc appt in the morning, I think you should proceed without me.

2021-04-21 22:45 UTC, ndushay commented on app/services/cocina/from_fedora/collection_access.rb
> +          props[:access] = 'world' unless props[:access] == 'dark'
I'm not 100% convinced it's better to have the DRO properties in the super class, vs having them only specified in the DROAccess class ...

2021-04-21 22:45 UTC, ndushay commented on app/services/cocina/from_fedora/embargo.rb
> +          releaseDate: embargo_metadata_ds.release_date.first.utc.iso8601
I'm starting to wonder if we come out ahead having this be a DateTime here rather than a string.  Is that required because we make it a date object in the API?

2021-04-21 22:45 UTC, ndushay commented on app/services/cocina/to_fedora/embargo_generator.rb
> +    class EmbargoGenerator
so more accurately:  `EmbargoMetadataGenerator` ?

2021-04-22 11:13 UTC, justinlittman commented on app/services/cocina/from_fedora/embargo.rb
> +          releaseDate: embargo_metadata_ds.release_date.first.utc.iso8601
Yes. Either we provide it with a DateTime or dry types will coerce it to a DateTime.

2021-04-22 11:14 UTC, justinlittman commented on app/services/cocina/from_fedora/embargo.rb
> +      def dra_object
Works for me.

2021-04-22 11:23 UTC, justinlittman commented on app/services/cocina/to_fedora/embargo_generator.rb
> +    class EmbargoGenerator
Yes. Renamed.

2021-04-23 21:17 UTC, closed without merging