[WIP] adjust rights normalization
sul-dlss/dor-services-app pull request #2811
Opened 2021-04-30 22:00 UTC by peetucket

## Why was this change made?

Fixes #2797 - adjust rights normalization to deal with license code style differences

remove the "roundtrip" normalizer, which is no longer necessasry (and also so that this style better matches what we do in descMetadata validation)

## How was this change tested?

Updated tests

## Which documentation and/or configurations were updated?

2021-04-30 22:02 UTC, peetucket commented
FYI @ndushay and @jmartin-sul , this is the start the work we discussed...will pick up and actually do the bit to add the license code later, but I found a class that may do what we need: https://github.com/sul-dlss/dor-services-app/blob/main/app/services/cocina/to_fedora/license.rb

2021-04-30 22:02 UTC, peetucket commented
Note the test failure is expected ... it will pass when the implementation of the license transformation is complete

2021-05-01 03:55 UTC, peetucket commented on app/services/cocina/normalizers/rights_normalizer.rb
> +      def self.normalize(datastream:)
passing in the datatream here instead of the XML itself since the license URI adding method I want to use takes the datastream as the input

2021-05-03 16:59 UTC, ndushay requested changes
one small thing and a larger ... wait ... where are we? as I'm trying to do something that may depend on this work.

2021-05-03 16:59 UTC, ndushay commented on app/services/cocina/normalizers/rights_normalizer.rb
> +        new_license_node = Nokogiri::XML::Node.new('license', Nokogiri::XML(nil))
I *think* the second argument here should be ng_xml -- https://www.rubydoc.info/github/sparklemotion/nokogiri/Nokogiri/XML/Node#new-class_method implies the second argument is about telling ng when it can garbage collect on the new node

2021-05-03 18:04 UTC, ndushay requested changes
@peetucket did you have to do anything to validate-cocina-roundtrip script for the rights normalizer to take the datastream?

I think that is needed or it will break that script.

2021-05-03 18:58 UTC, ndushay approved these changes

2021-05-03 18:59 UTC, merged