do not double escape HTML in identity metadata on roundtrip
sul-dlss/dor-services-app pull request #2820
Opened 2021-05-03 22:02 UTC by peetucket

## Why was this change made?

Fixes #2816 - avoid double escaping in identity metadata on roundtrip

## How was this change tested?

Unxited an existing test

## Which documentation and/or configurations were updated?

2021-05-03 22:03 UTC, peetucket commented on app/services/cocina/to_fedora/identity.rb
> +        fedora_object.objectLabel = CGI.unescapeHTML(label) if fedora_object.objectLabel.empty?
I think the `objectLabel` setting on fedora object is escaping, so we want to be sure we start with an unescaped value before we set it in fedora.

2021-05-03 22:04 UTC, peetucket commented on spec/services/cocina/mapping/identification/dro_spec.rb
> -            <objectLabel>E&amp;#x301;ve&amp;#x301;nement du 19 fevrier 1790</objectLabel>
This test actually had an object label explicitly coming back as different after the roundtripping before this change, and now it comes back exactly the same.  So I'm not sure... shouldn't it come back exactly the same after roundtripping?

2021-05-03 22:04 UTC, peetucket commented on spec/services/cocina/mapping/identification/dro_spec.rb
> +    it_behaves_like 'DRO Identification Fedora Cocina mapping' do
the test that was unskipped that now passes

2021-05-03 22:09 UTC, peetucket commented on app/services/cocina/to_fedora/identity.rb
> +        fedora_object.objectLabel = CGI.unescapeHTML(label) if fedora_object.objectLabel.empty?
Here is the definition in the datastream in `dor-services`: https://github.com/sul-dlss/dor-services/blob/main/lib/dor/datastreams/identity_metadata_ds.rb#L17

and where it gets delegated to from the object level: https://github.com/sul-dlss/dor-services/blob/main/lib/dor/models/abstract.rb#L81

Perhaps ActiveFedora is doing the encoding as it generates the HTML

2021-05-03 22:14 UTC, jcoyne commented on app/services/cocina/to_fedora/identity.rb
> +        fedora_object.objectLabel = CGI.unescapeHTML(label) if fedora_object.objectLabel.empty?
I'm curious why you are bringing HTML into this.  The original ticket was about ampersand escape in XML.

2021-05-03 22:20 UTC, jcoyne requested changes
The problem is not in this code.  The problem is that someone injected a literal `&amp;` in the JSON source (on line 69 and originally https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/identification/dro_spec.rb#L1180)  JSON doesn't think this is a special escape sequence, so this code was behaving correctly.

2021-05-03 22:38 UTC, peetucket commented
> The problem is not in this code. The problem is that someone injected a literal `&amp;` in the JSON source (on line 69, 56, 41 and originally https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/identification/dro_spec.rb#L1180) JSON doesn't think this is a special escape sequence, so this code was behaving correctly.

I think the problem is that we have some data with an `&amp;` in the source which is getting double encoded?  That example you reference is from an actual object we have: https://argo.stanford.edu/view/druid:bb001zc5754

I unskipped the spec that had it and made it pass by unescaping. But the HTML unescape is probably overkill, I believe there are only a handful of characters than need to be XML escaped.

2021-05-03 22:41 UTC, jcoyne commented
@peetucket but that `:label` value is being used both as an xml snippet, where it should be encoded and as the stubbed return value from the label method on an object, where it wouldn't be encoded.

2021-05-03 22:52 UTC, peetucket commented
> @peetucket but that `:label` value is being used both as an xml snippet, where it should be encoded and as the stubbed return value from the label method on an object, where it wouldn't be encoded.

Yeah, I see what you mean...though i guess I'd expect the starting XML snippet (the stubbed `identity_metadata_xml`) which has `<objectLabel>#{label}</objectLabel>` to equal the round-tripped XML snippet (the stubbed `roundtrip_identity_metadata_xml`), which is what the unskipped spec is asserting: https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/identification/dro_spec.rb#L1177

 Isn't it just trying to assert that whatever XML you start with (with encoding, etc.) , is what you end up with after going through cocina and back again?  Sorry if I'm confused, maybe easier to do in person .

2021-05-03 23:07 UTC, jcoyne commented
If you were to use a real ActiveFedora object (rather than a stub), you get the un-escaped value. Which would be the same as doing `Nokogiri::XML(xml).xpath('//objectLabel').first.content`

2021-05-04 19:06 UTC, ndushay requested changes
request for a var name change, o.w. looks good.

2021-05-04 19:06 UTC, ndushay commented on spec/services/cocina/mapping/identification/dro_spec.rb
> +      let(:escaped_label) { 'E&#x301;ve&#x301;nement du 19 fevrier 1790' }
what do you think about renaming this to `utf8_escaped_label` ?   "escaped" could be HTML, XML, UTF-8 ...

2021-05-04 19:06 UTC, ndushay commented on spec/services/cocina/mapping/identification/dro_spec.rb
> -            <objectLabel>E&amp;#x301;ve&amp;#x301;nement du 19 fevrier 1790</objectLabel>
I think we see the ? UTF-8 escaped ? characters in the lightbox in Argo;  Actual Fedora UI show them as NOT UTF-8 escaped:  https://sul-dor-prod.stanford.edu/fedora/objects/druid:bb016nw8128/datastreams/identityMetadata/content   but that is also a web browser view.   So no idea how they are in native Fedora.

equivalent-xml  and/or our code is set up to successfully match the string whether utf-8 escaped or not.

So ultimately, we will either find problems for this roundtripping actual data with the scripts or, this test, as it stands ... is fine???

As to your question:  Because there is a diff between Argo lightbox and Fedora UI display ... "exactly the same" may be tricky, and if we use the definition from equivalent-xml and our encoding settings, that may be sufficient.

2021-05-04 19:48 UTC, jcoyne commented on spec/services/cocina/mapping/identification/dro_spec.rb
> +      let(:escaped_label) { 'E&#x301;ve&#x301;nement du 19 fevrier 1790' }
I would say this is an `xml_escaped_label`  if this were just utf-8 bytes they would be `"\u0301"`

2021-05-04 20:16 UTC, ndushay commented on spec/services/cocina/mapping/identification/dro_spec.rb
> +      let(:escaped_label) { 'E&#x301;ve&#x301;nement du 19 fevrier 1790' }
ok, I'm good with xml_escaped_label :-)

2021-05-04 20:18 UTC, ndushay approved these changes

2021-05-04 20:36 UTC, merged