allow publish to continue but alert HB with data error for invalid license URL
sul-dlss/dor-services-app pull request #2873
Opened 2021-06-03 22:47 UTC by peetucket

## Why was this change made?

Fixes #2872 -- do not error out in the publish step when an invalid license URL is found and also provide the druid in the HB data error alert

## How was this change tested?

Existing tests

## Which documentation and/or configurations were updated?

2021-06-03 23:48 UTC, jcoyne requested changes

2021-06-03 23:48 UTC, jcoyne commented on app/services/publish/access_conditions.rb
> +      Honeybadger.notify("[DATA ERROR] #{license_url} is not a supported license in object #{pid}")
Can we put this in the Honeybadger context rather than the message? Then it won't be a new error each time.

2021-06-03 23:48 UTC, jcoyne commented on app/services/publish/access_conditions.rb
> +      license_url.present? && license.present?
Please add a test for this change.

2021-06-04 00:00 UTC, peetucket commented on app/services/publish/access_conditions.rb
> +      Honeybadger.notify("[DATA ERROR] #{license_url} is not a supported license in object #{pid}")
Yup, will do.

2021-06-04 00:01 UTC, peetucket commented on app/services/publish/access_conditions.rb
> +      license_url.present? && license.present?
Suggestions on where it should go?  It's not obvious to me.

2021-06-04 00:12 UTC, jcoyne commented on app/services/publish/access_conditions.rb
> +      license_url.present? && license.present?
spec/services/publish/public_desc_metadata_service_spec.rb is one place you could put it. Otherwise you could create a unit test for this class

2021-06-04 00:14 UTC, jcoyne commented on app/services/publish/access_conditions.rb
> +      Honeybadger.notify("[DATA ERROR] #{license_url} is not a supported license in object #{pid}")
I think we need a special trap here for the "none" license, because that is a valid value in SDR (for legacy ETDs), but we don't want to publish that to PURL.

2021-06-07 15:53 UTC, jcoyne requested changes

2021-06-07 15:53 UTC, jcoyne commented on spec/services/publish/access_conditions_spec.rb
> +    xit 'should alert HB on an unmapped license URL' do
Can you either complete these or remove them?  If you don't do it now, it's unlikely anyone will ever decide to do them later, and in the mean time they clutter up the test output.

2021-06-07 16:00 UTC, peetucket commented on spec/services/publish/access_conditions_spec.rb
> +    xit 'should alert HB on an unmapped license URL' do
these were just placeholders, I was intending to fill in these in now, just wanted to commit to github -- just have switched the PR to draft

2021-06-07 20:22 UTC, jcoyne requested changes

2021-06-07 20:22 UTC, jcoyne commented on app/services/publish/access_conditions.rb
> +                         context: { druid: pid })
What I was suggesting here was that we add `Honeybadger.context(druid: pid)` in `PublicDescMetadataService` and then we don't need to pass pid to this class.

2021-06-07 20:24 UTC, jcoyne commented on app/services/publish/access_conditions.rb
> +                         context: { druid: pid })
Putting it in PublishJob might even be better.  Then we have the druid for any error that can occur in that context.

2021-06-07 21:59 UTC, peetucket commented on app/services/publish/access_conditions.rb
> +                         context: { druid: pid })
Ahh, was not aware you could set the context earlier in the thread and have it added by HB later.  Changed.

2021-06-15 16:01 UTC, jcoyne requested changes
Is this still necessary? The DRUID on the ticket seems to already be accessioned: https://argo.stanford.edu/view/druid:dt303hw3940

2021-06-15 16:04 UTC, peetucket commented
This particular druid was manually remediated to allow it to proceed and not wait for this code, but I think its possible this particular license may still exist in other objects and would become a problem, hence the reason for making this code hcange.  Do you know @andrewjbtw ?

2021-06-22 17:46 UTC, peetucket commented
We do not think this is needed anymore based on the fact that we are now validating all new licenses being added and have remediated all existing licenses.

2021-06-22 17:46 UTC, closed without merging