Store DOI in identityMetadata and map it to Cocina
sul-dlss/dor-services-app pull request #2905
Opened 2021-07-08 19:12 UTC by jcoyne

Blocked by https://github.com/sul-dlss/cocina-models/pull/273

## Why was this change made?

## How was this change tested?

## Which documentation and/or configurations were updated?

2021-07-09 16:20 UTC, justinlittman requested changes
Does object_creator need to be changed as well?

2021-07-09 16:20 UTC, justinlittman commented on app/services/cocina/from_fedora/identification.rb
> +        value.text.delete_prefix('https://doi.org/')
How confident are we that these are the only DOI prefixes in existing data?

2021-07-09 16:20 UTC, justinlittman commented on app/services/cocina/from_fedora/identification.rb
> +          doi: doi,
Are there cases in which may have multiple DOIs?

2021-07-09 16:33 UTC, jcoyne commented on app/services/cocina/from_fedora/identification.rb
> +          doi: doi,
not that we support.  This will currently be coming from H2, so we have full control over all of this.

2021-07-09 16:34 UTC, jcoyne commented on app/services/cocina/from_fedora/identification.rb
> +        value.text.delete_prefix('https://doi.org/')
I don't know. I don't know how we could check.

2021-07-09 17:58 UTC, justinlittman commented on app/services/cocina/from_fedora/identification.rb
> +        value.text.delete_prefix('https://doi.org/')
I'll write a report.

2021-07-09 18:12 UTC, justinlittman commented on app/services/cocina/from_fedora/identification.rb
> +        value = fedora_object.identityMetadata.ng_xml.xpath('//identifier[type="doi"]').first
I suspect this should be `//identifier[@type="doi"]`.

Also, looking in the identity metadata specs I don't see `<identifier>`. Are you sure this is correct?

2021-07-09 18:14 UTC, justinlittman commented
Also, the mapping needs a spec in https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/identification/dro_identity_spec.rb

2021-07-09 19:02 UTC, jcoyne commented on app/services/cocina/from_fedora/identification.rb
> +        value = fedora_object.identityMetadata.ng_xml.xpath('//identifier[type="doi"]').first
ah, this is meant to be in descMetadata, not identityMetadata

2021-07-13 11:22 UTC, justinlittman approved these changes

2021-07-13 15:52 UTC, merged