implement event pub year first pass
sul-dlss/dor-services-app pull request #2949
Opened 2021-07-26 18:04 UTC by ndushay

## Why was this change made?

Implement algorithm to extract correct pub year from events for DataCite mapping

## How was this change tested?

unit tests adapted from Arcadia's tests

## Which documentation and/or configurations were updated?

2021-07-26 21:05 UTC, justinlittman requested changes
Note that some of the comments are intended as comments, not requested changes.

2021-07-26 21:05 UTC, justinlittman commented on app/services/cocina/to_datacite/event.rb
> +      def cocina_dro_access
This indirection isn't buying anything.

2021-07-26 21:05 UTC, justinlittman commented on app/services/cocina/to_datacite/event.rb
> +      attr :cocina_item, :cocina_events
I don't think `cocina_events` is an attr.

2021-07-26 21:05 UTC, justinlittman commented on app/services/cocina/to_datacite/event.rb
> +      def cocina_events
This is only used one placed. Is the indirection buying anything?

2021-07-26 23:44 UTC, ndushay commented on app/services/cocina/to_datacite/event.rb
> +        cocina_dro_access&.embargo&.releaseDate.presence
I think I ended up with `.presence` due to our rubocop masters.  I don't have strong feelings about it but every time I do a rubocop exception in this app, a certain individuals says "why did you do this"

2021-07-26 23:45 UTC, ndushay commented on app/services/cocina/to_datacite/event.rb
> +      def cocina_events
more code is in progress that uses it.  Much more to be implemented in this class.

2021-07-26 23:47 UTC, ndushay commented on app/services/cocina/to_datacite/event.rb
> +      attr :cocina_item, :cocina_events
you are correct;  fixing.

2021-07-26 23:50 UTC, ndushay commented on app/services/cocina/to_datacite/event.rb
> +      def cocina_dro_access
I disagree - it is used in 2 places and makes it clear we are not in `cocina_item.description.access` which also exists and is confusing.

2021-07-26 23:51 UTC, ndushay commented on app/services/cocina/to_datacite/event.rb
> +        cocina_dro_access&.embargo&.releaseDate.presence
presence is like `.present?` except it return the value if it is there, and returns nil if it isn't there.

2021-07-26 23:52 UTC, ndushay commented
@justinlittman I responded to all of your suggestions and took one of them.

2021-07-27 11:12 UTC, justinlittman approved these changes

2021-07-27 11:12 UTC, merged