datacite form mappings hardcoded as a stopgap
sul-dlss/dor-services-app pull request #2978
Opened 2021-08-03 22:02 UTC by ndushay

## Why was this change made?

To be able to debug `update_doi_metadata` endpoint and `UpdateDoiMetadataJob`

## How was this change tested?

created some H2 objects in stage.

## Which documentation and/or configurations were updated?

2021-08-03 22:20 UTC, jcoyne requested changes

2021-08-03 22:20 UTC, jcoyne commented on app/services/cocina/to_datacite/form.rb
> +          attribs[:resourceTypeGeneral] = resource_type_general || 'Text'
How about a check here that sends `Honeybadger.notify` if the default has to be used?

2021-08-03 22:24 UTC, ndushay commented on app/services/cocina/to_datacite/form.rb
> +          attribs[:resourceTypeGeneral] = resource_type_general || 'Text'
It will always have to be used until Arcadia does some updates -- the current code looks for resource_type  with DataCite as a source, and we have no way to represent that in MODS.

2021-08-04 15:48 UTC, jcoyne commented on app/services/cocina/to_datacite/form.rb
> +          attribs[:resourceTypeGeneral] = resource_type_general || 'Text'
I think I'm okay with it having to be ripped out later, but I don't want to merge code that we know is producing bad data without some kind of pain for us that will get us to change it later.

2021-08-04 18:59 UTC, ndushay commented
@jcoyne added Honeybadger notification.

2021-08-04 22:10 UTC, jcoyne approved these changes

2021-08-04 23:12 UTC, merged