Add warnings when in an infinite loop
sul-dlss/dor-services-app pull request #2984
Opened 2021-08-06 17:26 UTC by jcoyne

## Why was this change made?

To point people who are debugging to the right place in the code.

## How was this change tested?

## Which documentation and/or configurations were updated?

2021-08-12 16:46 UTC, jmartin-sul requested changes
i think one of the logging statements might reference an unavailable variable

2021-08-12 16:46 UTC, jmartin-sul commented on app/services/administrative_tags.rb
> +    Rails.logger.warn("Possible race condition updating tags: #{tags}.  This should only happen one time, otherwise this might be an error")
apologies if i'm missing something, but is there actually a var called `tags` in scope here?

2021-08-12 16:46 UTC, jmartin-sul commented on app/services/administrative_tags.rb
> +    Rails.logger.warn("Possible race condition updating tags: #{tags}.  This should only happen one time, otherwise this might be an error")
i see it as a param to the method in the other added logging statement

2021-08-12 17:21 UTC, jcoyne commented on app/services/administrative_tags.rb
> +    Rails.logger.warn("Possible race condition updating tags: #{tags}.  This should only happen one time, otherwise this might be an error")
Good catch, should be `new`

2021-09-15 19:37 UTC, jcoyne commented
Superseded by #3048

2021-09-15 19:37 UTC, closed without merging