Removes data attribute from resource node (content metadata).
sul-dlss/dor-services-app pull request #3209
Opened 2022-01-22 02:00 UTC by justinlittman

closes #3084

## Why was this change made?
Normalization

## How was this change tested?
Unit

## Which documentation and/or configurations were updated?

2022-01-22 03:13 UTC, justinlittman commented
Before:
```
Status (n=100000; not using Missing for success/different/error stats):
  Success:   94844 (94.922%)
  Different: 5074 (5.078%)
  Mapping error:     0 (0.0%)
  Create error:     0 (0.0%)
  Normalization error:     0 (0.0%)
  Missing from cache:     0 (0.0%)
  Unmapped:     0 (0.0%)
  Expected unmapped:     82 (0.082%)
  Bad cache:     0 (0.0%)
```

After:
```
Status (n=100000; not using Missing for success/different/error stats):
  Success:   94844 (94.922%)
  Different: 5074 (5.078%)
  Mapping error:     0 (0.0%)
  Create error:     0 (0.0%)
  Normalization error:     0 (0.0%)
  Missing from cache:     0 (0.0%)
  Unmapped:     0 (0.0%)
  Expected unmapped:     82 (0.082%)
  Bad cache:     0 (0.0%)
```

2022-01-25 19:46 UTC, ndushay requested changes
it would be good to provide a druid for the spec, especially since the run against 100,000 objects has no occurrences ...

2022-01-25 19:46 UTC, ndushay commented on spec/services/cocina/normalizers/content_metadata_normalizer_spec.rb
> +    it 'removes data and id attributes' do
id attributes?   And what is that after the closing tag of `</contentMetadata>` ?

2022-01-25 22:58 UTC, justinlittman commented
druid:zn580kw6428 is an example of this.

2022-01-25 22:59 UTC, justinlittman commented on spec/services/cocina/normalizers/content_metadata_normalizer_spec.rb
> +    it 'removes data and id attributes' do
Thanks. Fixed.

2022-01-25 23:03 UTC, ndushay approved these changes

2022-01-25 23:04 UTC, ndushay commented
merge when green (currently failing)

2022-01-25 23:14 UTC, merged