add normalizer for adminMetadata
sul-dlss/dor-services-app pull request #3231
Opened 2022-01-25 22:50 UTC by peetucket

## Why was this change made?

Fixes #2707 - admin administrativeMetadata normalizer, add a spec for the new normalizer, run normalizer in validation script and in adminMetadata spec

## How was this change tested?

Test suite

## Which documentation and/or configurations were updated?

2022-01-25 22:50 UTC, peetucket commented on spec/services/cocina/mapping/administrative/apo_administrative_spec.rb
Please verify the running of the normalizer was added to this spec correctly.

2022-01-26 12:42 UTC, justinlittman requested changes

2022-01-26 12:42 UTC, justinlittman commented on bin/validate-cocina-roundtrip
> +  when 'administrativeMetadata'
Can you test this on sdr-deploy?

2022-01-26 18:18 UTC, peetucket commented
Running against just APOs on main branch:

```
bin/validate-cocina-roundtrip -i druids.apos.txt
Status (n=1270; not using Missing for success/different/error stats):
  Success:   13 (1.024%)
  Different: 1257 (98.976%)
  Mapping error:     0 (0.0%)
  Create error:     0 (0.0%)
  Normalization error:     0 (0.0%)
  Missing from cache:     0 (0.0%)
  Unmapped:     0 (0.0%)
  Expected unmapped:     0 (0.0%)
  Bad cache:     0 (0.0%)
```

Running against just APOs on this PR:

```
bin/validate-cocina-roundtrip -i druids.apos.txt
Status (n=1270; not using Missing for success/different/error stats):
  Success:   77 (6.063%)
  Different: 1177 (92.677%)
  Mapping error:     16 (1.26%)
  Create error:     0 (0.0%)
  Normalization error:     0 (0.0%)
  Missing from cache:     0 (0.0%)
  Unmapped:     0 (0.0%)
  Expected unmapped:     0 (0.0%)
  Bad cache:     0 (0.0%)
```

2022-01-26 20:38 UTC, ndushay approved these changes
LGTM; approving.  But I think JLitt should sign off.

2022-01-26 20:50 UTC, justinlittman approved these changes

2022-01-26 20:50 UTC, merged