Cocina-ize the AdminPolicyDefaultsController
sul-dlss/dor-services-app pull request #3250
Opened 2022-01-27 17:38 UTC by mjgiarlo

## Why was this change made?

Fixes #3168

This commit changes the AdminPolicyDefaultsController so that it saves and loads Cocina objects instead of Fedora ones. It tests both cases of default defaultAccess and custom defaultAccess. It also copies over an RSpec matcher from Argo allowing comparison of Cocina substructures, in this case the access substructure.

## How was this change tested?

CI. We should test this in QA as well if @andrewjbtw has some time.

## Which documentation and/or configurations were updated?

None

2022-01-27 17:53 UTC, justinlittman requested changes

2022-01-27 17:53 UTC, justinlittman commented on spec/requests/apply_admin_policy_defaults_spec.rb
> +    allow(Dor).to receive(:find).with(object_pid).and_return(object)
I would expect the spec to not have Fedora in it. Should you be mocking `CocinaObjectStore.find` instead?

2022-01-27 18:02 UTC, mjgiarlo commented on spec/requests/apply_admin_policy_defaults_spec.rb
> +    allow(Dor).to receive(:find).with(object_pid).and_return(object)
@justinlittman I changed the stubs to use `CocinaObjectStore.fedora_find`.

2022-01-28 12:23 UTC, justinlittman requested changes

2022-01-28 12:23 UTC, justinlittman commented on spec/requests/apply_admin_policy_defaults_spec.rb
> +  let(:object) do
I still think this test should be entirely abstracted from Fedora. Ping me and let's discuss.

2022-01-28 16:13 UTC, mjgiarlo commented on spec/requests/apply_admin_policy_defaults_spec.rb
> +  let(:object) do
@justinlittman Oh, no worries, I can do that. No discussion needed on my part.

I was hesitant to start off with a pure unit test, mostly because I hadn't been in DSA for a long time and had low confidence that I could put a bunch of mocks and stubs in and feel good that the changes I made would work as intended in a deployed environment. So even if we back out those bits, they were a valuable demonstration to me that things are wired up right.

2022-01-28 20:07 UTC, justinlittman submitted a review, later dismissed

2022-01-31 22:07 UTC, mjgiarlo commented
TO-DO:

* UI reports “defaults applied” even when not applied;
* Files should have rights of “Stanford,Stanford” but ended up with “dark,none” (for test item: https://argo-stage.stanford.edu/view/druid:bf345my0487)

2022-02-01 01:29 UTC, jcoyne commented on app/controllers/admin_policy_defaults_controller.rb
> +    return error_response unless current_workflow_state.in?(ALLOWED_WORKFLOW_STATES)
Does Argo already do this check?

2022-02-01 16:17 UTC, mjgiarlo commented on app/controllers/admin_policy_defaults_controller.rb
> +    return error_response unless current_workflow_state.in?(ALLOWED_WORKFLOW_STATES)
@jcoyne Not that I saw, anyway.

2022-02-02 19:08 UTC, mjgiarlo commented on app/controllers/admin_policy_defaults_controller.rb
> +# TODO: This controller is doing way too much now. Consider extracting most of what is below into a new service object.
Dear reviewer(s): take note! I am inclined to take up this refactoring after this PR is merged, ideally.

2022-02-02 19:08 UTC, mjgiarlo commented on app/controllers/admin_policy_defaults_controller.rb
> +  }.freeze
It would be lovely to only have one place in DSA to validate/map rights, and I can investigate that possibility in the refactoring PR.

2022-02-02 19:08 UTC, mjgiarlo commented on app/controllers/admin_policy_defaults_controller.rb
> +    return workflow_error_response unless current_workflow_state.in?(ALLOWED_WORKFLOW_STATES)
@andrewjbtw confirmed this is the right behavior.

2022-02-02 19:09 UTC, mjgiarlo commented on app/services/workflow_client_factory.rb
> +               )
Unrelated to the issue I'm working on, but it's tiny and could nuke an HB alert we've been seeing forever. 🤷🏻‍♂️

2022-02-02 19:10 UTC, mjgiarlo commented on config/application.rb
> +        query_hash_key: 'rack.request.query_hash',
Nukes a deprecation warning in the test suite. Has no effect on production apps.

2022-02-02 19:11 UTC, mjgiarlo commented on spec/support/cocina_matchers.rb
> +  end
I wonder if the cocina-models should ship with this matcher? But maybe a thing for later.

2022-02-02 20:45 UTC, justinlittman approved these changes

2022-02-02 20:45 UTC, merged