We currently use the objectId in ThumbnailService over resourceId
sul-dlss/dor-services-app pull request #3261
Opened 2022-01-28 21:34 UTC by aaron-collier

## Why was this change made?

This should be reviewed by @andrewjbtw, @arcadiafalcone, @jcoyne, and @justinlittman to verify that this small change is ok.

When working in ThumbnailService, I noticed we expect the objectId (that includes a druid) to be used instead of resourceId which does not.

https://github.com/sul-dlss/dor-services-app/blob/main/app/services/thumbnail_service.rb#L50

For example, with content metadata of:

```
<contentMetadata objectId="tf960jc7725" type="image">
  <resource id="tf960jc7725_1" sequence="1" type="image">
    <externalFile fileId="2576001.jp2" mimetype="image/jp2" objectId="druid:pj563wy4429" resourceId="pj563wy4429_1"/>
    <relationship objectId="druid:pj563wy4429" type="alsoAvailableAs"/>
  </resource>
  <resource id="tf960jc7725_2" sequence="2" type="image">
    <externalFile fileId="2576002.jp2" mimetype="image/jp2" objectId="druid:jv233bw7647" resourceId="jv233bw7647_1"/>
    <relationship objectId="druid:jv233bw7647" type="alsoAvailableAs"/>
  </resource>
</contentMetadata>
```

we currently map as:
```
pj563wy4429_1/2576001.jp2
jv233bw7647_1/2576002.jp2
```

However, ThumbnailService expects:
```
druid:pj563wy4429/2576001.jp2
druid:jv233bw7647/2576002.jp2
```

If this was a design decision that I can ignore, please close. 

## How was this change tested?

Unit.

## Which documentation and/or configurations were updated?

2022-01-31 17:11 UTC, justinlittman commented
I don't know anything about the intent / design.

2022-01-31 17:15 UTC, jcoyne requested changes

2022-01-31 17:15 UTC, jcoyne commented on app/services/cocina/from_fedora/dro_structural.rb
> +          "#{resource_node['objectId']}/#{resource_node['fileId']}"
This was expected to be the resource id, not the object id filename.

2022-02-01 01:28 UTC, aaron-collier commented on app/services/cocina/from_fedora/dro_structural.rb
> +          "#{resource_node['objectId']}/#{resource_node['fileId']}"
Are we sure the `pj563wy4429_1/filename.jp2` works? From what I can tell in existing tests the `_1` is not included, but happy to ditch this if it's not needed.

2022-05-05 16:57 UTC, closed without merging