[DRAFT] Cocina-ize ThumbnailService
sul-dlss/dor-services-app pull request #3264
Opened 2022-01-29 00:01 UTC by aaron-collier

## Why was this change made?

Closes #3253 

## How was this change tested?

Updated unit tests

## Which documentation and/or configurations were updated?

2022-01-31 17:20 UTC, jcoyne commented on app/services/thumbnail_service.rb
> +        # if we find one, return the filename based on whether it is a local file or external file
How is this supporting local files?

2022-01-31 22:02 UTC, aaron-collier commented on app/services/thumbnail_service.rb
> +        # if we find one, return the filename based on whether it is a local file or external file
Yeah probably, it was an older comment.

2022-01-31 23:44 UTC, jcoyne requested changes

2022-01-31 23:44 UTC, jcoyne commented on app/models/dor/update_marc_record_service.rb
> +      return unless @druid_obj
Why is this check necessary?

2022-01-31 23:44 UTC, jcoyne commented on app/models/dor/update_marc_record_service.rb
> +      cocina_object = CocinaObjectStore.find(@druid_obj.pid)
Is it necessary to do this find if `@thumb` is already defined?

2022-01-31 23:44 UTC, jcoyne commented on app/services/publish/public_xml_service.rb
> +      cocina_object = CocinaObjectStore.find(object.pid)
would this cause an extra load?  Is it possible to do dependency injection with the ThumbnailService instance when instantiating PublicXMLService to avoid that?

2022-01-31 23:44 UTC, jcoyne commented on app/services/thumbnail_service.rb
> +    return unless object.respond_to?(:structural) && object.structural.present?
Why is `present?` necessary here?

2022-01-31 23:44 UTC, jcoyne commented on app/services/thumbnail_service.rb
> +    object.structural.contains.each do |attachment|
Please use `file_set` rather than `attachment` here, as it is an instance of `Cocina::FileSet`

2022-01-31 23:44 UTC, jcoyne commented on app/services/thumbnail_service.rb
> +      next unless attachment.respond_to?(:structural) && attachment.structural.present?
Is there a case where FileSet would not respond to structural? is `present?` necessary?

2022-02-01 00:34 UTC, aaron-collier commented on app/services/thumbnail_service.rb
> +      next unless attachment.respond_to?(:structural) && attachment.structural.present?
perhaps mostly being extra cautious... happy to remove any unnecessary checks.

2022-02-01 00:35 UTC, aaron-collier commented on app/models/dor/update_marc_record_service.rb
> +      return unless @druid_obj
It may not be. I recall in one test that it was `nil` but that could have been related to something else. I'll try without.

2022-02-01 00:35 UTC, aaron-collier commented on app/services/thumbnail_service.rb
> +    return unless object.respond_to?(:structural) && object.structural.present?
Probably not, following the existing pattern, which is likely over cautious now.

2022-02-01 00:40 UTC, aaron-collier commented on app/models/dor/update_marc_record_service.rb
> +      cocina_object = CocinaObjectStore.find(@druid_obj.pid)
@jcoyne I'm not sure I'm following. In this case, we're starting with a `Dor::Item` and need to pass a `Cocina::Model` to the ThumbnailService.

2022-02-01 00:49 UTC, aaron-collier commented on app/services/publish/public_xml_service.rb
> +      cocina_object = CocinaObjectStore.find(object.pid)
This is somewhat temporary as once PublicXmlService is rewritten for cocina we won't need this. I'd be happy to pair through dependency injection if you think that's the write path forward, but I'm not grokking how it may help in this case.

2022-02-01 00:52 UTC, aaron-collier commented on app/services/thumbnail_service.rb
> +    return unless object.respond_to?(:structural) && object.structural.present?
I get a load of failures without it. I'll think through a bit of a refactor to improve this though.

2022-02-01 01:09 UTC, aaron-collier commented on app/services/thumbnail_service.rb
> +    return unless object.respond_to?(:structural) && object.structural.present?
I suspect both of these checks are required. If a `Cocina::Models::Collection` is passed in, the model does not include `structural`, so a check for `present?` will fail. But also, if a DRO is passed in that has does not include `structural` in its data (as it's not required) then the loop over `contains` fails. I'm happy to suggestions and pair though if I'm missing anything.

2022-02-01 13:41 UTC, jcoyne commented on app/models/dor/update_marc_record_service.rb
> +      cocina_object = CocinaObjectStore.find(@druid_obj.pid)
How about refactoring this class so that it's initializer takes both a Dor::Item and an instace of ThumbnailService (depenency injection).  Then the class doesn't need to know how to find a cocina object.

2022-02-01 13:41 UTC, jcoyne commented on app/services/publish/public_xml_service.rb
> +      cocina_object = CocinaObjectStore.find(object.pid)
Sounds good, lets pair together this morning.

2022-02-01 13:45 UTC, jcoyne commented on app/services/thumbnail_service.rb
> +    return unless object.respond_to?(:structural) && object.structural.present?
The existing pattern is looking for nil or an empty string. The new model makes an empty string impossible. 
I'm pretty sure `return unless object.respond_to?(:structural) && object.structural` would be sufficient, right?

2022-02-01 16:17 UTC, aaron-collier commented on app/services/thumbnail_service.rb
> +    return unless object.respond_to?(:structural) && object.structural.present?
Ah, yeah - that is correct. :+1:

2022-02-01 17:22 UTC, jcoyne approved these changes
Looks great! Thanks for the changes.

2022-02-01 17:22 UTC, merged

2022-02-08 23:37 UTC, mjgiarlo commented on app/services/thumbnail_service.rb
> +    object.structural.hasMemberOrders.first.members.first
Now that I'm touching member orders as part of cocinization of virtual objects, I'm wondering how we know the first member of the first member order is the thumb. @aaron-collier @jcoyne @justinlittman

2023-03-23 16:39 UTC, mjgiarlo commented on app/services/thumbnail_service.rb
> +    object.structural.hasMemberOrders.first.members.first
@andrewjbtw this looks like the source of the bug in #4456 which suggests it's been out there for a yearish 😬

2023-03-23 21:09 UTC, andrewjbtw commented on app/services/thumbnail_service.rb
> +    object.structural.hasMemberOrders.first.members.first
Hmm. I think this only affects places where a thumbnail appears in SW (not many), and not the virtual object functionality itself, which might be how we haven't heard any reports. I feel like it's taken me the year since the migration to fully understand all the possibilities in an 856.