Add Cocina ActiveRecord models.
sul-dlss/dor-services-app pull request #3273
Opened 2022-02-01 14:20 UTC by justinlittman

closes #3138

## Why was this change made?
~~Fedora~~

## How was this change tested?
Unit

## Which documentation and/or configurations were updated?

2022-02-01 15:13 UTC, jcoyne requested changes

2022-02-01 15:13 UTC, jcoyne commented on db/migrate/20220131194912_create_collection.rb
> +      t.string :content_type, null: false
Why is content_type necessary for collections? Isn't this constant?  If not, can this be changed to collection_type as content_type is an attribute that has specific meaning in sdr.

2022-02-01 15:13 UTC, jcoyne commented on spec/factories/admin_policies.rb
> +    cocina_version { '0.0.1' }
Should this be Cocina::Models::VERSION?

2022-02-01 15:13 UTC, jcoyne commented on spec/factories/collections.rb
> +    cocina_version { '0.0.1' }
Cocina::Models::VERSION?

2022-02-01 15:13 UTC, jcoyne commented on spec/factories/dros.rb
> +    cocina_version { '0.0.1' }
Cocina::Models::VERSION?

2022-02-01 16:19 UTC, justinlittman commented on db/migrate/20220131194912_create_collection.rb
> +      t.string :content_type, null: false
Not a constant: https://github.com/sul-dlss/cocina-models/blob/main/openapi.yml#L394-L399

I will rename to `collection_type`.

2022-02-01 16:22 UTC, justinlittman commented on spec/factories/admin_policies.rb
> +    cocina_version { '0.0.1' }
Could be, but doesn't have to be.

My general strategy for test fixtures is to use `Cocina::Models::VERSION` when the version matters and `0.0.1` when it doesn't. However, if you feel strongly happy to change in these tests.

2022-02-02 16:45 UTC, jcoyne approved these changes

2022-02-02 16:46 UTC, justinlittman commented on app/models/admin_policy.rb
> +      type: Cocina::Models::Vocab.adminPolicy,
Fixing.

2022-02-02 16:49 UTC, merged