[HOLD] Cocina-izes VersionService. Stores version data in db.
sul-dlss/dor-services-app pull request #3311
Opened 2022-02-04 22:04 UTC by justinlittman

closes #3170

## Why was this change made?
Version metadata is being moved from the version datastream to the DB.

## How was this change tested?
Unit

## Which documentation and/or configurations were updated?

2022-02-05 00:25 UTC, jcoyne commented on app/controllers/versions_controller.rb
> +    # This can be removed after migration.
Do we need to keep a list of what has and what hasn't migrated?

2022-02-07 12:06 UTC, justinlittman commented on app/controllers/versions_controller.rb
> +    # This can be removed after migration.
My thought was to create an Uber Migration job that would migrate versions, events, and persist to cocina and then invoke that for every object. So I don't think there is a need for a separate tracking mechanism for versions.

2022-02-07 23:07 UTC, jcoyne commented
Holding until when?

2022-02-10 01:21 UTC, justinlittman commented
Testing completed, so ready for review / merge.

2022-02-10 03:39 UTC, jcoyne requested changes

2022-02-10 03:39 UTC, jcoyne commented on spec/requests/authorization_spec.rb
> +  let(:cocina_object) { instance_double(Cocina::Models::DRO, version: '5') }
Version should be an integer. https://github.com/sul-dlss/cocina-models/blob/main/openapi.yml#L197-L198

2022-02-10 03:48 UTC, jcoyne requested changes
Shouldn't this line have been updated too? https://github.com/sul-dlss/dor-services-app/blob/main/app/services/embargo_release_service.rb#L43

2022-02-10 12:50 UTC, justinlittman commented
@jcoyne Yes, changes are needed to EmbargoReleaseService. In fact, I made them. And then I forgot to hit save in the editor. That showed up here as well: https://app.honeybadger.io/projects/50568/faults/83969890

2022-02-10 14:08 UTC, jcoyne approved these changes

2022-02-10 14:08 UTC, merged