[HOLD] add objectLabel node with value from fedora object if not in datastream
sul-dlss/dor-services-app pull request #3365
Opened 2022-02-08 22:52 UTC by peetucket

## Why was this change made?

Fixes #3320 - if missing when normalizing, add objectLabel to identityMetadata using value pulled from fedora object

## How was this change tested?

- Added new unit tests
- Pending roundtrip validation on server

## Which documentation and/or configurations were updated?

2022-02-08 23:08 UTC, peetucket commented
Running on this PR:

```
bin/validate-cocina-roundtrip -s 100000 -i druids.testbed.txt -f

```

Running on main:

```
bin/validate-cocina-roundtrip -s 100000 -i druids.testbed.txt -f

```

2022-02-08 23:08 UTC, peetucket commented on bin/validate-cocina-roundtrip
>    when 'embargoMetadata'
fetch the label from the MetadataService and pass to normalizer so we can use if needed

2022-02-08 23:09 UTC, peetucket commented on app/services/cocina/normalizers/identity_normalizer.rb
>        end
we need this label passed in since it comes from the fedora object, which we do not have access to inside the normalizer

2022-02-09 00:12 UTC, ndushay commented
I think the problem has to do with https://github.com/sul-dlss/dor-services-app/blob/main/app/services/cocina/to_fedora/identity.rb#L40-L44 -- this method is called for `object_updater` and in `object_creator` and would overwrite the existing label, right?

![image](https://user-images.githubusercontent.com/96775/153097156-a9cae511-123f-4836-9efc-b0d30aa2703f.png)

2022-02-09 01:56 UTC, justinlittman commented on bin/validate-cocina-roundtrip
> +    Cocina::Normalizers::IdentityNormalizer.normalize(identity_ng_xml: orig_datastream_ng_xml, label: MetadataService.label_from_mods(fedora_obj.descMetadata.ng_xml))
Why not just use the label that is passed into norm_orig_datastream_ng_xml_for method?

2022-02-09 02:01 UTC, justinlittman commented
@ndushay This ticket is about normalizing when the original identity metadata is missing an objectLabel.

However, unless I'm misunderstanding the existing code is correct in overwriting the existing label.

2022-02-09 04:44 UTC, peetucket commented on bin/validate-cocina-roundtrip
> +    Cocina::Normalizers::IdentityNormalizer.normalize(identity_ng_xml: orig_datastream_ng_xml, label: MetadataService.label_from_mods(fedora_obj.descMetadata.ng_xml))
ahh, missed that it was available here, will use that instead

2022-02-09 05:50 UTC, peetucket commented
roundtrip tests updated - now basically identical (1 better in the PR)

2022-02-09 17:55 UTC, peetucket commented
Example from ticket (druid:ck375kx3685) succeeds on PR but fails on main.

2022-02-09 18:21 UTC, ndushay commented
I think this spec should be changed:

https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/identification/dro_identity_spec.rb#L745

and maybe some others???

2022-02-09 18:22 UTC, ndushay requested changes
I found 3 specs where we're mocking the normalized identityMetadata and it would be awesome if all such specs were corrected to match this change.  :-P

2022-02-09 18:51 UTC, peetucket commented
> I found 3 specs where we're mocking the normalized identityMetadata and it would be awesome if all such specs were corrected to match this change. :-P

What changes would you suggest?  The new normalization code does not do anything about blank labels (though perhaps it should ... but was not in the original specification).  These particular specs you mention appear to simply have incoming blank labels in the mocked data, which are then preserved through the roundtrip, as expected.  The new specs I added in the PR confirm the new changes in the code.

2022-02-09 19:02 UTC, ndushay approved these changes
oh duh.  I don't know why I keep confusing myself over all this stuff.  (Maybe it's ... confusing?)

2022-02-09 19:03 UTC, merged