Cocinize virtual object creation
sul-dlss/dor-services-app pull request #3379
Opened 2022-02-09 22:01 UTC by mjgiarlo

Fixes #3331
Fixes #3177

## Why was this change made?

This commit Cocinizes the major components involved in virtual object creation.
It includes the following:

* Convert from Fedora to Cocina:
  * `ConstituentService` (but for the `VersionService` interactions)
  * `ItemQueryService`
  * `ResetContentMetadataService`
* Rename parents and children to virtual objects and constituents (requested by @andrewjbtw)

## How was this change tested?

CI, will also be tested via integration test and in a deployed environment

## Which documentation and/or configurations were updated?

None

2022-02-10 17:31 UTC, jcoyne commented on app/services/constituent_service.rb
> +    @virtual_object ||= ItemQueryService.find_combinable_item(virtual_object_druid)
Do you know why it is showing this isn't covered?

2022-02-10 17:37 UTC, mjgiarlo commented on app/services/constituent_service.rb
> +    @virtual_object ||= ItemQueryService.find_combinable_item(virtual_object_druid)
Because `virtual_object` is only used in calls to collaborators, all of which have been stubbed in the unit tests for this class. All of the collaborators do have their own unit tests, including for this method. I'm hoping to use integration tests to ensure we're not outsmarting ourselves with stubs.

2022-02-10 18:07 UTC, jcoyne requested changes

2022-02-10 18:07 UTC, jcoyne commented on spec/services/constituent_service_spec.rb
> +      allow(service).to receive(:virtual_object)
Can you replace this with `allow(ItemQueryService).to receive(:find_combinable_item)`?

2022-02-11 12:11 UTC, justinlittman commented on app/services/constituent_service.rb
> +    # NOTE: virtual object is saved as part of closing the version
Actually, I don't think it is.

2022-02-11 12:11 UTC, justinlittman commented on app/services/constituent_service.rb
> -    child.add_relationship :is_constituent_of, parent
This is a problem. We don't have any way to represent this in Cocina and it is not clear if/where this relationship is used.

2022-02-11 13:53 UTC, jcoyne commented on app/services/constituent_service.rb
> -    child.add_relationship :is_constituent_of, parent
I don't think this is used by anything in the access systems.  They index off the MODS:
```xml
<relatedItem type="host" displayLabel="Appears in">
<titleInfo>
<title>Faculty Senate Session 30</title>
</titleInfo>
<location>
<url>http://purl.stanford.edu/fw628pk2797</url>
</location>
</relatedItem>
```

2022-02-11 16:16 UTC, mjgiarlo commented on app/services/constituent_service.rb
> -    child.add_relationship :is_constituent_of, parent
@jcoyne Unfortunately, this is used by Access systems. Example PURL: https://purl.stanford.edu/kq126jw7402 and search for "Appears in"

That display is driven by the following in public XML:

```xml
<relatedItem type="host" displayLabel="Appears in">
<titleInfo>
<title>The Cyclers' Guide and Road Book of California Containing Map of California in relief with principal Roads, Seven Sectional Maps showing all available Roads for Cyclers from Chico to San Diego, and a Map of Golden Gate Park. 1896. Price, One Dollar. Compiled and Published by Geo. W. Blum, 330 Pine St., S.F. Edward Denny & Co., Agents. (on verso) Copyrighted 1895 By Geo. W. Blum, San Francisco, Cal</title>
</titleInfo>
<location>
<url>http://purl.stanford.edu/cp799hh4428</url>
</location>
</relatedItem>
```

That currently is generated from RELS-EXT, which you can see here: https://github.com/sul-dlss/dor-services-app/blob/5ea36f697c7b0ecc0a86a8e9091047a0e29ac4e6/app/services/publish/public_desc_metadata_service.rb#L62-L90

So we do need a way to model the virtual object relationship on both the virtual object *and* constituents, it turns out. HT to @andrewjbtw.

2022-02-11 20:28 UTC, mjgiarlo commented on app/services/constituent_service.rb
> -    child.add_relationship :is_constituent_of, parent
Discussed with @jcoyne and @justinlittman and we're going to handle this on the indexing side, not in this PR.

2022-02-11 20:38 UTC, mjgiarlo commented
# TO-DO

- [ ] ConstituentService should save after versioning
- [ ] Validate that all constituents are DROs
- [ ] Validate that the constituent isn't also the virtual object
- [ ] Validate that no constituents are themselves already virtual objects

2022-02-15 19:04 UTC, mjgiarlo commented
# TO-DO

- [ ] Figure out why member orders aren't coming through even if they're in the request
- [ ] Re-publish constituent objects so their public XML includes the constituent relationship
  - [ ] If constituent object has a catkey, run the releaseWF (check what this does first)

2022-02-17 01:03 UTC, mjgiarlo commented on app/services/cocina/object_updater.rb
> +      if cocina_object.structural&.contains.present? || cocina_object.structural&.hasMemberOrders&.first&.members&.present?
@jcoyne @justinlittman I'm not sure if this is the right change here but the tests still pass and the virtobj integration test passes now FWIW. I'd like to hear what y'all have to say. Otherwise, pending one successful test by @andrewjbtw in QA, I think this is about ready for final review.

2022-02-17 01:54 UTC, justinlittman commented on app/services/cocina/object_updater.rb
> +      if cocina_object.structural&.contains.present? || cocina_object.structural&.hasMemberOrders&.first&.members&.present?
Seems right to me. Can you update the comment (L143)?

2022-02-17 02:51 UTC, mjgiarlo commented on app/services/cocina/object_updater.rb
> +      if cocina_object.structural&.contains.present? || cocina_object.structural&.hasMemberOrders&.first&.members&.present?
@justinlittman You bet. Done and ready for another look.

2022-02-18 23:18 UTC, mjgiarlo commented on app/services/cocina/object_updater.rb
> +          druid: fedora_object.pid,
Good call.

2022-02-18 23:19 UTC, mjgiarlo commented on app/services/reset_content_metadata_service.rb
> +  def self.reset(item:, constituent_druids: [])
@justinlittman how about I rename to `cocina_item`, since this must always be a DRO/item?

2022-02-18 23:25 UTC, mjgiarlo commented on app/services/reset_content_metadata_service.rb
> +    Honeybadger.notify("[DATA ERROR] item #{item.externalIdentifier} has multiple member orders")
Will do.

2022-02-18 23:25 UTC, mjgiarlo commented on app/services/reset_content_metadata_service.rb
> +  def self.reset(item:, constituent_druids: [])
done

2022-02-25 00:52 UTC, mjgiarlo commented
Unholding per conversation with @andrewjbtw

2022-02-25 01:31 UTC, jcoyne requested changes

2022-02-25 01:31 UTC, jcoyne commented on .rubocop_todo.yml
> +    - 'spec/services/publish/metadata_transfer_service_spec.rb'
why are these changes in this PR? You aren't touching this file.

2022-02-25 01:31 UTC, jcoyne commented on app/services/constituent_service.rb
> +      next unless cocina_item.identification&.catalogLinks&.find { |link| link.catalog == 'symphony' }
Would this be more clear if you used `.any?` rather than find?

2022-02-25 01:31 UTC, jcoyne commented on .rubocop_todo.yml
> +  Max: 13
Can this change be kept separate.  I really appreciate having the inline comments that flag where the complexity is too high.  I think that 12 is pretty good and if we're pushing above this, then reviewers deserve to have a look at the flagged method.

The auto-correction removes these comments that we've added to flag these trouble spots.

2022-02-25 16:38 UTC, mjgiarlo commented on app/services/constituent_service.rb
> +      next unless cocina_item.identification&.catalogLinks&.find { |link| link.catalog == 'symphony' }
Yep, I think so. Made the change.

2022-02-25 16:38 UTC, mjgiarlo commented on .rubocop_todo.yml
> +  Max: 13
Done.

2022-02-25 16:38 UTC, mjgiarlo commented on .rubocop_todo.yml
> +    - 'spec/services/publish/metadata_transfer_service_spec.rb'
Removed

2022-02-25 16:39 UTC, mjgiarlo commented
@jcoyne Made the changes you asked about. Review again pls?

2022-02-25 17:28 UTC, jcoyne approved these changes

2022-02-25 17:31 UTC, merged