Rewrite ApoExistenceValidator for cocina objects
sul-dlss/dor-services-app pull request #3380
Opened 2022-02-09 22:31 UTC by aaron-collier

## Why was this change made?

Fixes #3306 by using CocinaObjectStore to verify the existence of an APO

## How was this change tested?

Update unit tests

## Which documentation and/or configurations were updated?

2022-02-09 22:38 UTC, jcoyne requested changes

2022-02-09 22:38 UTC, jcoyne commented on spec/requests/create_collection_spec.rb
>      allow(Dor).to receive(:find).and_return(apo)
Can you remove this one?

2022-02-09 22:38 UTC, jcoyne commented on spec/requests/create_object_spec.rb
>      allow(Dor).to receive(:find).and_return(apo)
Can you remove this one.

2022-02-09 22:38 UTC, jcoyne commented on spec/requests/update_metadata_spec.rb
>      allow(Dor).to receive(:find).with(apo_druid).and_return(apo)
remove?

2022-02-09 22:38 UTC, jcoyne commented on spec/requests/update_metadata_spec.rb
>    let(:apo) { Dor::AdminPolicyObject.new(pid: apo_druid) }
remove this?

2022-02-09 22:38 UTC, jcoyne commented on spec/requests/create_object_spec.rb
>    let(:apo) { Dor::AdminPolicyObject.new(pid: 'druid:dd999df4567') }
Can this be removed?

2022-02-09 22:38 UTC, jcoyne commented on spec/requests/create_collection_spec.rb
>    let(:apo) { Dor::AdminPolicyObject.new(pid: 'druid:dd999df4567') }
Can this be removed?

2022-02-10 00:15 UTC, aaron-collier commented
@jcoyne I believe I've addressed your comments.

2022-02-10 01:16 UTC, jcoyne approved these changes

2022-02-10 01:16 UTC, merged