Create public contentMetadata from Cocina models
sul-dlss/dor-services-app pull request #3407
Opened 2022-02-10 21:44 UTC by jcoyne

## Why was this change made?
Fixes #3329

## How was this change tested?

## Which documentation and/or configurations were updated?

2022-02-14 15:04 UTC, justinlittman requested changes

2022-02-14 15:04 UTC, justinlittman commented on app/services/cocina/to_fedora/content_metadata_generator.rb
> +          file_node.add_child(create_image_data_node(cocina_file.presentation.height, cocina_file.presentation.width))
Isn't presentation optional?

2022-02-14 17:23 UTC, jcoyne commented on app/services/cocina/to_fedora/content_metadata_generator.rb
> +          file_node.add_child(create_image_data_node(cocina_file.presentation.height, cocina_file.presentation.width))
I don't believe this is optional on image types. If it wasn't present then it would break the access code.  We are switching to ensuring that all constituent members are images, right?

2022-02-14 17:37 UTC, justinlittman commented on app/services/cocina/to_fedora/content_metadata_generator.rb
> +          file_node.add_child(create_image_data_node(cocina_file.presentation.height, cocina_file.presentation.width))
Is there anything in our code that enforces this for existing data? Do we need to add it to Cocina? Or create a new validator?

2022-02-14 18:09 UTC, justinlittman commented
I ran this on a small sample of virtual objects and it seems to have introduced an error:
```
$ bin/validate-cocina-roundtrip -i druids.virtual.txt -s 500
Status (n=500; not using Missing for success/different/error stats):
  Success:   484 (96.8%)
  Different: 9 (1.8%)
  Mapping error:     0 (0.0%)
  Create error:     7 (1.4%) <----------------------
  Normalization error:     0 (0.0%)
  Missing from cache:     0 (0.0%)
  Unmapped:     0 (0.0%)
  Expected unmapped:     0 (0.0%)
  Bad cache:     0 (0.0%)
```

$ git checkout main
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
$ bin/validate-cocina-roundtrip -i druids.virtual.txt -s 500
Status (n=500; not using Missing for success/different/error stats):
  Success:   484 (96.8%)
  Different: 16 (3.2%)
  Mapping error:     0 (0.0%)
  Create error:     0 (0.0%)
  Normalization error:     0 (0.0%)
  Missing from cache:     0 (0.0%)
  Unmapped:     0 (0.0%)
  Expected unmapped:     0 (0.0%)
  Bad cache:     0 (0.0%)
```

2022-02-14 18:37 UTC, jcoyne commented on app/services/cocina/normalizers/content_metadata_normalizer.rb
> +      def remove_external_image_data
@justinlittman  This clearly affects the round trip results, but I'm not sure what I ought to do about this. I don't understand how normalizers are supposed to work.

2022-02-15 04:24 UTC, jcoyne commented
@andrewjbtw here are the invalid virtual objects:

```
druid:fk658ss3613=create_error
druid:zm453vp3719=create_error
druid:gx581fb6401=create_error
druid:qk134sy4320=create_error
druid:mq586jq5910=create_error
druid:pp407rf7502=create_error
druid:fw628pk2797=create_error
```

How should we handle these?  Should we remove the non-image external resources?

2022-02-16 19:26 UTC, justinlittman requested changes

2022-02-16 19:26 UTC, justinlittman commented on app/services/cocina/to_fedora/content_metadata_generator.rb
> +            Honeybadger.notify('External resource has no presentation data', { external_druid: external_druid, druid: druid })
Can you please use use DataErrorNotifier?

2022-02-16 20:28 UTC, jcoyne commented on app/services/cocina/to_fedora/content_metadata_generator.rb
> +            Honeybadger.notify('External resource has no presentation data', { external_druid: external_druid, druid: druid })
@justinlittman if I do that, what passes the messages on to honeybadger?  This class isn't already configured to use the notifier and I'm using this to publish public xml, not as a way to persist in Fedora.

2022-02-17 01:45 UTC, justinlittman approved these changes

2022-03-01 21:26 UTC, justinlittman commented
Since tested and reported problem was fixed, I'm merging.

2022-03-01 21:26 UTC, merged