[DRAFT] Rewrite rights metadata in public xml from cocina
sul-dlss/dor-services-app pull request #3509
Opened 2022-02-17 17:38 UTC by aaron-collier

## Why was this change made? 🤔

Fixes #3330

This is draft until I can verify the various rights combinations are creating the expected public xml, and then some cleanup and refactoring. Wanting to get this in the open in case there are concerns or suggestions about this approach.

## How was this change tested? 🤨

Updated unit tests.

⚡ ⚠ If this change has cross service impact, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

2022-02-17 22:23 UTC, jcoyne requested changes

2022-02-17 22:23 UTC, jcoyne commented on app/services/publish/rights_metadata.rb
> +      return '<license />' unless @object.access.respond_to?(:license) && @object.access.license
Why are you checking for `respond_to?(:license)`?  Aren't all publishable types going to have that?

2022-02-17 22:23 UTC, jcoyne commented on app/services/publish/rights_metadata.rb
> +      return '<human />' unless @object.access.respond_to?(:copyright) && @object.access.copyright
Why are you checking for `respond_to?(:copyright)`?  Aren't all publishable types going to have that?

2022-02-17 22:23 UTC, jcoyne commented on app/services/publish/rights_metadata.rb
> +      return unless @object.access.respond_to?(:access) && @object.access.respond_to?(:download)
Why are you checking for `@object.access.respond_to?(:access)` ?  Which types would that be false for?

2022-02-17 22:23 UTC, jcoyne commented on app/services/publish/rights_metadata.rb
> +    def read
How would this be produced?
```xml
       <access type="read">
          <machine>
            <world />
          </machine>
        </access>
```

I can't seems to find a path for that.

2022-02-17 22:25 UTC, jcoyne commented on app/services/publish/rights_metadata.rb
> +    def read
I see that would be in the `download`.

2022-02-17 22:26 UTC, jcoyne commented on app/services/publish/rights_metadata.rb
> +      return '<human type="useAndReproduction" />' unless @object.access.respond_to?(:useAndReproductionStatement) && @object.access.useAndReproductionStatement
Why are you checking for `respond_to?(:useAndReproductionStatement)`?  Aren't all publishable types going to have that?

2022-02-18 01:52 UTC, jcoyne requested changes

2022-02-18 01:52 UTC, jcoyne commented on app/services/publish/rights_metadata.rb
> +      "<embargoReleaseDate>#{@object.access.embargo.releaseDate}</embargoReleaseDate>"
Please format `.utc.iso8601`

2022-02-25 21:28 UTC, jcoyne approved these changes

2022-02-25 21:29 UTC, jcoyne commented
__PERSON WHO MERGES:__ Please squash commits.

2022-02-26 01:21 UTC, justinlittman commented
I cleaned up the commits.

2022-03-04 00:44 UTC, mjgiarlo commented on app/services/publish/rights_metadata.rb
> +  # rubocop:disable Metrics/ClassLength
@aaron-collier and I talked about the `Cocina::ToFedora::Rights::*` classes that already have all the rights logic for objects and files to see whether we can repurpose them in the publish context here.

2022-03-04 03:12 UTC, aaron-collier commented on app/services/publish/rights_metadata.rb
> +  # rubocop:disable Metrics/ClassLength
This is actually coming along well and I think it will be much better. Thanks @mjgiarlo

2022-03-04 03:51 UTC, aaron-collier commented on app/services/publish/rights_metadata.rb
> +      add_release_date(cocina_access) if release_date
I'm going to investigate moving these lines into AccessGenerator.

2022-03-04 22:16 UTC, aaron-collier commented
@andrewjbtw has tested and signed off on this.

2022-03-04 22:25 UTC, merged