add report-content-imagedata-not-num
sul-dlss/dor-services-app pull request #3550
Opened 2022-02-19 01:36 UTC by ndushay

## Why was this change made? 🤔

To look beyond the tea leaves into the actual data, I presume.

Closes #3540 

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

I ran the code in this report against some contentMetadata in the rails console.

2022-02-21 23:03 UTC, justinlittman requested changes

2022-02-21 23:03 UTC, justinlittman commented on bin/reports/report-content-imagedata-not-num
> +  Float(width) if width.present?
Integer, not float.

2022-02-22 05:16 UTC, ndushay commented on bin/reports/report-content-imagedata-not-num
> +  Float(width) if width.present?
er ... we have ones that are Float like 29.82334124mm -- I thought that was ok

2022-02-22 18:33 UTC, ndushay commented on bin/reports/report-content-imagedata-not-num
> +  Float(width) if width.present?
Is the goal to identify all the non-integer ones, or the ones with  "mm" or whatever?

2022-02-22 18:36 UTC, justinlittman commented on bin/reports/report-content-imagedata-not-num
> +  Float(width) if width.present?
Non-integer and non-blank.

2022-02-22 22:58 UTC, ndushay commented on bin/reports/report-content-imagedata-not-num
> +  Float(width) if width.present?
ok!  can do.

2022-02-24 12:59 UTC, justinlittman approved these changes

2022-02-24 12:59 UTC, merged