Handle Hydrus APOs with no content metadata.
sul-dlss/dor-services-app pull request #3573
Opened 2022-02-22 20:40 UTC by justinlittman

closes #3553

## Why was this change made? 🤔
Avoid normalizer error.

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

Before:
```
Status (n=100000; not using Missing for success/different/error stats):
  Success:   99795 (99.877%)
  Different: 123 (0.123%)
  Mapping error:     0 (0.0%)
  Create error:     0 (0.0%)
  Normalization error:     0 (0.0%)
  Missing from cache:     0 (0.0%)
  Unmapped:     0 (0.0%)
  Expected unmapped:     82 (0.082%)
  Bad cache:     0 (0.0%)
  Validate error:     0 (0.0%)
```

After:
```
Status (n=100000; not using Missing for success/different/error stats):
  Success:   99795 (99.877%)
  Different: 123 (0.123%)
  Mapping error:     0 (0.0%)
  Create error:     0 (0.0%)
  Normalization error:     0 (0.0%)
  Missing from cache:     0 (0.0%)
  Unmapped:     0 (0.0%)
  Expected unmapped:     82 (0.082%)
  Bad cache:     0 (0.0%)
  Validate error:     0 (0.0%)
```

This was also tested locally with some know problems.

2022-02-22 22:55 UTC, ndushay approved these changes

2022-02-22 23:32 UTC, jcoyne requested changes

2022-02-22 23:32 UTC, jcoyne commented on app/services/cocina/from_fedora/descriptive.rb
> +        return nil if ng_xml.root.nil?
Why is this PR about contentMetadata, but this change is affecting descMetadata?

2022-02-22 23:59 UTC, ndushay commented on app/services/cocina/from_fedora/descriptive.rb
> +        return nil if ng_xml.root.nil?
That is a most excellent question.

2022-02-23 00:00 UTC, ndushay commented on app/services/cocina/from_fedora/descriptive.rb
> +        return nil if ng_xml.root.nil?
Looks like PR title is wrong:  https://github.com/sul-dlss/dor-services-app/issues/3553

```
Cause:
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/from_fedora/descriptive.rb:78:in `check_version'
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/from_fedora/descriptive.rb:31:in `props'
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/from_fedora/descriptive.rb:17:in `props'
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/from_fedora/dro.rb:66:in `block in props'
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/from_fedora/dro.rb:64:in `tap'
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/from_fedora/dro.rb:64:in `props'
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/from_fedora/dro.rb:11:in `props'
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/mapper.rb:42:in `build'
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/mapper.rb:28:in `build'
bin/validate-cocina-roundtrip:215:in `validate_druid'
```

2022-02-23 00:01 UTC, ndushay commented on app/services/cocina/from_fedora/descriptive.rb
> +        return nil if ng_xml.root.nil?
I changed the title.

2022-02-23 02:16 UTC, justinlittman commented on app/services/cocina/from_fedora/descriptive.rb
> +        return nil if ng_xml.root.nil?
I changed the commit message.

2022-02-23 02:21 UTC, jcoyne approved these changes

2022-02-23 02:21 UTC, merged