Rewrite RefreshMetadataAction for Cocina objects
sul-dlss/dor-services-app pull request #3584
Opened 2022-02-24 17:01 UTC by aaron-collier

## Why was this change made? 🤔

Fixes #3169 - rewrites RefreshMetadataAction to use cocina objects, Moves existing RefreshMetadataAction into LegacyRefreshMetadataAction for object creation where Draft cocina objects do not have the required externalIdentifier yet.

## How was this change tested? 🤨

Updated unit tests.

⚡ ⚠ If this change has cross service impact, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

2022-02-24 17:49 UTC, justinlittman requested changes

2022-02-24 17:49 UTC, justinlittman commented on app/services/refresh_metadata_action.rb
> +    CocinaObjectStore.save(updated_cocina_object)
I don't think we want to move save into the action.

2022-02-24 21:31 UTC, justinlittman commented on app/services/refresh_metadata_action.rb
>    # @return [NilClass,Object] returns nil if there was no resolvable metadata id.
This is a slight refactoring, but would you consider returning a [dry-monads result](https://dry-rb.org/gems/dry-monads/1.3/result/) instead of using nil to indicate that no resolveable metadata id?

2022-02-24 22:11 UTC, jcoyne requested changes

2022-02-24 22:11 UTC, jcoyne commented on app/controllers/metadata_refresh_controller.rb
> +    @identifiers ||= @cocina_object.identification&.catalogLinks&.collect { |clink| clink.catalogRecordId }
What about barcode?

2022-02-24 22:11 UTC, jcoyne commented on spec/requests/metadata_refresh_spec.rb
> +      purl: "https://purl.stanford.edu/#{Dor::PidUtils.remove_druid_prefix(druid)}"
Can we be certain that the MODS provided by Symphony will always be able to produce a purl? If it doesn't this descriptive won't validate.

2022-02-24 22:11 UTC, jcoyne commented on app/services/refresh_metadata_action.rb
> +  # @param [Cocina::Models::DRO] cocina_object to refresh
It's not always a DRO.

2022-02-24 22:18 UTC, jcoyne commented on app/services/refresh_metadata_action.rb
> +    CocinaObjectStore.save(updated_cocina_object)
@justinlittman doesn't that make it hard to reuse this for the ObjectCreator (or whatever that evolves into?)

2022-02-24 22:28 UTC, jcoyne commented on app/services/refresh_metadata_action.rb
> +    CocinaObjectStore.save(updated_cocina_object)
Ah, nevermind you said "don't"

2022-02-24 22:33 UTC, jcoyne commented on spec/requests/metadata_refresh_spec.rb
> +      purl: "https://purl.stanford.edu/#{Dor::PidUtils.remove_druid_prefix(druid)}"
I think this is a safe bet:
```
2.7.0 :010 > mods = MetadataService.fetch("catkey:1997249")
2.7.0 :011 > props = Cocina::FromFedora::Descriptive.props(mods: Nokogiri::XML(mods), druid: 'druid:bb000fg4892')
2.7.0 :012 > props[:purl]
 => "https://purl.stanford.edu/bb000fg4892"
 ```

2022-02-25 17:11 UTC, aaron-collier commented on app/controllers/metadata_refresh_controller.rb
> +    @identifiers ||= @cocina_object.identification&.catalogLinks&.collect { |clink| clink.catalogRecordId }
Added barcode here. If adding the `barcode:` prefix is inaccurate, happy to address. Barcodes are unresolvable without it.

2022-02-25 17:26 UTC, jcoyne requested changes

2022-02-25 17:26 UTC, jcoyne commented on app/controllers/metadata_refresh_controller.rb
> +    @identifiers ||= @cocina_object.identification&.catalogLinks&.collect { |clink| clink.catalogRecordId }.tap do |id|
Should we filter out things where `clink.catalog  != 'symphony'` currently we also put previous catkeys in here too.

2022-02-25 17:53 UTC, aaron-collier commented on app/controllers/metadata_refresh_controller.rb
> +    @identifiers ||= @cocina_object.identification&.catalogLinks&.collect { |clink| clink.catalogRecordId }.tap do |id|
Did we before? I can add that if necessary.

2022-02-25 19:31 UTC, jcoyne commented on app/controllers/metadata_refresh_controller.rb
> +    @identifiers ||= @cocina_object.identification&.catalogLinks&.collect { |clink| clink.catalogRecordId }.tap do |id|
Oh, one other thing. Don't these need to be prefixed with `"catkey:#{clink.catalogRecordId}"`?

2022-02-25 19:34 UTC, jcoyne commented on spec/requests/metadata_refresh_spec.rb
> +        catalogRecordId: 'catkey:10121797'
I don't think that most catkeys are formatted like this.  See https://argo.stanford.edu/view/druid:bb000fg4892
<img width="555" alt="Screen Shot 2022-02-25 at 1 34 22 PM" src="https://user-images.githubusercontent.com/92044/155782647-f48fc19b-5431-40bc-8b30-bfada0e7a05d.png">
.

2022-02-25 21:49 UTC, jcoyne commented on app/controllers/metadata_refresh_controller.rb
> +    return identifier if identifier.include?(':')
I don't think we have any restrictions against `:` in catkeys (e.g. 'foo:bar:123'), so I think you need to remove this.  It should always prefix with `catkey:`

2022-02-25 21:49 UTC, jcoyne commented on app/controllers/metadata_refresh_controller.rb
> +    @identifiers ||= @cocina_object.identification&.catalogLinks&.collect { |clink| prefixed_identifier(clink.catalogRecordId) }.tap do |id|
We definitely need to filter out previous catkeys from this or it can return bad data.

2022-02-25 22:14 UTC, jcoyne requested changes

2022-02-25 22:14 UTC, jcoyne commented on app/controllers/metadata_refresh_controller.rb
> +    @identifiers ||= @cocina_object.identification&.catalogLinks&.collect { |clink| "catkey:#{clink.catalogRecordId}" }.tap do |id|
we still need to filter out previous catkeys or those will be considered the current identifiers and return bad data.

2022-02-25 22:18 UTC, aaron-collier commented on app/controllers/metadata_refresh_controller.rb
> +    @identifiers ||= @cocina_object.identification&.catalogLinks&.collect { |clink| "catkey:#{clink.catalogRecordId}" }.tap do |id|
shoot, i totally missed your comment above (shakes fist at github).

2022-02-25 22:54 UTC, jcoyne requested changes

2022-02-25 22:54 UTC, jcoyne commented on app/controllers/metadata_refresh_controller.rb
> +    return nil unless @cocina_object.identification&.catalogLinks
This used to return an empty array, and now it returns nil.  Have you tested that `RefreshMetadataAction` can handle being called with nil?

2022-02-25 22:54 UTC, jcoyne commented on app/controllers/metadata_refresh_controller.rb
> +    @identifiers ||= @cocina_object.identification.catalogLinks.select { |clink| clink.catalog == 'symphony' }
This works, but `filter_map` might be an easier way to write this. nbd.

2022-02-25 23:03 UTC, aaron-collier commented on app/controllers/metadata_refresh_controller.rb
> +    return nil unless @cocina_object.identification&.catalogLinks
Mistake, fixed.

2022-02-25 23:03 UTC, aaron-collier commented on app/controllers/metadata_refresh_controller.rb
> +    @identifiers ||= @cocina_object.identification.catalogLinks.select { |clink| clink.catalog == 'symphony' }
Oh yeah, I like filter_map better, thanks!

2022-02-25 23:10 UTC, jcoyne approved these changes

2022-02-25 23:12 UTC, justinlittman approved these changes

2022-03-03 19:09 UTC, justinlittman commented
Tested by Andrew.

2022-03-03 19:09 UTC, merged