replace Dor::SearchService with SolrService
sul-dlss/dor-services-app pull request #3653
Opened 2022-03-02 23:49 UTC by peetucket

## Why was this change made? 🤔

Fixes #3639 - replace Dor::SearchService with new SolrService

## How was this change tested? 🤨

Updated existing tests 

⚡ ⚠ If this change has cross service impact, including data writes to shared file system, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

2022-03-02 23:53 UTC, peetucket commented on app/validators/cocina/unique_source_id_validator.rb
>      end
the `query_by_id` method in dor-services (https://github.com/sul-dlss/dor-services/blob/main/lib/dor/services/search_service.rb#L29-L43) was more generalized and complicated ... but we only call it in this one place, so we can simplify a bit (basically, lookup by the single supplied source ID and return either an array of druids, or nil if none found)

2022-03-02 23:55 UTC, peetucket commented on spec/requests/create_object_spec.rb
>    end
we now mock a solr response (see new lines 30-32 above) so that our updated `lookup_duplicate` method works as expected

2022-03-02 23:57 UTC, mjgiarlo approved these changes

2022-03-02 23:57 UTC, mjgiarlo commented on app/services/embargo_release_service.rb
> +    solr = SolrService.get(query, 'rows' => '5000', 'fl' => 'id')
This line is the source of the coverage ding. Not sure if it's bogus or legit.

2022-03-03 00:07 UTC, peetucket commented on app/services/embargo_release_service.rb
> +    solr = SolrService.get(query, 'rows' => '5000', 'fl' => 'id')
Yeah,  interesting -- I don't see this method being called from anywhere in the DSA codebase (it's also not tested).  I wonder if the whole method can just be removed?

2022-03-03 00:11 UTC, mjgiarlo commented on app/services/embargo_release_service.rb
> +    solr = SolrService.get(query, 'rows' => '5000', 'fl' => 'id')
@peetucket looks like dead code to me too. KILL IT

2022-03-03 00:15 UTC, mjgiarlo commented on app/services/embargo_release_service.rb
> +    solr = SolrService.get(query, 'rows' => '5000', 'fl' => 'id')
@peetucket This became dead code five days ago: https://github.com/sul-dlss/dor-services-app/commit/29f9d8907f729d43f36ac4858cbd8a6b092a45fc#diff-a5e0fdbbca23f671b0fba6425be8786707a402115eab792a3b8bcfa3ad449fbcL67

2022-03-03 00:58 UTC, peetucket commented on app/services/embargo_release_service.rb
> +    solr = SolrService.get(query, 'rows' => '5000', 'fl' => 'id')
Cool.  I removed it.

2022-03-03 00:59 UTC, peetucket commented on app/services/embargo_release_service.rb
>    def self.release_all
dead code - not called anywhere anymore

2022-03-03 01:02 UTC, merged

2022-03-03 01:04 UTC, jcoyne commented on app/validators/cocina/unique_source_id_validator.rb
>      end
It was doing a term query there, but this logic would tokenize and match on the tokens which might match more than you expect. I think a term query here is the right choice.

2022-03-03 01:04 UTC, jcoyne requested changes
Please use a term query when finding by identifier