add versions/current/update endpoint
sul-dlss/dor-services-app pull request #3903
Opened 2022-04-19 23:13 UTC by ndushay

## Why was this change made? 🤔

For https://github.com/sul-dlss/argo/issues/3493, we need a way to update an objects _open_ version description and "significance" (tag).  This provides the endpoint necessary.  

## How was this change tested? 🤨

specs

⚡ ⚠ If this change has cross service impact, including data writes to shared file systems, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

2022-04-19 23:20 UTC, ndushay commented on app/models/object_version.rb
> +  # @param [String] description text describing version change
fix mistake - description param is not optional

2022-04-19 23:20 UTC, ndushay commented on spec/models/object_version_spec.rb
> +  describe '#update_current_version' do
fix mistake (probably method was renamed at some point.

2022-04-19 23:20 UTC, ndushay commented on spec/models/object_version_spec.rb
> +        expect(described_class.current_version(druid).version).to eq(1)
this proves the current_version is still 1, which is a better test.

2022-04-19 23:20 UTC, ndushay commented on spec/requests/versions_spec.rb
> +    context 'when closing a version succeeds' do
fix typo

2022-04-19 23:20 UTC, ndushay commented on spec/requests/versions_spec.rb
> +      it 'returns false' do
fix copy pasta

2022-04-20 00:04 UTC, jcoyne commented on config/routes.rb
> +          post 'current/update', action: 'update_current'
Could we have a `CurrentVersionController` with `#show`, `#update`, and `#close`?

2022-04-20 00:29 UTC, justinlittman requested changes

2022-04-20 00:29 UTC, justinlittman commented on app/controllers/versions_controller.rb
> +    render plain: VersionService.update_open_version(@cocina_object, update_params).to_s
What is this returning?

2022-04-20 22:38 UTC, ndushay commented
we ended up going in a completely different direction for addressing https://github.com/sul-dlss/argo/issues/3286, the problem where some versions can't be closed because they have no version descriptions.  See PR #3910

2022-04-20 22:38 UTC, closed without merging