Rake task to find objects missing from the index and output a list of…
sul-dlss/dor-services-app pull request #4079
Opened 2022-06-06 19:58 UTC by aaron-collier

… druids

## Why was this change made? 🤔

Part of [dor-indexing-app/843](https://github.com/sul-dlss/dor_indexing_app/issues/843)

This initial rake task will be used to produce a report to determine the extent of missing druids in the index. It is possible that this rake task will be relatively temporary, but depending on the number of missing items, we may want to keep it for recurring reporting as further work on 843 continues.

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact, including data writes to shared file systems, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

2022-06-06 20:03 UTC, edsu approved these changes

2022-06-06 20:03 UTC, jcoyne requested changes

2022-06-06 20:30 UTC, aaron-collier commented on lib/tasks/missing_druids.rake
> +      model.find_each do |object|
@jcoyne good point, I've updated this to query SOLR first, then diff the results from the db per discussion.

2022-06-06 22:05 UTC, ndushay reviewed
added some possibly useless info ...

2022-06-06 22:05 UTC, ndushay commented on lib/tasks/missing_druids.rake
> +      results = SolrService.query('*:*', fl: 'id', rows: 10000, start: druids_from_solr.length, sort: 'id asc')
if you set `wt: 'csv'` and ask for 10 million, you should get all the druids in a very compact response, if you can wait long enough for the response (without losing the connection).  You should also see if the query `id:*` speeds it up at all, so Solr returns all docs with ids (which should be all docs.

2022-06-06 22:05 UTC, ndushay commented on lib/tasks/missing_druids.rake
> +      model.find_each do |object|
I *think* what JCoyne is suggesting is that you can use the list of druids to access each object by id, and determine which ones aren't there???    Or I could be confused.

2022-06-06 22:51 UTC, aaron-collier commented on lib/tasks/missing_druids.rake
> +      model.find_each do |object|
@ndushay we discussed in a slack thread getting a list of each (db, solr) then diffing the results.

2022-06-06 22:52 UTC, aaron-collier commented on lib/tasks/missing_druids.rake
> +      results = SolrService.query('*:*', fl: 'id', rows: 10000, start: druids_from_solr.length, sort: 'id asc')
That's a good idea to look into if this sticks around, but since initially we're trying to get a first list, I would think this is good for now. But if not, let me know.

2022-06-07 01:53 UTC, ndushay commented
I'm okay running with this as is for now;  hopefully it won't be horribly non-performant.   

I would expect we will need to run the same thing (get DSA druids, get Solr druids, compare entire lists) as a cron in the future, so maybe another ticket for doing that which can include paying more attention to performance, after this is done ....

2022-06-07 03:50 UTC, aaron-collier commented
@ndushay yeah, this being a cron-able task is what it was initially intended for, but discussion this morning suggested that we wanted an initial report. Perhaps I misunderstood.

2022-06-07 12:26 UTC, jcoyne commented on lib/tasks/missing_druids.rake
> +      results = SolrService.query('*:*', fl: 'id', rows: 10000, start: druids_from_solr.length, sort: 'id asc')
I'm with @ndushay.  Doing 1 request instead of 400 is the simplest thing and we should try it first.

2022-06-07 17:33 UTC, jcoyne commented on lib/tasks/missing_druids.rake
> +      model.find_each do |object|
If you do `model.all.pluck(:external_identifier)` here, you don't need this inner loop.

2022-06-07 17:46 UTC, aaron-collier commented on lib/tasks/missing_druids.rake
> +      model.find_each do |object|
oh, that's cool, I didn't realize pluck would be that helpful there. On it.

2022-06-07 18:09 UTC, ndushay approved these changes

2022-06-07 18:10 UTC, merged