Add reports for edtf and w3cdtf validation
sul-dlss/dor-services-app pull request #4091
Opened 2022-06-07 22:58 UTC by mjgiarlo

## Why was this change made? 🤔

Fixes #4071
Fixes #4073

Also brings the ISO8601 date report into alignment with the new reports.

## How was this change tested? 🤨

Ran all three reports on stage

2022-06-07 23:02 UTC, mjgiarlo commented on app/reports/bad_iso8601_dates.rb
> +end
I refactored and renamed this report, @jcoyne, to align with the other two date reports and to accommodate a couple changes:

1. Report on all bad date values, not just the first
1. Report on values that are nested in structured and parallel and grouped values

2022-06-07 23:05 UTC, ndushay reviewed
So this addresses #4071, #4072, #4072 and #4052?

How does it cope with Arcadia's desire for what may be a subset of the allowed regex values in the etdf gem, for example?

How will this relate to the date validation code going into cocina when someone picks up sul-dlss/cocina-models#483?   I see you remove that code here.  Also, we're going to do date validation via cocina-models so it seems prudent to have these reports run through the same validation code (I know,  sul-dlss/cocina-models#483 didn't exist when you picked up this ticket ...)

Beyond those questions, the code here looks fine to me.  Confer with JCoyne and Arcadia, I guess.

2022-06-07 23:10 UTC, mjgiarlo commented
@ndushay 
> So this addresses #4071, #4072, #4072 and #4052?

And #4073, yeah. I wasn't aware of #4052 when I started this PR, and I can remove those bits if folks prefer; I don't need it for these reports. I'm flexible.
 
> How does it cope with Arcadia's desire for what may be a subset of the allowed regex values in the etdf gem, for example?

This is the first I've heard of it. Can you or @arcadiafalcone point me at more information?
 
> How will this relate to the date validation code going into cocina when someone picks up [sul-dlss/cocina-models#483](https://github.com/sul-dlss/cocina-models/issues/483)? I see you remove that code here ...

Once it's in Cocina and that's deployed, entering bad dates will no longer be possible, but we may still have data to remediate. I'd say once all three reports run clean, we can ditch these reports and the changes in this commit.
 
> Beyond those questions, the code here looks fine to me. Confer with JCoyne and Arcadia, I guess.

cc: @jcoyne @arcadiafalcone 😄

2022-06-08 00:22 UTC, jcoyne requested changes

2022-06-08 00:22 UTC, jcoyne commented on app/reports/bad_iso8601_dates.rb
> +    rescue ArgumentError
Shouldn't this be a `Date::Error`?

2022-06-08 15:18 UTC, mjgiarlo commented on app/reports/bad_iso8601_dates.rb
> +    rescue ArgumentError
Yes, copypasta. Thank you!

2022-06-08 15:30 UTC, jcoyne approved these changes

2022-06-08 16:41 UTC, ndushay commented
@mjgiarlo can you easily determine which date patterns are allowed by this code?   The regexp in the date validator class (which will be migrating to cocina models)  should reflect what @arcadiafalcone wanted.  I don't know if it's a subset or not ... it's just that we've got more of a black box on valid dates with this implementation.

2022-06-08 16:49 UTC, jcoyne commented
@ndushay a Regex is not sufficient for validating dates (unless it's monstrously complex).  Consider leap years, Sept 31, etc.

2022-06-08 21:44 UTC, mjgiarlo commented
@ndushay @jcoyne I chatted with Arcadia and she is on board with using upstream validators ([comment](https://github.com/sul-dlss/cocina-models/issues/392#issuecomment-1150440283)). @ndushay can you re-review?

2022-06-08 21:54 UTC, ndushay approved these changes

2022-06-08 21:54 UTC, merged