report subjects_with_double_dash narrows to 2 source codes
sul-dlss/dor-services-app pull request #4240
Opened 2022-09-21 19:24 UTC by ndushay

## Why was this change made? 🤔

Fixes #4237

## How was this change tested? 🤨

Ran it and spot checked a few results.

⚡ ⚠ If this change has cross service impact, including data writes to shared file systems, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

2022-09-21 20:02 UTC, jcoyne requested changes

2022-09-21 20:02 UTC, jcoyne commented on app/reports/subjects_with_double_dash.rb
> +           AND jsonb_path_exists(description, '#{JSONB_PATH}.source.code ? (@ like_regex "^(lcsh|naf)$")')
I think you could say `subjects->>'source'->>'code' IN ('lcsh', 'naf')` here. To me, that's easier to read and then you could skip the filter on line 41.

2022-09-21 20:58 UTC, ndushay commented
@jcoyne took your suggestion and it worked swimmingly.  Ready for re-review.

2022-09-22 01:32 UTC, jcoyne approved these changes

2022-09-22 01:32 UTC, merged