Adds new rubocops.
sul-dlss/dor-services-app pull request #4275
Opened 2022-10-27 18:58 UTC by justinlittman

## Why was this change made? 🤔
All the rubos.

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact, including data writes to shared file systems, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

2022-10-28 22:26 UTC, ndushay requested changes
I think the "\." in these cases are intentional - it should be a period, not an anything char?

2022-10-28 22:26 UTC, ndushay commented on app/reports/invalid_form_uris.rb
> -    SELECT (jsonb_path_query_array(description, '#{JSON_PATH} ? (@ like_regex "^.*\.html$")') ||
actually, I think the period here is meant to be a real period, not an anything char.

2022-10-28 22:26 UTC, ndushay commented on app/reports/invalid_form_uris.rb
> -           jsonb_path_exists(description, '#{JSON_PATH} ? (@ like_regex "^.*\.html$")'))
ditto here...

2022-10-28 22:26 UTC, ndushay commented on app/reports/invalid_language_uris.rb
> -           jsonb_path_exists(description, '#{JSON_PATH2} ? (@ like_regex "^.*\.html$")')
and here

2022-10-31 11:45 UTC, justinlittman commented
Great catch @ndushay! I excluded that rule for all reports.

2022-10-31 16:34 UTC, ndushay approved these changes

2022-10-31 16:34 UTC, merged