Adds feature for syncing catalog links.
sul-dlss/dor-services-app pull request #4391
Opened 2023-02-21 18:16 UTC by justinlittman

closes #4376

## Why was this change made? 🤔
Allow Symphony and Folio catalog links to peacefully co-exist during the transition.

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact, including data writes to shared file systems, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

Unit

2023-02-21 18:17 UTC, justinlittman commented
Blocked by https://github.com/sul-dlss/cocina-models/issues/574

2023-02-24 22:34 UTC, ndushay requested changes
I think the approach of having create and update objects do this is sound.  

I remain uncomfortable with "sync" as the name for this, as it is really only adding folio identifiers, and only some of the time. 

I have concerns about multiple updates to the same object adding extra folio identifiers, and I also have concerns as to whether we could end up with multiple folio identifiers with refresh=true in those circumstances.

Therefore, even after covering those cases with tests, I think this should be tested by @andrewjbtw and/or Arcadia  to try to trip it up it in qa or stage before this is merged.

2023-02-24 22:34 UTC, ndushay commented on app/services/catalog_link_sync_service.rb
> +# Syncs Symphony catalog links with Folio catalog links
add a comment that this should only be in place BEFORE Folio is in place as ILS in production?

2023-02-24 22:34 UTC, ndushay commented on app/services/catalog_link_sync_service.rb
> +  def drop_catalog_link?(catalog_link)
I think this method would be more clearly named as "keep_existing_folio_link?"

2023-02-24 22:34 UTC, ndushay commented on app/services/catalog_link_sync_service.rb
> +      end
so if we have a symphony link, and it's not in the skip list .. then we add a folio link.  But if a record is updated 2 or 3 times, won't we be adding a folio link each time?   

If I understand the code, I *think* this will be ok for objects with multiple catkeys, tho.

2023-02-24 22:34 UTC, ndushay commented on app/services/catalog_link_sync_service.rb
> +class CatalogLinkSyncService
Actualy, this is a service to add missing folio links;  it is not exactly "sync" -- there is no true mirroring of links happening or desired.  Would it be better named "AddFolioCatalogLinks" ?

2023-02-24 22:34 UTC, ndushay commented on app/services/catalog_link_sync_service.rb
> +  def sync
better name:  add_folio_catalog_links?

2023-02-24 22:34 UTC, ndushay commented on app/services/catalog_link_sync_service.rb
> +  def synced_catalog_links
"populate_folio_links" ?

2023-02-24 22:34 UTC, ndushay commented on spec/services/catalog_link_sync_service_spec.rb
> +  context 'when there are catalog links' do
I think there are more cases -

- when record is updated mutiple times (starting without folio link;  starting with folio link)
it will likely be clearer to test these wrinkles with separate tests.

- how about a dro that only has "previous symphony"
- how about a dro that only has "folio" (????) or "previous folio" ???
- collection objects?
- is it correct that agreement and adminPolicy objects are never in Symphony?

any other wrinkles?   Ask @andrewjbtw and @arcadiafalcone ?

2023-02-27 12:51 UTC, justinlittman commented on app/services/catalog_link_sync_service.rb
> +# Syncs Symphony catalog links with Folio catalog links
Done.

2023-02-27 12:52 UTC, justinlittman commented on app/services/catalog_link_sync_service.rb
> +class CatalogLinkSyncService
Makes sense. Done.

2023-02-27 13:21 UTC, justinlittman commented on spec/services/catalog_link_sync_service_spec.rb
> +  context 'when there are catalog links' do
I've added tests for (1) when there is no existing Folio link and (2) a collection.

Updating multiple times is not distinct from the existing tests.
Handling of "previous symphony" is covered by the existing tests.
It's not clear what the proper handling of folio-only is because that is not an intended state prior to switchover to Folio.
Agreements are just DROs, so no special consideration required.
I don't know whether AdminPolicies are ever in Symphony. However, in cocina they cannot have catalog links.

2023-02-27 14:00 UTC, justinlittman commented on app/services/catalog_link_sync_service.rb
> +  def drop_catalog_link?(catalog_link)
It passes judgment on any sort of catalog link, so I don't think adding `folio` is accurate.

It could be renamed to `keep_existing ...`, but then its use becomes `unless ...` instead of `if ...`. The negative has to go somewhere, I'm not sure it matters where. If you feel strongly, let me know.

2023-02-27 14:02 UTC, justinlittman commented on app/services/catalog_link_sync_service.rb
> +      end
Existing folio links are dropped (`next if drop_catalog_link?(catalog_link)`), so the previous folio link will be dropped and a new folio link will be added.

2023-02-27 14:03 UTC, justinlittman commented on app/services/catalog_link_sync_service.rb
> +  def sync
I just changed it to `add` because `AddFolioCatalogLinksService.add` seems clear enough.

2023-02-27 17:47 UTC, ndushay requested changes
Thanks for the refactors.  I have another, better/clearer suggestion, and another possible hole in the logic.  And a quibble in spec description for your consideration.

2023-02-27 17:47 UTC, ndushay commented on app/services/catalog/add_folio_catalog_links_service.rb
> +    def drop_catalog_link?(catalog_link)
this method should be named `non_lane_folio_link?` - because that is what the logic says

2023-02-27 18:02 UTC, justinlittman commented on app/services/catalog/add_folio_catalog_links_service.rb
> +        next if drop_catalog_link?(catalog_link)
Skipping it means it is dropped, so mission accomplished. Unless I'm missing something?

2023-02-28 18:21 UTC, arcadiafalcone approved these changes

2023-02-28 18:24 UTC, arcadiafalcone commented
Everything I tested passed.

Not tested:
-collection records (pre-existing bug)
-release workflow

Testing notes:
br092xk8968 - existing ckey, opened (accessioned)
-refresh from source - adds FOLIO HRID with same refresh value
-change catkey - updates FOLIO HRID, no previous_catkey created
-new version, restore previous catkey - updates FOLIO HRID, no previous_catkey created
-change refresh status, both directions - updates FOLIO HRID refresh status
-remove catkey - removes FOLIO HRID, previous_catkey created
-re-add same catkey - adds FOLIO HRID, catkey
-replace with different catkey - adds FOLIO HRID, no previous_catkey created (but would be duplicate)
-add second catkey - adds second FOLIO HRID with same refresh status
-reverse refresh status on two catkeys - updates FOLIO refresh status
-remove second catkey - removes second FOLIO catkey
-FOLIO + symphony + previous symphony versions without error
-remove catkey when previous_catkey present - removes FOLIO HRID
-add catkey when only previous_catkey present - adds FOLIO HRID
-add second catkey and change refresh status - adds FOLIO HRID and updates refresh status

bc941dh2269 - no catkey, accessioned
-add catkey to object that never had catkey - adds FOLIO HRID and refresh status
-add forbidden Lane catkey to object with other catkey - message of successful update, catkey added, FOLIO HRID not added
-remove additional catkey from object with forbidden Lane catkey - message of successful update, catkey becomes previous

bn325xc3747 - no catkey, registered
-add catkey - adds FOLIO HRID and refresh status

ft043bp0584 - registered with catkey, form
-adds FOLIO HRID and refresh status
-pulls in descriptive metadata

nd981qw5082, qn756gy8851 - registered with catkey, tab-delimited
-adds FOLIO HRID and refresh status
-pulls in descriptive metadata
-tracking sheets use catkey label and value

hb877zh8366, qp882tk2097 - registered with catkey, CSV file upload (bulk action)
-adds FOLIO HRID and refresh status
-pulls in descriptive metadata

fm516px0309 - registered with forbidden Lane catkey, form
-adds catkey only
-pulls in descriptive metadata

bc544pb9701 - virtual object
-refreshed from source - FOLIO HRID and refresh status added


Bulk actions
-edit catkeys and barcodes - OK
-refresh MODS from catkey - OK
-edit catkeys and barcodes from CSV - OK
-register druids - OK

2023-02-28 18:42 UTC, ndushay approved these changes

2023-02-28 18:43 UTC, ndushay commented
approved - merge at will (take out the HOLD in the title, please) and ensure this won't be on in prod before we intend

2023-02-28 19:19 UTC, merged