[DRAFT | REDO] Refactor of marc856generator to serialize 856 string
sul-dlss/dor-services-app pull request #4432
Opened 2023-03-10 02:00 UTC by aaron-collier

## Why was this change made? 🤔

The original PR was reverted due to encoding issues of the string causing a bug. This will be a replacement to fix the encoding issue.

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact, including data writes to shared file systems, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

2023-03-10 02:17 UTC, ndushay reviewed
a few small notes on ...stuff we didn't fully understand before today.   Tagging @justinlittman as well.

2023-03-10 02:17 UTC, ndushay commented on app/services/catalog/marc_856_generator.rb
> +      record = {
This code still mistakenly believes all the information goes in ONE record.  It does not.  Each previous_ckey currently creates a record in the array.  Then the current ckey creates a more complicated record in the array.

2023-03-10 02:17 UTC, ndushay commented on app/services/catalog/marc_856_generator.rb
>      end
this |x notation is unlikely to be understood by Folio's QuickMarc (or any other API).

2023-03-10 02:17 UTC, ndushay commented on app/services/catalog/marc_856_generator.rb
>      end
this is a Stanford hoked-up notation between the SDR and the script that loads the data on the SYmphony side.  That script is going away in favor of the SDR making direct API calls to Folio.  We hope.

2023-03-10 02:17 UTC, ndushay commented on app/services/catalog/symphony_writer.rb
>    class SymphonyWriter
This class is where we would take the array of records, described in some hash format, and turn that hash into the String format Symphony is expecting in a file that is output from the SDR

2023-03-10 02:26 UTC, ndushay requested changes
We're going to talk about this;  just making extra sure we don't merge by accient.

2023-03-10 02:40 UTC, ndushay commented
Possibly useful for later:   `/sdrpurl_transfer` is where to find the output file on a dsa box.

2023-03-10 02:50 UTC, aaron-collier commented on app/services/catalog/marc_856_generator.rb
> +      record = {
My approach here is to to include the previous catkey lines in the single hash and then in `SymphonyWriter` treat them as individual records for output. That avoids the need to do any inspection, etc. when we get to Folio and they can simply be ignored if necessary.

2023-03-13 18:09 UTC, mjgiarlo commented on app/services/catalog/marc_856_generator.rb
> +    # @return [Array] hash of all data required to create stub 856 records for this object
Clarifying this is a hash in the text is a good tweak. And I think we can also tighten the return type specification in YARD by considering `@return [Array<Hash>] ...`

2023-03-13 18:18 UTC, ndushay requested changes
Im happy to pair or talk through my thinking on the 856 generator vs. the symphony writer -- what logic lives where and what the data structure needs to be.

2023-03-13 18:18 UTC, ndushay commented on app/services/catalog/marc_856_generator.rb
> +        rights:
while I love the meaningful keys here, I was thinking more like this:

```
...
indicators:
subfields [
   { x: value },
   { u: value },
   { x: nother value }
   { x: nother nother value }
]
```

The subfield char ("code") is generic marc;   the `|` is the part that was unique to the symphony script.

This also is presenting the info in an Array, which guarantees order, while a ruby Hash does not.  Order matters in Marc.

The values above could be the meaningful names you have chosen for the methods or attr with the germane data.

2023-03-13 18:18 UTC, ndushay commented on app/services/catalog/marc_856_generator.rb
> +  # Creates a hash that is used to stub the MARC 856 field (currently for transferring to symphony only) given a cocina object.
ditch "currenty for symphony only" clause

And now were not talking about a stub any longer -- this class is returning identifiers and then a hash of data to build a plain old marc 856 field, or no such hash to imply 856 matching druid should be removed.

@justinlittman did you want to keep the identifier information and whether or not it has an 856 associated in THIS class?  (makes sense to ... just confirming)

2023-03-13 18:18 UTC, ndushay commented on app/services/catalog/marc_856_generator.rb
> +    # @return [Array] hash of all data required to create stub 856 records for this object
"... required to update marc bib 856 fields to purls" ???


"@return [Array] hash" -- shouldn't this be [Array<Hash>] and then a description of the hash structure?

2023-03-13 18:18 UTC, ndushay commented on app/services/catalog/marc_856_generator.rb
>        return [] if ckeys.empty? && previous_ckeys.empty?
I've forgotten where we are with this -- should this still be "ckeys" and previous_ckeys"?   And it will accommodate folio hrids in a separate ticket?  Or is this "catalog_record_ids"?   Or ?

2023-03-13 18:18 UTC, ndushay commented on app/services/catalog/symphony_writer.rb
> +    end
so switching to the Array for subfields changes this stuff to something like:

```
marc_856 = ".856.#{record[:indicators]}"
record[:subfields].each { |subfield| marc_856 << "|#{subfield.first.key}#{subfield.first.value}" }

^^ thus, all the marc 856 logic is in the data structure, and the writer is a very stupid class that just takes the strings and turns them into the desired output.   Happy to talk through this if I'm not making sense.
```

2023-03-13 18:45 UTC, aaron-collier commented on app/services/catalog/marc_856_generator.rb
> +    # @return [Array] hash of all data required to create stub 856 records for this object
I have the hash layed out below this comment, maybe a better format?

2023-03-13 18:48 UTC, aaron-collier commented on app/services/catalog/symphony_writer.rb
> +    end
As discussed, I did not like the lack of explictness of the data when following that pattern (which is where this PR started) but can adopt it if that's what we prefer.

2023-03-13 19:09 UTC, aaron-collier commented on app/services/catalog/marc_856_generator.rb
> +        rights:
The problem I ran into with this proposed format is for fields that can have multiples, like collections and rights, when do the `|xcollection:` and `|xrights:` get serialized? If we follow this pattern it would need to be something like:

```
subfields: [
...
  {  x: `|xcollection:ckey_1:druid_1:title_1|xcollection:ckey_2:druid_2:title_2` }
]
```
so now we have the symphony specific pipe embedded in the data. With the approach I took, that is handled in the writer.

2023-03-13 21:20 UTC, aaron-collier commented on app/services/catalog/marc_856_generator.rb
> +        ].compact.flatten
Note that this `compact` and `flatten` removes any `nil` values returned from the list of methods, and then flattens the ones that return arrays like `collections` and `rights`

2023-03-13 21:28 UTC, ndushay reviewed
changes to 856 looking good;  a few small quibbles.   I also float the idea that you migh somehow indicate that, for example, "access" is returning the hash for subfield z.  Maybe `access_subfield_z`  or `subfield_z_access` or maybe you have something better.

2023-03-13 21:28 UTC, ndushay commented on app/services/catalog/marc_856_generator.rb
> +    # catalog_reocrd_id: the catalog key that associates a DOR object with a specific Symphony record.
typo

2023-03-13 21:28 UTC, ndushay commented on app/services/catalog/marc_856_generator.rb
> +    # @return [Array<Hash>] of data required to create stub 856 records for this object
"... of data required to update 856 fields for purls pertaining to this object" ???

2023-03-13 21:28 UTC, ndushay commented on app/services/catalog/marc_856_generator.rb
> +    # x - collections (optional): Collection(s) this object is a member of formatted as: druid:catkey:label
"... is a member of, formatted ..."

2023-03-13 21:28 UTC, ndushay commented on app/services/catalog/marc_856_generator.rb
> +    # NOTE: this is the data to serialize a stub 856 record (not a properly formatted 856 field nor a marc record)
"... the data to go in an 856 field (not a ...."  ?

2023-03-13 21:28 UTC, ndushay commented on app/services/catalog/marc_856_generator.rb
>      def new_identifier_record(ckey)
i would rename the param, too.

2023-03-13 22:27 UTC, ndushay approved these changes
Approving, modulo:
- look for catkey and ckey in the 856 code and spec (can leave for symphony writer)
- typo in comment line 55

having Andrew (?) try it in test.

2023-03-13 22:27 UTC, ndushay commented on spec/services/catalog/symphony_writer_spec.rb
> +      let(:marc856) do
maybe call this marc856file or something?

2023-03-13 22:27 UTC, ndushay commented on spec/services/catalog/symphony_writer_spec.rb
> +      let(:marc856) do
maybe call this marc856file or something?

2023-03-13 22:27 UTC, ndushay commented on app/services/catalog/marc_856_generator.rb
> +      records = previous_catalog_record_ids.map { |previous_catkey| new_identifier_record(previous_catkey) }
ugh - missed this before - previous_catkey

2023-03-13 22:27 UTC, ndushay commented on app/services/catalog/marc_856_generator.rb
> +    # NOTE: this is the data to go in an 856 field (not a (not a properly formatted 856 field nor a marc record)
not a not a

2023-03-13 22:27 UTC, ndushay commented on app/services/catalog/marc_856_generator.rb
> +    # x - collections (optional): Collection(s) this object is a member of, formatted as: druid:catkey:label
catkey

2023-03-13 22:27 UTC, ndushay commented on app/services/catalog/marc_856_generator.rb
>      # @return [String] the collection information druid-value:catkey-value:title format
catkey

2023-03-13 22:27 UTC, ndushay commented on app/services/catalog/marc_856_generator.rb
>          catkey = collection.identification&.catalogLinks&.find { |link| link.catalog == 'symphony' }
catkey

2023-03-13 22:27 UTC, ndushay commented on app/services/catalog/marc_856_generator.rb
> +        collection_info << { code: 'x', value: "collection:#{collection.externalIdentifier.sub('druid:', '')}:#{catkey&.catalogRecordId}:#{Cocina::Models::Builders::TitleBuilder.build(collection.desc
catkey

2023-03-13 22:27 UTC, ndushay commented on app/services/catalog/marc_856_generator.rb
>      # @return [Array] previous or current catkeys for the object in an array, empty array if none exist
catkey

2023-03-13 22:27 UTC, ndushay commented on spec/services/catalog/marc856_generator_spec.rb
>      context "when the druid object doesn't have catkey or previous catkeys" do
look for catkey and ckey in the spec, too.

2023-03-14 12:25 UTC, justinlittman reviewed
This PR gets us most of the way there. However, there is still some Symphony specific logic:
* Determining which records have 865s to be deleted and added.
* The inclusion of the catkey in subfield x collections. (Missed that before.)

That being said, I'd suggest that this is good enough (=huge improvement and step in the right direction) for this PR. I'd suggest that we make the minor tweaks recommended by Naomi, but leave all remaining catkey references as is. (Just renaming them to catalog record id doesn't solve the problem.) I'll address them in a follow-up PR that removes the last bits of Symphony-specific logic.

Also, makes sense to delay testing until the follow-up PR.

2023-03-14 13:11 UTC, justinlittman commented on app/services/catalog/marc_856_generator.rb
> +    # NOTE: this is the data to go in an 856 field (not a (not a properly formatted 856 field nor a marc record)
Fixed.

2023-03-14 13:15 UTC, justinlittman commented on spec/services/catalog/symphony_writer_spec.rb
> +      let(:marc856) do
Fixed.

2023-03-14 13:17 UTC, justinlittman commented
For the sake of expediency, I made the tweaks and squished the PR.

2023-03-14 13:18 UTC, merged