Add rake task to register with known druids
sul-dlss/dor-services-app pull request #4582
Opened 2023-09-01 19:36 UTC by aaron-collier

## Why was this change made? 🤔

Fixes #4581 

Note that `RegistrationCsvConverter` is largely a direct copy out of Argo for use here (and it's test). 

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact, including data writes to shared file systems, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

2023-09-01 20:33 UTC, justinlittman commented on lib/tasks/seed.rake
> +  rescue Errno::ENOENT => e
What is this for?

2023-09-01 20:33 UTC, justinlittman commented on app/services/registration_csv_converter.rb
> +  # @param [Hash] params that can be used instead of CSV columns. Keys are same as column headers.
Why not get rid of the params if we're always passing `{}`?

2023-09-01 20:33 UTC, justinlittman commented on lib/tasks/seed.rake
> +      },
Do we need to create tags?

2023-09-01 20:33 UTC, justinlittman commented on lib/tasks/seed.rake
> +                                                  ->(error) { log_error(error, bulk_action:, log:) })
What provides log_error()?

2023-09-01 21:03 UTC, aaron-collier commented on lib/tasks/seed.rake
> +  rescue Errno::ENOENT => e
I should probably just drop that since this is a rake task. It catches if the input file is not found. But that will be obvious for a command line tool.

2023-09-01 21:22 UTC, aaron-collier commented on lib/tasks/seed.rake
> +      },
Yes, I think so, I meant to add that. Done.

2023-09-01 21:23 UTC, aaron-collier commented on lib/tasks/seed.rake
> +                                                  ->(error) { log_error(error, bulk_action:, log:) })
Copypasta, replaced. However, I'm open to this not logging but reporting to the user. Hmm.

2023-09-01 21:57 UTC, aaron-collier commented
I believe the coverage drop here is for coverage of the big switch statement in RegistrationCsvConverter. The test was copied from Argo and would just switch the type between tests, so seems a bit excessive to try to do anything with coverage there, but happy to do it if we prefer avoiding that drop.

2023-09-06 16:49 UTC, justinlittman requested changes
What happens if this is run with an object that already exists?

2023-09-06 16:49 UTC, justinlittman commented on lib/tasks/seed.rake
> +                                                  ->(error) { Rails.logger.error(error) })
Since this is a rake task, can we also send the error to stdout?

2023-09-06 17:37 UTC, aaron-collier commented on lib/tasks/seed.rake
> +                                                  ->(error) { Rails.logger.error(error) })
Sure - just `puts`-ing it now if that's sufficient.

2023-09-06 17:37 UTC, aaron-collier commented
@justinlittman now capturing cocina and pg based duplication errors.

2023-09-07 11:31 UTC, justinlittman approved these changes

2023-09-07 11:31 UTC, merged