Retries creating workspace content dir in ShelvingService.
sul-dlss/dor-services-app pull request #4954
Opened 2024-05-01 20:02 UTC by justinlittman

closes #4952

## Why was this change made? 🤔
Less noisy integration tests.

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact, including data writes to shared file systems, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

2024-05-01 20:15 UTC, jcoyne requested changes
I believe this will make the problem worse.

Currently it fails because another process has already created the directory.   If you keep retrying, you will continue to find that the directory exists and still cannot be created.

2024-05-01 20:25 UTC, justinlittman commented
Here's the relevant code: https://github.com/sul-dlss/druid-tools/blob/main/lib/druid_tools/druid.rb#L88-L100

There are 2 checks to see if the directory exists prior to create (the first one should skip the create; the second one should raise). I'm guessing that there is probably a file system sync problem that is causing both of those checks to report that the directory doesn't exist. I'd expect that if retried the file system sync will resolve and the code will work as expected.

2024-05-01 21:28 UTC, jcoyne commented
@justinlittman If you have two processes running simultaneously and they each ask "Directory x created yet?" they will each get a "no". Then they will both try to create it.  One will succeed and the other will get this error.  A retry will just give the error again.

2024-05-01 22:33 UTC, justinlittman commented
On the second process's retry, it will discover that the directory exists (https://github.com/sul-dlss/druid-tools/blob/main/lib/druid_tools/druid.rb#L90) and skip the mkdir.

2024-05-01 23:28 UTC, jcoyne requested changes

2024-05-01 23:28 UTC, jcoyne commented on app/services/shelving_service.rb
> +    # This addresses a race condition.
can you be more specific about the race condition and why the retry resolves it in this comment?

2024-05-01 23:29 UTC, jcoyne commented on app/services/shelving_service.rb
> +    # This addresses a race condition.
Should the retry be upstream in the gem? Don't we want it fixed for all users?

2024-05-02 11:32 UTC, justinlittman commented on app/services/shelving_service.rb
> +    # This addresses a race condition.
I'm reluctant to fix in the gem, as the fix might have unintended consequences on other file systems.

Adding more detail to the comment.

2024-05-02 12:19 UTC, jcoyne approved these changes

2024-05-02 12:19 UTC, merged