Diff cocina from purl to determine what to shelve.
sul-dlss/dor-services-app pull request #4991
Opened 2024-05-15 20:28 UTC by justinlittman

closes #4982

## Why was this change made? 🤔
Less janky.

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact, including data writes to shared file systems, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

Unit, integration tests.

2024-05-16 18:30 UTC, jcoyne commented on app/services/digital_stacks_differ.rb
> +      response = connection.get("/#{bare_druid}")
Do you need to add `.json` as a suffix here?  Won't it give HTML by default?

2024-05-16 18:34 UTC, jcoyne requested changes

2024-05-16 18:34 UTC, jcoyne commented on app/services/digital_stacks_differ.rb
> +  # return [Array<String>] filenames of files that should be shelved
What about items that should be removed from stacks?

2024-05-16 18:44 UTC, justinlittman commented on app/services/digital_stacks_differ.rb
> +  # return [Array<String>] filenames of files that should be shelved
Stacks needs to figure that out.

2024-05-16 18:46 UTC, justinlittman commented on app/services/digital_stacks_differ.rb
> +      response = connection.get("/#{bare_druid}")
I'd expect so. Fixing.

2024-05-16 18:47 UTC, jcoyne commented on app/services/digital_stacks_differ.rb
> +  # return [Array<String>] filenames of files that should be shelved
Currently we don't have a stacks API, it's just a file system.  I would agree with you, but only after https://github.com/sul-dlss/purl-fetcher/issues/718 is done.

2024-05-22 14:41 UTC, jcoyne approved these changes

2024-05-22 14:41 UTC, merged