Adds user version index endpoint.
sul-dlss/dor-services-app pull request #4994
Opened 2024-05-16 19:38 UTC by justinlittman

closes #4993

## Why was this change made? 🤔
So that user versions can be displayed in argo.

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact, including data writes to shared file systems, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

Unit

2024-05-16 19:58 UTC, jcoyne commented on config/routes.rb
> +      resources :user_versions, only: [:index]
should this be resource (singular)? there's never more than one, right?

2024-05-16 20:00 UTC, jcoyne requested changes

2024-05-16 20:00 UTC, jcoyne commented on app/controllers/user_versions_controller.rb
> +  before_action :check_cocina_object_exists, only: %i[index]
Is this necessary? Why?

2024-05-16 20:10 UTC, justinlittman commented on app/controllers/user_versions_controller.rb
> +  before_action :check_cocina_object_exists, only: %i[index]
It's not. Removed.

2024-05-16 20:58 UTC, mjgiarlo commented on openapi.yml
> +                $ref: "#/components/schemas/UserVersionLog"
Should we add the 404 response here as well?

2024-05-16 20:59 UTC, mjgiarlo commented on openapi.yml
> +          description: the number of the user version
I'm curious why one version if a string and one is an int if both are numbers.

2024-05-16 21:02 UTC, mjgiarlo approved these changes
Approve pending consideration of comment

2024-05-16 22:41 UTC, jcoyne requested changes

2024-05-16 22:41 UTC, jcoyne commented on app/controllers/user_versions_controller.rb
> +  rescue_from(ActiveRecord::RecordNotFound) do |e|
Isn't this already done by `ActionDispatch::ExceptionWrapper.rescue_responses`?

2024-05-17 12:20 UTC, justinlittman commented on openapi.yml
> +          description: the number of the user version
Copypasta. Fixed.

2024-05-17 12:22 UTC, justinlittman commented on app/controllers/user_versions_controller.rb
> +  rescue_from(ActiveRecord::RecordNotFound) do |e|
When I comment out and run the test:
```
Failures:

  1) User versions when not found returns a 404
     Failure/Error: repository_object = RepositoryObject.find_by!(external_identifier: params[:object_id])

     ActiveRecord::RecordNotFound:
       Couldn't find RepositoryObject with [WHERE "repository_objects"."external_identifier" = $1]
     # ./app/controllers/user_versions_controller.rb:10:in `index'
     # ./spec/requests/user_versions_inventory_spec.rb:26:in `block (3 levels) in <top (required)>'
```

2024-05-17 14:53 UTC, jcoyne commented on app/controllers/user_versions_controller.rb
> +  rescue_from(ActiveRecord::RecordNotFound) do |e|
You have configured the test suite to not allow ActionDispatch to handle the response.  It will be handled in prod or you can switch this setting: https://github.com/sul-dlss/dor-services-app/blob/main/config/environments/test.rb#L34

2024-05-17 15:12 UTC, justinlittman commented on app/controllers/user_versions_controller.rb
> +  rescue_from(ActiveRecord::RecordNotFound) do |e|
You learn something new every day. Removing.

2024-05-17 15:16 UTC, jcoyne approved these changes

2024-05-17 15:16 UTC, merged