Refactors AuditTechnicalMetadataFileList to use RepositoryObjects.
sul-dlss/dor-services-app pull request #5013
Opened 2024-05-20 11:41 UTC by justinlittman

closes #4996

## Why was this change made? 🤔
Dro is deprecated.

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact, including data writes to shared file systems, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

QA

2024-05-20 18:37 UTC, jcoyne requested changes

2024-05-20 18:37 UTC, jcoyne commented on app/reports/audit_technical_metadata_file_list.rb
> +    Dro.where(external_identifier: druid).closed.joins(:head_version).pick(:external_identifier, FILES_FROM_RESOURCES_SQL).tap do |dro_row|
Is this `Dro` still supposed to be here?

2024-05-20 19:27 UTC, justinlittman commented on app/reports/audit_technical_metadata_file_list.rb
> +    Dro.where(external_identifier: druid).closed.joins(:head_version).pick(:external_identifier, FILES_FROM_RESOURCES_SQL).tap do |dro_row|
Nar.

2024-05-21 12:42 UTC, jcoyne approved these changes

2024-05-21 12:42 UTC, merged