allow the workspace call to return the location created
sul-dlss/dor-services-app pull request #5042
Opened 2024-05-24 21:40 UTC by peetucket

## Why was this change made? 🤔

ocrWF will be making a call to create the relevant `/dor/workspace` druid tree directory. It will not need the source path and symlink, it just wants to the workspace folder.   So this:

- removes the HB alert since we this will be the first consumer to not be sending in the source
- allows DSA to return the directory location created, so it can be used by the caller

There is a corresponding dor-services-client PR to grab the location and return to the consumer.

## How was this change tested? 🤨

Updated existing spec
Created a new spec

2024-05-25 11:40 UTC, jcoyne requested changes

2024-05-25 11:40 UTC, jcoyne commented on app/controllers/workspaces_controller.rb
> +    head :created, location: result
This seems like abuse of the location header. This response header is supposed to contain a URL.

2024-05-28 17:32 UTC, peetucket commented on app/controllers/workspaces_controller.rb
> +    head :created, location: result
Moved to body.

2024-05-28 17:32 UTC, peetucket commented
Added the ability to request the content and/or metadata subfolders be created as well.  This will be useful for the OCR work too (where we want the content subfolder if it doesn't exist).

2024-05-29 16:35 UTC, merged